### ISSUE TITLE
[FEATURE REQUEST] enum names

### ISSUE THREAD

**Issue by p3root** [asyncapi/generator#101]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/4295914/63694078-eb5b2c00-c815-11e9-85e9-f544f053fb2d.png)
Enumermations which are serialized as integer have no meaning to the user of the api.

**Can't it be tackled using specification extensions?**
Like in the open api spec.

**Describe the solution you'd like**
OpenApi example:
`{
  "openapi": "3.0.0",
  "info": {
    "title": "Swagger specification",
    "version": "1.0.0"
  },
  "components": {
    "schemas": {
      "EnumDemo": {
        "type": "integer",
        "description": "",
        "x-enumNames": [
          "Value0",
          "Value1",
          "Value2",
          "Value3",
          "Value4"
        ],
        "enum": [
          0,
          1,
          2,
          3,
          4
        ]
      }
    }
  }
}`

**Additional context**
Otherwise enums are pretty useless :/

**Comment by fmvilas** [comment]
Awesome! I'm moving it to the generator repo. The `asyncapi` repo is only for the spec and organizational issues.

**Comment by p3root** [comment]
I didn't found it in the asyncapi spec either. Anyway would be great if this feature will be implemented :)

**Comment by fmvilas** [comment]
What you described is a [specification extension](https://github.com/asyncapi/asyncapi/blob/master/versions/next/asyncapi.md#specificationExtensions). They're the same as in OpenAPI.

**Comment by p3root** [comment]
Alright. Thanks @fmvilas  :)

**Comment by derberg** [comment]
Issue moved to [asyncapi/html-template #27](https://github.com/asyncapi/html-template/issues/27) via [**ZenHub**](https://www.zenhub.com/)
