### ISSUE TITLE
[Docs Bug 🐞 report]: Fix `creating a generator template` url format

### ISSUE THREAD

**Issue by Florence-Njeri** [asyncapi/generator#1015]
### Problem
The [**Creating a generator template**](https://www.asyncapi.com/docs/tools/generator/generator_template) tutorial url -> https://www.asyncapi.com/docs/tools/generator/generator_template isn't following the standard URL format where we use hyphens to separate words in a URL but is using an underscore. 

### Proposed solution
This issue aims to bring uniformity in the tools bucket URL format by replacing the underscore URL with a hyphenated one

### Attach any resources that can help us understand the issue.

![](https://imgur.com/j6yHQbB.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by derberg** [comment]
which is the correct one that should be there?
