### ISSUE TITLE
How to check / decode channel protocolInfo in template

### ISSUE THREAD

**Issue by jdall** [asyncapi/generator#103]
I'm in the process of converting our handlebars based templates into nunjucks. Processing of the protocolInfo element is giving me some grief.

Looking at the following a2s example file
```
asyncapi: '2.0.0-rc1'
id: 'urn:hello-world-app'
info:
  title: Hello world application
  version: '0.1.0'
channels:
  hello:
    #description: "subscribe to hello's"
    subscribe:
      message:
        payload:
          type: string
          pattern: '^hello .+$'
    protocolInfo:
      nats-2-0:
        pubSub:
```
How can I check for the presence of the protocolInfo element and the nats-2-0 element within?
I currently have in my template as follows:
```
{% for channelName, channel in asyncapi.channels() %}
  {{ channel | log }}
  {% if channel.protocolInfo %}
    {{ 'found protocolInfo' | log }}
    {{ channel.protocolInfo | log }}
    {% if channel.protocolInfo.nats-2-0 %}
      {{ 'found nats-2-0' | log }}
    {% endif %}
  {% endif %}
{% endfor %}
```
which results in the following output:
```
Channel {
  _json:
   { subscribe: { message: [Object] },
     protocolInfo: { 'nats-2-0': [Object] } } }
```
where I would have liked something like:
```
Channel {
  _json:
   { subscribe: { message: [Object] },
     protocolInfo: { 'nats-2-0': [Object] } } }
found protocolInfo
protocolInfo: { 'nats-2-0': [Object] }
found nats-2-0
```
Can someone please help solving this little problem?

Thanks.

Running ag 0.11.0

**Comment by fmvilas** [comment]
Yes, sorry the parser was built with RC2 in mind already. `protocolInfo` has been renamed to `bindings`. Check out the list of changes: https://github.com/asyncapi/asyncapi/releases/tag/2.0.0-rc2.

**Comment by fmvilas** [comment]
Also, protocol bindings are being defined here: https://github.com/asyncapi/bindings. They will be separate from the main spec to make sure we can iterate faster on them without touching the AsyncAPI spec.

**Comment by jdall** [comment]
Thank you very much for this feedback, @fmvilas. That helped a lot.

I'll get back to you regarding nats.

**Comment by jdall** [comment]
Hmmm... something is a bit fishy... I cannot access the bindings element in my template. The following template code:
```
{% for channelName, channel in asyncapi.channels() %}
  {{ channel | log }}
  {{ channel.bindings | log }}
  {{ channel.bindings() | log }}
{% endfor %}
```
results in the following output:
```
Channel {
  _json:
   { subscribe: { message: [Object] },
     bindings: { nats: null, http: [Object] } } }
undefined
Something went wrong:
Template render error: (unknown path) [Line 3, Column 21]
  Error: Unable to call `channel["bindings"]`, which is undefined or falsey
```
The yaml file contains:
```
asyncapi: '2.0.0-rc2'
id: 'urn:hello-world-app'
info:
  title: Hello world application
  version: '0.1.0'
channels:
  hello:
    subscribe:
      message:
        payload:
          type: string
          pattern: '^hello .+$'
    bindings:
      nats:
      http:
        type: request
```
I've also tried with a for statement, but that also does not work.

What am I missing?

**Comment by fmvilas** [comment]
That's a bug. I'll send a fix. Thanks for reporting!

**Comment by jdall** [comment]
Since the 'bindings' element is quite strict compared to the former 'protocolInfo' element, for now I would like to define the extension 'x-protocolInfo' to the channel object (otherwise we have to change a lot before we can move forward)

Accessing it using the following syntax in the template:
```
  {{channel.x-protocolInfo | log}}
  {{channel.x-protocolInfo() | log}}
```
I get the output:
```
undefined
Something went wrong:
Template render error: (unknown path) [Line 9, Column 26]
  Error: Unable to call `protocolInfo`, which is undefined or falsey
```
Not sure if that's related to the above issue, but I just wanted to mention it.

**Comment by fmvilas** [comment]
If you want to continue like this, you have to call `channel.ext('x-protocolInfo')` or the more verbose version `channel.extension('x-protocolInfo')`.

**Comment by fmvilas** [comment]
New version of generator has been published. It fixes the problem you spotted and also adds `bindings` to the Server object. Hope it helps!

**Comment by jdall** [comment]
Thanks. That works just fine.
I will probably run with the x-protocolInfo solution for now, as it gives us the freedom we need.
In that context, I figured out that ag has an issue with element names with dashes.
The yaml:
```
    x-protocolInfo:
      nats-2-0:
        pubSub:
```
and the template:
```
  {% if channel.ext('x-protocolInfo') %}
    {{ 'found x-protocolInfo' | log }}
    {{ channel.ext('x-protocolInfo') | log }}
    {% if channel.ext('x-protocolInfo').nats-2-0 %}
      {{ 'found nats-2-0' | log }}
    {% endif %}
  {% endif %}
```
results in the errornous output:
```
found x-protocolInfo
{ 'nats-2-0': { pubSub: null } }
```
while removing the dashes gives the correct output:
```
found x-protocolInfo
{ nats20: { pubSub: null } }
found nats20
```
Am I using unsupported naming?

**Comment by fmvilas** [comment]
It seems related to Nunjucks. I think the syntax should be `channel.ext('x-protocolInfo')['nats-2-0']`.
