### ISSUE TITLE
Support protobuf schema parser

### ISSUE THREAD

**Issue by smoya** [asyncapi/generator#1033]
#### Reason/Context

https://github.com/asyncapi/protobuf-schema-parser is a Schema parser for protobuf. Adding support for it is needed in order to generate using documents that contain schemas in that format.

#### Description
In order to support that, we need to add that to the dependencies + register it in the Parser as we do with the rest [here](https://github.com/asyncapi/generator/blob/7e9e36e10631a9b9e2ddc27db8485953a0cb0fb8/lib/parser.js#L4C1-L6).

cc @GreenRover

**Comment by GreenRover** [comment]
done: issue can be closed
