### ISSUE TITLE
[Docs Bug 🐞 report]: Typo in error log

### ISSUE THREAD

**Issue by michael-ball-ctct** [asyncapi/generator#1036]
### Describe the bug you found in AsyncAPI Docs.

I apologise if this isn't strictly a "Docs" bug, but there's what appears to be a small typo in one of the error messages. I figure that's closer to being a "Docs" issue than it is a functionality one.

At [generator.js, line 264](https://github.com/asyncapi/generator/blob/master/lib/generator.js#L264) the error message currently reads 'Input is not a **corrent** AsyncAPI document so it cannot be processed.' "Corrent" isn't a word in English, so this message could be a little bit clearer. Is it meant to be "correct", or "current", or something else? My suspicion (given the context) is that it is meant to be "correct", although I would recommend updating it to be "valid" as that seems like a slightly more appropriate word.

I'm happy to make the PR if there's concensus on what the right wording is - just let me know whether this is a "docs:" or a "chore:" commit.

### Attach any resources that can help us understand the issue.

```
    if (!document) {
      const err = new Error('Input is not a corrent AsyncAPI document so it cannot be processed.');
      err.diagnostics = diagnostics;
      throw err;
    }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by derberg** [comment]
@michael-ball-ctct sorry for being late, yes, please open a PR.

`chore` will not trigger a release, so you need to do `fix` so we release a patch, and make new fixed error available in new release

**Comment by michael-ball-ctct** [comment]
@derberg Looks like Jonas bundled this change up with a bunch of other stuff 2 days after I raised it (in https://github.com/asyncapi/generator/commit/60f8e62cf391b2ff34103697af37578eafc520c6 ). I'm happy with that resolution, so closing the issue. Cheers!
