### ISSUE TITLE
Fix cognitive complexity issue

### ISSUE THREAD

**Issue by derberg** [asyncapi/generator#1040]
So `generate` command from https://github.com/asyncapi/generator/blob/master/lib/generator.js#L163 grew a bit and our code [smell checks complain](https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&pullRequest=1039&id=asyncapi_generator&open=AYrVno9ob6ubVuTTBoqq)

I think the point is valid, maybe for maintainers it is not a big problem, but for contributors, for sure.

We need help from someone to figure out how best refactor that part

**Comment by swastiksuvam55** [comment]
Hey @derberg can you please review my PR #1047 for this issue #1040 and let me know if any more modifications or refactoring is need or not.
Thank You.
