### ISSUE TITLE
We need to explain in documentation the recommended way for types generation

### ISSUE THREAD

**Issue by derberg** [asyncapi/generator#1042]
- in main overview we need clear info that if people are interested only in types/model generation, they should use modelina directly
- we also need a separate document with some example that explains that better to use modelina for models generation, if template requires it. We have examples like https://github.com/asyncapi/ts-nats-template/blob/master/template/src/models/models.js for example

@jonaslagoni wdyt?

**Comment by black-snow** [comment]
Yes please. I just opened an issue for I want models only and I only got here by accident.

**Comment by jonaslagoni** [comment]
Makes sense to me yea 👍

**Comment by derberg** [comment]
you mean it could be done better?

**Comment by jonaslagoni** [comment]
Always 😄 But yea, the integration feels a bit rough right now. Never the less we can of course document it as is and it can always be improved later.

**Comment by derberg** [comment]
ok so the scope (writing it as I put it up for bounty) is to:
- clarify in main doc, probably intro that for only-model generation better people look int modelina and use cli to generate models
- have a dedicated doc that explains that when developing template, client or server code, where models generation is also important, the modelina library should be used - and how (some code snippets)

@jonaslagoni anything specific from your side? I think https://github.com/asyncapi/ts-nats-template/blob/master/template/src/models/models.js is the best example (with additional code comments), unless you think it makes sense to have another one with custom preset? I don't think so, better link directory to modelina examples right? as it is not much about generator-functionality. Also, you would probably like to provide 2.0 version of above mentioned example?

**Comment by aeworxet** [comment]
Bounty Issue's End Of Life (EOL): [2024-02-29 23:59:59 UTC-12:00](https://time.lol/#2024-02-29T23:59:59-12:00)

**Comment by mhmohona** [comment]
Would like to work on this.

**Comment by Florence-Njeri** [comment]
Hey @derberg I'd love to work on this issue

**Comment by derberg** [comment]
Since @Florence-Njeri is a maintainer in this repo, she has priority.
For transparency: I also contacted Florence before putting this issue under bounty to make sure she has time to work on the issue as she knows the generator docs the most

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Medium          |2023-11-07                 |2023-11-13              |**2023-12-22**        |2023-11-24         |2023-12-08         |**2023-12-22**|

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.

**Comment by aeworxet** [comment]
Due to unpredicted circumstances that could not be foreseen and are beyond the control of the AsyncAPI Maintainer (@derberg), the Bounty Issue's Timeline is frozen for an indefinite amount of time.

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline Extended
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Medium          |2023-11-07                 |2023-11-13              |**[2024-01-19](https://time.lol/#2024-01-19T23:59:59-12:00)**        |[2023-12-22](https://time.lol/#2023-12-22T23:59:59-12:00)         |[2024-01-05](https://time.lol/#2024-01-05T23:59:59-12:00)         |**[2024-01-19](https://time.lol/#2024-01-19T23:59:59-12:00)**|

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.

**Comment by derberg** [comment]
@Florence-Njeri hey, do you need some help?

**Comment by Florence-Njeri** [comment]
@aeworxet  @derberg Sorry for the delay. I'm hoping to open up my draft PR by end of week. @derberg Incase of blockers I'll let you know on Slack

**Comment by derberg** [comment]
thanks @Florence-Njeri 
fyi I'm out next week cause of christmas and new years eve travel

**Comment by aeworxet** [comment]
@asyncapi/bounty_team

**Comment by Florence-Njeri** [comment]
@derberg @asyncapi/bounty_team @aeworxet here is the PR: https://github.com/asyncapi/generator/pull/1096

**Comment by aeworxet** [comment]
AsyncAPI Maintainer (@derberg) was absent online in [Slack](https://asyncapi.slack.com) for one period of three working days in a row, so all remaining target dates of the Bounty Issue's Timeline are extended by two calendar weeks.

### Bounty Issue's Timeline Extended
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Medium          |2023-11-07                 |[2023-11-13](https://time.lol/#2023-11-13T00:00:00+12:00)              |**[2024-02-02](https://time.lol/#2024-02-02T23:59:59-12:00)**        |[2023-12-22](https://time.lol/#2023-12-22T23:59:59-12:00)         |[2024-01-19](https://time.lol/#2024-01-19T23:59:59-12:00)         |**[2024-02-02](https://time.lol/#2024-02-02T23:59:59-12:00)**|

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.

**Comment by aeworxet** [comment]
@Florence-Njeri, please provide an update to the PR.

**Comment by Florence-Njeri** [comment]
Hi guys, @aeworxet @asyncapi/bounty_team I am currently addressing PR feedback from @derberg. The PR should be merged by end of week

**Comment by alequetzalli** [comment]
thank you so much @Florence-Njeri 💗

**Comment by derberg** [comment]
well done @Florence-Njeri 👏🏼 

@aeworxet I confirm bounty issue is completed
