### ISSUE TITLE
Generator crashes due to the error `[BABEL] Note: The code generator has deoptimised the styling of asyncapi-ui.min.js as it exceeds the max of 500KB.`

### ISSUE THREAD

**Issue by xserrat** [asyncapi/generator#1049]
#### Describe the bug
When generating the HTML template based on the `asyncapi.yaml` specification, I've started to receive an error related to the internal js library about `Babel`:
```
[BABEL] Note: The code generator has deoptimised the styling of /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/html-template/template/js/asyncapi-ui.min.js as it exceeds the max of 500KB.
```

#### How to Reproduce
Steps to reproduce the issue:
- Create an `asyncapi.yaml` specification and generate its yaml
- Screenshots
```
ag /app/asyncapi/asyncapi.yaml @asyncapi/html-template --force-write -o /tmp/output
[BABEL] Note: The code generator has deoptimised the styling of /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/html-template/template/js/asyncapi-ui.min.js as it exceeds the max of 500KB.
#26 ERROR: executor failed running [/bin/sh -c ag /app/asyncapi/asyncapi.yaml @asyncapi/html-template --force-write -o /tmp/output]: exit code: 137
```

#### Expected behavior
I expected a generated HTML templated based on the `asyncapi.yaml` file provided.

**Comment by jonaslagoni** [comment]
> [BABEL] Note: The code generator has deoptimised the styling of /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/html-template/template/js/asyncapi-ui.min.js as it exceeds the max of 500KB.

Is not the cause of the error 🤔 

Is it posting anything else?

**Comment by xserrat** [comment]
You're totally right:

```
[BABEL] Note: The code generator has deoptimised the styling of /usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/html-template/template/js/asyncapi-ui.min.js as it exceeds the max of 500KB.
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <ul>. See https://reactjs.org/link/warning-keys for more information.
    at li
    at Sidebar (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/react-component/lib/cjs/containers/Sidebar/Sidebar.js:47:35)
    at div
    at section
    at AsyncApiLayout (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/react-component/lib/cjs/containers/AsyncApi/Layout.js:40:23)
    at AsyncApiComponent (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/react-component/lib/cjs/containers/AsyncApi/Standalone.js:99:28)
    at AsyncApiComponent (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/react-component/lib/cjs/containers/AsyncApi/AsyncApi.js:87:28)


Done! ✨
Check out your shiny new generated files at /output/html.
```

This is the exact output running it locally. I gave you previously the output from a process that runs inside a Docker image and it seems that these warnings may affect to the crash but from your side looks perfect.

We can close the issue, sorry for the confusion 🙏🏽

**Comment by xserrat** [comment]
@jonaslagoni FYI we got an error related to the version of the html template generator. We fixed that setting the version to the compatible one (`0.28.4`):
```
docker.io/asyncapi/generator:1.13.1 /app/asyncapi/asyncapi.yaml @asyncapi/html-template@0.28.4 --force-write -o /output/html
```

**Comment by jonaslagoni** [comment]
Every logging so far only showed warnings, nothing that indicates what caused the crash 😅

And since you can successfully run it locally, it has to do with your CI setup I would assume 🤔
