### ISSUE TITLE
Report parse failure reasons

### ISSUE THREAD

**Issue by michael-ball-ctct** [asyncapi/generator#1051]
#### Reason/Context

This is a general Quality of Life improvement for anyone using the generator. By implementing this, the speed at which someone trying to process AsyncAPI docs can diagnose and understand the issues with their document formatting will significantly increase. 

#### Description

The changes for this are fairly simple. In `lib/generator.js - Generator.parseInput()` block where the document is reported as "not correct" (currently at https://github.com/asyncapi/generator/blob/master/lib/generator.js#L353 ), before the error the `diagnostics` from the error response can be looped over to `console.error` out each of the issues found before the error is thrown. Something like:
``` js
      if (!document) {
        const err = new Error('Input is not a correct AsyncAPI document so it cannot be processed.');
        err.diagnostics = diagnostics;

        for (const diag of diagnostics) {
          console.error(`Diagnostic err: ${diag['message']} in path ${JSON.stringify(diag['path'])} starting at L${diag['range']['start']['line']} C${diag['range']['start']['character']}, and ending at L${diag['range']['end']['line']} C${diag['range']['end']['character']}`);
        }

        throw err;
      } else {
        this.asyncapi = document;
      }
```

This would result in an error log being emitted before the thrown error ("Error: Input is not a correct AsyncAPI document so it cannot be processed.") such as:
```
Diagnostic err: Property "subscribe" is not expected to be here in path ["channels","user/signedup","subscribe"] starting at  L0 L185, and ending at L0 L240
```

Obviously, the exact phrasing of the error is less important than the information. `console.error("Diagnostic err:", diag);` would still be a huge improvement here (and I guess also be less brittle, as it doesn't rely so heavily on the structure of  the diagnostic objects that get returns being consistent...)

Thanks in advance for any consideration of this. I'm happy to make a PR for this if you want - just let me know which logging strategy is preferred.

**Comment by derberg** [comment]
@michael-ball-ctct lgtm, please feel free to open a PR 🙏🏼
