### ISSUE TITLE
File Location $ref Inconsistent Between `validate` and `generate` Commands

### ISSUE THREAD

**Issue by baxterjo** [asyncapi/generator#1057]
#### Describe the bug
Generator and validator do not have consistent behaviors for local file $refs when API doc is lower in the FS than where commands are being run from.

#### How to Reproduce
1. Create an API doc that references another file **below** your current position in the FS e.g.: `example_dir/example_api.yaml`
2. Create the file that is to be referenced and fill it with valid data.
3. When running the validator, the reference must be relative to the location of the API file.
4. When running the generator the reference must be relative to where the generator is run from

- Work is for a private repository so I can't provide additional data

#### Expected behavior
Both asyncapi commands should have consistent results. I believe the json schema spec for `$ref` should be relative to the api document.

**Comment by derberg** [comment]
hey there, please provide more details:
- what validator you have in mind and you do you run it
- how do you run the generator, please provide example
