### ISSUE TITLE
Generator with parameter sidebarOrganization=byTags throws error: Found non-callable @@iterator

### ISSUE THREAD

**Issue by lenartgolob** [asyncapi/generator#1059]
#### Describe the bug
I added tags to all my channels/operations and when I try to generate the file with command: 
asyncapi generate fromTemplate asyncapi.yaml @asyncapi/html-template -p sidebarOrganization=byTags --force-write 
I get this error:
[BABEL] Note: The code generator has deoptimised the styling of C:\Users\GolobL\AppData\Roaming\npm\node_modules\@asyncapi\cli\node_modules\@asyncapi\generator\node_modules\@asyncapi\html-template\template\js\asyncapi-ui.min.js as it exceeds the max of 500KB.
Generation in progress. Keep calm and wait a bit... done
Generator Error: Found non-callable @@iterator

If I try to generate documentation without the parameter or with other parameters it works fine.

### Replicate
I call my tags like this:
  "{operatorId}.*.session.started":
    description: desc. 
    parameters:
      operatorId:
        $ref: './common/parameters.yaml#/operatorId'
    publish:
      operationId: "{operatorId}.*.session.started"
      traits:
        - $ref: '#/components/operationTraits/kafka'
      message:
        $ref: './common/messages.yaml#/SessionStarted'
      tags:
        - name: session

I also tried moving the tags to messages but I get the same error

#### Expected behavior
A generated html file with side bar organization based on tags

**Comment by derberg** [comment]
Hey there, please provide examples and errors formatted with markdown code. Best, please provide full AsyncAPI documents examples for testing so we can easily replicate

**Comment by lenartgolob** [comment]
`asyncapi: '2.6.0'
info:
  title: Message Queues Documentation
  version: '1.0.0'
  description: This is a documentation for message queues
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  test:
    url: test.mykafkacluster.org:8092
    protocol: kafka-secure
    description: Test broker
    security:
      - saslScram: []
defaultContentType: application/json
channels:

  #  Session

  "{operatorId}.*.session.started":
    description: desc
    parameters:
      operatorId:
        $ref: '#/components/parameters/operatorId'
    publish:
      operationId: sessionStarted
      traits:
        - $ref: '#/components/operationTraits/kafka'
      message:
        $ref: '#/components/messages/SessionStarted'
      tags:
        - name:  Session

components:
  messages:
    SessionStarted:
      name: SessionStarted
      title: Session Started
      contentType: application/json
      traits:
        - $ref: '#/components/messageTraits/commonHeaders'
      payload:
        $ref: "#/components/schemas/SessionPayload"   
        example:
          SessionId: 660427
          SessionNumber: "S-2023/2673"
          SessionSourceId: 1
          ParkingFrom: null
          ParkingTo: null
          ConnectedFrom: "2023-10-30T07: 53: 03.557Z"
          ConnectedTo: null
          From: "2023-10-30T07: 53: 03.557Z"
          To: null
          MeterStart: 6804.3 
          MeterEnd: null
          Consumption: null
          Power: null
          RoamingTypeId: 0
          RoamingSessionId: null
          InstanceRoamingPlatformId: null
          Object: 
            Id: 75691
            ObjectFriendlyCode: "1"                 
                                                                                                                              

  schemas:
    SessionPayload:
      type: object
      properties:
        SessionId:
          type: integer
          format: int64
          description: Unique ID of the  session
        SessionNumber:
          type: string
          description: Friendly ID of the  session
        SessionSourceId:
          type: integer
          format: int16
          description: 1 - Local charge point (CSO); 2 - Roaming CDR.
        ParkingFrom:
          type: string
          format: date-time
          description: Parking start time. Normally empty if charger is not able to detect parking time.
        ParkingTo:
          type: string
          format: date-time
          description: Parking end time. Normally empty if charger is not able to detect parking time.
        ConnectedFrom:
          type: string
          format: date-time
        ConnectedTo:
          type: string
          format: date-time
        From:
          type: string
          format: date-time
        To:
          type: string
          format: date-time
        MeterStart:
          type: string
          format: date-time
        MeterEnd:
          type: string
          format: date-time
        Consumption:
          type: number
          format: float
        Power:
          type: number
          format: float
        RoamingTypeId:
          type: integer
          format: int32
        RoamingSessionId:
          type: string
          description: Roaming session id, collected from roaming partner, used as reference when communicating with partner.
        InstanceRoamingPlatformId:
          type: integer
          format: int32
        Object:
          type: object
          properties:
            Id:
              type: integer
              format: int32
            ObjectFriendlyCode:
              type: string
  
  securitySchemes:
    saslScram:
      type: scramSha256
      description: Provide your username and password for SASL/SCRAM authentication
  parameters:
    operatorId:
      description: Instance ID. Every tenant has unique ID.
      schema:
        type: integer
        format: int32                
  messageTraits:
    commonHeaders:
      headers:
        type: object
        properties:
          my-app-header:
            type: integer
            minimum: 0
            maximum: 100
  operationTraits:
    kafka:
      bindings:
        kafka:
          clientId: my-app-id
`
This is the sample document (full document is too long). There are no error, the file gets generated, but the examples are generic instead of the examples I listed. I want the generated html file to have the example I listed. When I preview the async file with VS Code Extension the examples are the ones I defined and not generated ones, but once I generate html file the genric examples show up. Also defining example for each attribute is really not an option, because the file is so long and examples are also very long.

**Comment by michaelyali** [comment]
Same issue here

**Comment by jonaslagoni** [comment]
Taking a look at this now.

**Comment by derberg** [comment]
no further feedback - assuming fixed

**Comment by jonaslagoni** [comment]
This was fixed as part of https://github.com/asyncapi/github-action-for-cli/issues/368#issuecomment-1894939063
