### ISSUE TITLE
CLI support for file name

### ISSUE THREAD

**Issue by m-mohr** [asyncapi/generator#11]
The npm package allows to set a file name for the generated file, the cli version doesn't have this flag. Would be very handy to support this option.

**Comment by fmvilas** [comment]
This is not a CLI option because templates are based in directories, not files. What you see in the package is a handy method for when you want to generate a single file. Not sure if it could be somehow used from the CLI. Ideas?

**Comment by m-mohr** [comment]
Thanks. I was speaking about the `options.file`, which is described as "Path to the file you want to generate".
I was thinking that I could set it to "something.md" and once I run `ag -o ./docs asyncapi.yaml markdown` I'd get `something.md` instead of `asyncapi.md`. Probably I misunderstood the whole "as a module" section. Is there an easy way to implement what I described? Otherwise I'm fine with just renaming the files in CI.

**Comment by fmvilas** [comment]
Oh, I understand. What you described is not what is offered as a module. `options.file` is the entry point for the template compilation. This is for templates to have multiple subtemplates. For instance, the HTML docs template has 2 versions: one with sidebar menu and one without it.

The problem with implementing what you want is that templates might result in many files (e.g. code generation), not just a single one. If you have an idea on how to make it possible, I'm all ears :)
