### ISSUE TITLE
Arrays are not working in HTML output

### ISSUE THREAD

**Issue by peters-r** [asyncapi/generator#110]
HTML outputs only `null` when working with arrays in JSON data.

```
asyncapi: 2.0.0-rc2
info:
  title: WebSockets echo server
  version: 1.0.0
servers:
  localhost:
    url: localhost
    protocol: ws

channels:
  my/chan:
    subscribe:
      message:
        $ref: '#/components/messages/echo'

components:
  messages:
    echo:
      payload:
        type: object
        properties:
          myprop:
            type: array
            items:
              type: string

```

build with: `ag -o ./doc myws.yml html`

Version:
```
ag --version
0.13.1
```

**Comment by peters-r** [comment]
There should be maybe an example using JSON in the `test/docs` folder.

**Comment by fmvilas** [comment]
Good catch. Thanks for reporting!

**Comment by bra1n** [comment]
I also just ran into this bug. Tried digging a bit into the generator / template code, but couldn't figure out what exactly caused it. asyncapi/parser seems to work fine, so it must be a generator issue.

**Comment by fmvilas** [comment]
I just tested the issue and seems to be fixed now. I'm closing the issue but feel free to reopen if you think it's not. Thanks!
