### ISSUE TITLE
Allow $$operation$$ file template

### ISSUE THREAD

**Issue by lukas-mertens** [asyncapi/generator#1116]
For the v3 spec operations are much more important for templates. Please also support `$$operation$$`. 

https://github.com/asyncapi/generator/blob/7629c168532dbc1c6504d7417242084fa7c2d2ef/docs/file-templates.md?plain=1#L6C1-L16C49

**Comment by derberg** [comment]
closing this issue

we should not add more features to Nunjucks.

and for React - functionality is already in place - we just need to properly document it -> https://github.com/asyncapi/generator/issues/1199
