### ISSUE TITLE
No need to Untagged section when byTags is true

### ISSUE THREAD

**Issue by joaoritter** [asyncapi/generator#112]
![image](https://user-images.githubusercontent.com/5597861/64138414-d7816e00-cdb1-11e9-9f77-0b788918edaa.png)

If there aren't untagged routes, no need for the untagged menu section.

Thank you for working on this project. Let me know if I can pitch in to get this issue and the other one I filed taken care of.

**Comment by rmelian** [comment]
Hi @joaoritter, thank you for submitting this issue. 

You are very welcome to send a PR
