### ISSUE TITLE
Not generate message model, just example when using `allOf`

### ISSUE THREAD

**Issue by vodanh109** [asyncapi/generator#115]
When I tried `allOf` to refer an object, the async api schema just generated empty model like below:
![image](https://user-images.githubusercontent.com/10377513/64220500-d5272d00-cef3-11e9-9541-b16e1113ef5d.png)

but the example has full properties, including extending model

**Comment by fmvilas** [comment]
Great catch. Thanks for reporting, @vodanh109!

**Comment by jonaslagoni** [comment]
I was unable to reproduce this. I used the followings API definition:
```
...
  schemas:
    lightMeasuredPayload:
      allOf: 
        - type: object
          properties:
            lumens:
              type: integer
              minimum: 0
              description: Light intensity measured in lumens.
            sentAt:
              $ref: "#/components/schemas/sentAt"
        - type: object
          properties:
            command:
              type: string
              enum:
                - on
                - off
              description: Whether to turn on or off the light.
            sentAt:
              $ref: "#/components/schemas/sentAt"
...
```
which generated:
![image](https://user-images.githubusercontent.com/13396189/68214882-8aeb2680-ffde-11e9-9e98-c215427e1080.png)

Can one of you provide an example API definition which causes this problem?

**Comment by fmvilas** [comment]
Yeah, I also can't reproduce it. @vodanh109, do you have an example?

**Comment by vodanh109** [comment]
Sorry for late reply, I tried with following files and run command:

> ag -o ./docs test.yaml html

[generator.zip](https://github.com/asyncapi/generator/files/3828074/generator.zip)

**Comment by fmvilas** [comment]
Can you please provide the content of `test.yaml`?

**Comment by vodanh109** [comment]
Sorry for late reply but it's already inside the zip file I attached

**Comment by fmvilas** [comment]
Sorry, I just asked for the content because it's not very secure to download and uncompress a zip file from an unknown source. Hope you understand.

**Comment by vodanh109** [comment]
Sorry. But in the zip has a lot of sub files becaus my docs have dependent hierarchy. If you can suggest any convinient way to share the source code for u without zip file, I will try :) Here is the test.yaml content

```
asyncapi: '2.0.0-rc1'
id: 'urn:array.example.com'

info:
  title: Very simple example
  version: '1.0.0'

channels:
  myChannel:
    publish:
      message:
        description: Simple example
        payload:
          $ref: './strategy/echo.json'

components:
  schemas:
    myObject:
      type: object
      properties:
        key1:
          title: A key
          type: string
          default: "foo"
          enum:
            - foo
            - bar
          description: Just an example enum
```

**Comment by fmvilas** [comment]
What about a Github repo? 😊

**Comment by vodanh109** [comment]
https://github.com/vodanh109/async-sample
Sorry for late reply. Here it is

**Comment by fmvilas** [comment]
I see. Please, do not use version 2.0.0-rc1 but instead use 2.0.0. Release candidates are not supported and some things have changed.

**Comment by derberg** [comment]
@vodanh109 I just used `html` template from latest master using your example and works like a charm imho:

<img width="1395" alt="Screenshot 2020-02-17 at 17 04 23" src="https://user-images.githubusercontent.com/6995927/74669517-91756680-51a7-11ea-9e15-a0be0b89178f.png">

Can you confirm?
also, notice Fran's comment about the spec version

**Comment by derberg** [comment]
unable to duplicate and anyway related issue is here already https://github.com/asyncapi/html-template/issues/11 so closing this one

**Comment by stsydow** [comment]
I experience the issue when using nested `allOf:` statements.

Here is an example:
```
asyncapi: '2.0.0'
id: allof:test
info:
  title: AllOf Test
  version: '0.1.0'

servers:
  test-local:
    url: "localhost:{port}"
    protocol: ws
    variables:
      port:
        default: "8000"

channels:
  /signaling:
    bindings:
      ws:
        method: "GET"
        headers:
          type: object
          required:
            - Sec-WebSocket-Protocol
          properties:
            Sec-WebSocket-Protocol:
              type: array
              items:
                - type: string
                  enum: ["test-v{MAJOR}.{MINOR}"]
                  description: |
                    This informs the API that you want to talk using Protocol specified in this document.
                    The version part MUST be a valid MAJOR.MINOR release of this specification.

                    The server will respond with the same version as part of the WebSocket sub-protocol negotiation.

    publish:
      summary: Send messages nested API message
      operationId: onNested
      message:
        oneOf:
          - $ref: '#/components/messages/nested_message'

components:
  messages:
    nested_message:
      name: "Composed Message"
      payload:
        allOf:
          - $ref: '#/components/schemas/specific_envelope'
          - type: object
            properties:
              payload:
                type: string
  schemas:
    common_envelope:
      type: object
      required:
        - namespace
        - payload
      additionalProperties: false
      properties:
        namespace:
          type: string
        payload:
          type: object
      descriminator:
        propertyName: namespace

    specific_envelope:
      type: object
      allOff:
        - $ref: '#/components/schemas/common_envelope'
        - type: object
          properties:
            namespace:
              enum: ['my_variant']
```

**Comment by jonaslagoni** [comment]
![billede](https://user-images.githubusercontent.com/13396189/131618034-86d94e37-ae18-4278-a554-6d09d5ff981e.png)
This has been solved.

**Comment by magicmatatjahu** [comment]
@jonaslagoni After two years 😂
