### ISSUE TITLE
Need to add proper options to generate the template from private registory using CLI

### ISSUE THREAD

**Issue by AayushSaini101** [asyncapi/generator#1156]
### Describe the bug you found in AsyncAPI Docs.

The generator can fetch the private template from the registry Reference: https://www.asyncapi.com/docs/tools/generator/using-private-template 

But there is no proper option in CLI commands how to use it to fetch the private templates that needs to be added  https://www.asyncapi.com/docs/tools/generator/usage#asyncapi-cli

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lmgyuan** [comment]
Have you tried this page to find the relevant information (https://www.asyncapi.com/docs/tools/cli/usage)? It seems to have a more comprehensive list of all the things you can do with CLI.

**Comment by derberg** [comment]
@AayushSaini101 shouldn't this be in the CLI repo?

**Comment by AayushSaini101** [comment]
> @AayushSaini101 shouldn't this be in the CLI repo?

We can close this issue as it completed in this PR: https://github.com/asyncapi/cli/pull/1399/files
