### ISSUE TITLE
[Docs Bug 🐞 report]: The `template-constant` link is broken at the generator docs

### ISSUE THREAD

**Issue by Gmin2** [asyncapi/generator#1164]
### Describe the bug you found in AsyncAPI Docs.

![image](https://github.com/asyncapi/generator/assets/127925465/a060e50b-5896-4d2d-8f4a-935de18dd4eb)

The link to the `Template Context` is broken. On clicking the Template Context it gives a 404 page.

### Attach any resources that can help us understand the issue.

![image](https://github.com/asyncapi/generator/assets/127925465/7302bac7-a0ee-43a2-bb34-dff6c0428a71)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lmgyuan** [comment]
May I ask if you are referring to a bug in this page: https://www.asyncapi.com/docs/tools/generator

**Comment by lmgyuan** [comment]
if so, I believe that the link should take the users to https://www.asyncapi.com/docs/tools/generator/template-context 

@derberg, if my solution is correct, may I ask whether I could take this issue? I would love to fix it

**Comment by derberg** [comment]
@lmgyuan you're right, please go ahead with a PR
