### ISSUE TITLE
Headers don't work in html template.

### ISSUE THREAD

**Issue by joaoritter** [asyncapi/generator#118]
The `headers` of a message does not take a `type` and a `properties` (if type=object), but the code which creates the html docs depends on there being these two properties, and the header properties under `properties` instead of under `header` directly.

![image](https://user-images.githubusercontent.com/5597861/64404887-39500b00-d032-11e9-80e2-aaf1a7b51252.png)

**Comment by joaoritter** [comment]
The simple fix would be to allow the generator to accept `headers` formatted like the `payload` is formatted.

**Comment by fmvilas** [comment]
Hey João! That's RC1 syntax and we're not supporting it anymore in favor of RC2. Headers must be a JSON Schema object with `type === 'object'` and `properties`. This was changed because, with this syntax, it wasn't impossible to say, for instance, header X is required.

**Comment by joaoritter** [comment]
That makes sense. I guess the issue is then that the HTML template doesn’t parse the new syntax.

**Comment by joaoritter** [comment]
I’d reopen the issue until the template is fixed. I tried fixing it last night to make message.headers() compatible with the schema.html partial, but no luck. I have a hacky solution for my own needs but wouldn’t feel comfortable with it in a PR.

**Comment by fmvilas** [comment]
It works for me in [playground.asyncapi.io](https://playground.asyncapi.io/) with the latest release of the generator package. The syntax is as follows:

```yaml
headers:
  type: object
  properties:
    applicationInstanceId:
      description: Unique identifier...
      type: string
```

Headers must be always an JSON Schema object.
