### ISSUE TITLE
Support platform generator type templates to infrastructure as code

### ISSUE THREAD

**Issue by emeraldjava** [asyncapi/generator#1221]
### Why do we need this improvement?

The idea here that we can extend the existing 'asyncapi generate' command to generate platform commands to create/configure the topics. 

### How will this change help?

This enables the user to leverage the asyncapi file as a form of infrastructure as code.

### How could it be implemented/designed?

On the assumption that kafka is the most popular event broker this enhancement would take the list of topic names from the ayncapi yml file, and output a set of 'kafka' style command to config the needed topics.

    kafka-topics.sh --create --topic 'topic-name-per-async-api-yml'

The existing cli supports these two options currently

    asyncapi generate fromTemplate ASYNCAPI TEMPLATE
    asyncapi generate models LANGUAGE FILE

and i'd foresee a 3rd flavour called 'platform'    

    asyncapi generate platform ASYNCAPI

which based on the broker type in yml file we'd call the relevant platform-template module.

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

Yes I am willing to submit a PR!

**Comment by emeraldjava** [comment]
As discussed on the slack channel - i opened the proposal issue here. Thanks for the suggestion. @derberg

**Comment by jonaslagoni** [comment]
makes sense to me :v:

Can easily be extended for multiple protocols 🤙 Remember to add this to the CLI not the generator though 🙂 https://github.com/asyncapi/cli

**Comment by emeraldjava** [comment]
Let me move the issue to the cli repo and an attempt to start a coded proposal.
