### ISSUE TITLE
docs no longer pushed to website

### ISSUE THREAD

**Issue by derberg** [asyncapi/generator#1264]
### Describe the bug.

after adding monorepo setup - docs update to website workflow is failing

https://github.com/asyncapi/generator/blob/master/.github/workflows/update-docs-in-website.yml#L35

the job marked with above link needs some paths update, to point to docs folder in new `apps` location

### Expected behavior

make this green: https://github.com/asyncapi/generator/actions/runs/9599491989

### Screenshots

no screen shots

### How to Reproduce

somehow run the workflow in your fork 🤔 

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by DhairyaMajmudar** [comment]
Let me give it a try, can you pls. assign @derberg

**Comment by DhairyaMajmudar** [comment]
> @DhairyaMajmudar there is one more error with path in line 42, with `_section.md` file - can you open a followup PR please?

Sure thingy : )

**Comment by DhairyaMajmudar** [comment]
> @DhairyaMajmudar there is one more error with path in line 42, with `_section.md` file - can you open a followup PR please?

Sure thingy : )
