### ISSUE TITLE
Move hooks inside monorepo

### ISSUE THREAD

**Issue by derberg** [asyncapi/generator#1270]
This repo https://github.com/asyncapi/generator-hooks needs to become part of the Generator repo just like `generator-filters`

https://github.com/asyncapi/generator-hooks must be archived and removed from org to the org with archived repos

**Comment by derberg** [comment]
As maintainer of generator I wanna work on this issue

**Comment by DhairyaMajmudar** [comment]
@derberg I would love to help on this issue, if its okay ?

**Comment by aeworxet** [comment]
### Bounty Issue's service comment

Text labels: `bounty/2024-Q4`, `bounty/medium`, `bounty/coding`
First assignment to regular contributors: [2024-09-20 00:00:00 UTC+12:00](https://time.lol/#2024-09-20T00:00:00+12:00)
End Of Life after: [2024-10-31 23:59:59 UTC-12:00](https://time.lol/#2024-10-31T23:59:59-12:00)

@asyncapi/bounty_team

##### The Bounty Program is not a Mentorship Program. The accepted level of Bounty Program Participants is **Middle**/**Senior**.
##### Regular contributors should explain in meaningful words how they are going to approach the resolution process when expressing a desire to work on this Bounty Issue.

**Comment by aeworxet** [comment]
@derberg says,

> As maintainer of generator I wanna work on this issue

https://github.com/asyncapi/generator/issues/1270#issuecomment-2352704393

**Comment by derberg** [comment]
@DhairyaMajmudar not sure much help will be needed in this one. It is medium task, and it is not complicated, but complex because of communication and amount of things that need to be done here and there.

maybe some help will be needed in https://github.com/asyncapi/generator/issues/1269

**Comment by DhairyaMajmudar** [comment]
> maybe some help will be needed in #1269

Got your point, yeah the mentioned task is a bit complicated one, what kinda help would be needed there ?

**Comment by aeworxet** [comment]
@derberg is an AsyncAPI Maintainer specified in https://raw.githubusercontent.com/asyncapi/community/master/MAINTAINERS.yaml, so they fall under the first category in the [prioritization list](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR27).

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline
|Complexity Level|Assignment Date (by GitHub)|Start Date (by BP Rules)|End Date (by BP Rules)|Draft PR Submission|Final PR Merge Start|Final PR Merge End|
|----------------|---------------------------|------------------------|----------------------|-------------------|--------------------|------------------|
|Medium          |2024-09-18                 |[2024-10-07](https://time.lol/#2024-10-07T00:00:00+12:00)              |**[2024-11-17](https://time.lol/#2024-11-17T23:59:59-12:00)**        |[2024-10-20](https://time.lol/#2024-10-20T23:59:59-12:00)         |[2024-11-03](https://time.lol/#2024-11-03T23:59:59-12:00)         |**[2024-11-17](https://time.lol/#2024-11-17T23:59:59-12:00)**        |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR224) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR99).

**Comment by derberg** [comment]
fyi, I'm a bit delayed here, lost laptop and conference travel, now a bit overwhelmed by PRs from Hacktoberfest - but all good, still on track

**Comment by derberg** [comment]
PR opened: https://github.com/asyncapi/generator/pull/1304

**Comment by derberg** [comment]
completed, new release out

- npm deprecated https://www.npmjs.com/package/@asyncapi/generator-hooks
- repo archived and moved out to repos commentary https://github.com/asyncapi-archived-repos/generator-hooks

all required work done

**Comment by aeworxet** [comment]
### Bounty Issue Is Completed 🎉

@derberg (`githubID` [6995927](https://api.github.com/user/6995927)), please go to the [AsyncAPI page on Open Collective](https://opencollective.com/asyncapi) and submit an invoice for `USD 200.00` with the expense title `Bounty generator#1270`, tag `bounty`, and full URL of this Bounty Issue in the description.
