### ISSUE TITLE
[📑 Docs]: Fix the relative paths of `index.md` & `migration.md` files.

### ISSUE THREAD

**Issue by Gmin2** [asyncapi/generator#1294]
### What Dev Docs changes are you proposing?

In the `index.md` & `migration.md`  there are many places where relative paths are wrongly placed(after the migration to monorepo) , fix the relative paths for this two particular file.

**Example**
In the https://github.com/asyncapi/generator/blob/6f60d50f3e4544d7356e8b1c8dc40380dfb87ece/apps/generator/docs/index.md?plain=1#L6
 the `AsyncAPI Document` relative path is not correct, it should be `asycapi-document.md` instead of `generator/asyncapi-document`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shubham0523** [comment]
I would love to work on the issue please assign me

**Comment by Gmin2** [comment]
We dont assign issues, just make a PR solving the issue

**Comment by Aryan4884** [comment]
@Gmin2 Raised a PR. Have a look please.

**Comment by derberg** [comment]
@Gmin2 but the paths should be valid only for asyncapi.com, where docs are rendered, not here in docs

**Comment by Gmin2** [comment]
> @Gmin2 but the paths should be valid only for asyncapi.com, where docs are rendered, not here in docs

yes @derberg

**Comment by derberg** [comment]
not sure what links you have in mind exactly, can you share?

**Comment by rajRishi22** [comment]
Hi @Gmin2 , I have fixed all links in index.js but i am unable to find the file migration.md , can you please send me path for that file.

**Comment by Gmin2** [comment]
> @Gmin2 but the paths should be valid only for asyncapi.com, where docs are rendered, not here in docs

@derberg  we should close this issue
