### ISSUE TITLE
HTML generator does not render specification extensions 

### ISSUE THREAD

**Issue by ethanballinger** [asyncapi/generator#136]
Usage is documented here: https://www.asyncapi.com/docs/specifications/2.0.0/#specificationExtensions

When providing "x-..." extensions, these are not rendered in the HTML index file.

**Comment by fmvilas** [comment]
How do you think they could be rendered? Specification extensions can have any content and can mean anything.

**Comment by ethanballinger** [comment]
So in swagger, it renders it like an attribute to the property. 

So 

`      name:
        type: "string"
        example: "doggie"
        x-pi: false
        x-pci: false  `

Would get generated as: 

name* | string
example: doggie
x-pi: false
x-pci: false

**Comment by fmvilas** [comment]
Ok, I see what you mean. Fair point.
