### ISSUE TITLE
[Feature Request] Seperated security schema files 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#138]
Hey,

I have a use case where I would like to seperate the functionality of the security schemes into files the same way messages and channels are: https://github.com/asyncapi/generator/blob/802fdb1d93d1eec400186ebd29577c105b3df047/lib/generator.js#L298-L321

### Example implementation:
 ```js
...
else if (stats.name.includes('$$securityScheme/$$')) {
	// this file should be handled foreach in asyncapi.components.securityScheme
	await this.generateSecuritySchemeFiles(asyncapiDocument, stats.name, root);
 	const templateFilePath = path.relative(this.templateDir, path.resolve(root, stats.name));
	fs.unlink(path.resolve(this.targetDir, templateFilePath), next);
}
...
```

### Detailed usecase 
Instead of adding the security to the servers themself I want to specify for each channel what the security parameters are. I am unable to find any details if this is possible through the standard definitions, so I am considering using an extension for the channel which references to a security scheme. Then the main problem arise, I want the generated security scheme to be in separate files and then after the generation implement the functionality behind it and using the --no-overwrite parameter when generating the code.

Let me know your thoughts or if i am missing something. I am willing to implement this myself if there are any interest behind it :)

**Comment by fmvilas** [comment]
Hey @jonaslagoni! I think this is a great idea. Let's move forward with this. Let me know if you need some help.
