### ISSUE TITLE
support binary files

### ISSUE THREAD

**Issue by rmelian** [asyncapi/generator#15]
The generator will break on binary files like jar files. As part of the java-spring generator a jar file needs to be copied(see picture)
![image](https://user-images.githubusercontent.com/4565267/48578769-908cbf80-e8e8-11e8-98a0-98f48bcaf744.png)

I see the method renderFile in generator.js is trying to compile all files as Handlebars templates:
`try {
      const template = Handlebars.compile(content);
      const parsed_content = template(data);
      resolve(parsed_content);
    } catch (e) {
      reject(e);
    }`

Suggested solution: declare in a config file under the template directory to declare ignore files to be compiled as  Handlebars templates.

**Comment by fmvilas** [comment]
This is a great idea. Let's work on the config file idea first.

**Comment by rmelian** [comment]
here it goes what just came out of my mind
```json
{
  "ignore": [
    ".jar"
  ],
  "schemeFiles" : {
    "amqp": [
      "src/main/java/com/asyncapi/service/AmqpConfig.java",
      "src/main/java/com/asyncapi/service/AmqpMessageHandlerService.java",
      "src/main/java/com/asyncapi/service/AmqpPublisherService.java"
    ],
    "mqtt": [
      "src/main/java/com/asyncapi/service/mqtt/"     
    ]
  }  
}
```

ignore: regular expressions for paths to be ignored
schemeFiles: paths|folders dependants on schemes to be copied 

feedbacks on this first silly version

**Comment by fmvilas** [comment]
Looks great so far. It doesn't need to be very sophisticated for now. I'd suggest using Unix globs for the paths. As a suggestion, check out the npm glob module: https://www.npmjs.com/package/glob.

**Comment by rmelian** [comment]
@fmvilas PR #17 created

**Comment by rmelian** [comment]
Hi @fmvilas can we close this issue as I merged the branch into develop

**Comment by fmvilas** [comment]
Sure! :)
