### ISSUE TITLE
[FEATURE REQUEST] Nats template for typescript

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#151]
I need a nats template for typescript.

I already started working on it so gonna do a PR as soon as it is ready :)

**Comment by fmvilas** [comment]
You're on fire mate!

**Comment by jonaslagoni** [comment]
Waiting for https://github.com/asyncapi/bindings/issues/5 to create the PR.

**Comment by Cingulara** [comment]
Will test this one as well as the .NET Core one.

**Comment by jonaslagoni** [comment]
Template public here - https://github.com/asyncapi/ts-nats-template/
