### ISSUE TITLE
[FEATURE REQUEST] Nats client for .net

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#152]
I need a nats template for .net.

I have not yet started on this, however will be starting as soon as #151 is done :)

**Comment by fmvilas** [comment]
![](https://media.giphy.com/media/bP0y34GHtOzp6/source.gif)

**Comment by Cingulara** [comment]
I will happily test this for you.

**Comment by jonaslagoni** [comment]
Template is located here - https://github.com/asyncapi/dotnet-nats-template
