### ISSUE TITLE
[FEATURE REQUEST] File watcher for the generator

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#157]
When scripting and designing websites, as well as in react etc you can enable a `watch` feature so it re-compiles or re-generates files on change.

Could this be a desired feature for the generator? I've found myself missing this feature quite a lot lately when having to debug and develop templates.

**Comment by fmvilas** [comment]
Oh yes, definitely. I feel your pain, my friend. That would be cool.

**Comment by jonaslagoni** [comment]
Fixed by #160
