### ISSUE TITLE
Introducing testing for the generator and cli 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#158]
While changing and fixing bugs for the generator there should be some indications that the generator and the cli function correctly within a PR and during development.

I am unsure if the templates themself should somehow be tested as well, not quite sure how that should be done 🤔

**Comment by fmvilas** [comment]
I guess we could test the output of certain templates under some given conditions. For instance:

AsyncAPI file: streetlights.yaml
Template: HTML
Params:
* `sidebarOrganization=byTags`

Then we compare the output with a previously stored output with the same params. In other words, an integration test :)

I know it's not ideal but it will allow us to detect what breaks whenever we add some new features or bugfixes.

**Comment by jonaslagoni** [comment]
Yea we could do that. How would we be able to store such an output though? And when changes occur to the template, how could we differentiate between the changes 🤔

**Comment by fmvilas** [comment]
We could use something like this: https://www.npmjs.com/package/files-compare.

We store (in the test folder) what we think is a good output (without bugs) and then when we add features we would have to update the stored output. Before updating, we will be able to see what changed and how by using `git dif`. It's not perfect but it's something.

**Comment by jonaslagoni** [comment]
Hmm, yea, that is a lot of files though. Would have suggested just storing known hashes of correctly generated folders and compare that. However then we would would lose the information about what changed which would take a lot more time debugging.

**Comment by fmvilas** [comment]
I know it's a lot of files but it's the result of running the generator so it shouldn't take us long to do it.

**Comment by derberg** [comment]
I think that pretty common practice for templates case is snapshot testing, and it is normal that you have to store the first, successful run of the test for future comparison

https://jestjs.io/docs/en/snapshot-testing
