### ISSUE TITLE
Java POJO generation

### ISSUE THREAD

**Issue by typekpb** [asyncapi/generator#159]
I'd be interested in using the generator for generating the Java POJOs based on the payload definition in the particular messages.

**Comment by fmvilas** [comment]
Us too! If we could have something like [this](https://github.com/joelittlejohn/jsonschema2pojo) in Node.js, that'd be perfect.

**Comment by nickspacek** [comment]
I started a bit of work on this, might have more later this week.

**Comment by nickspacek** [comment]
I wonder if it would be possible to leverage https://github.com/quicktype/quicktype for JSON Schema messages? OpenAPI has a similar need for this as well, but leveraging existing code generation for JSON Schema messages seems like it would make a lot of sense instead of rebuilding from scratch.

**Comment by fmvilas** [comment]
Totally agree. Quicktype seems to be perfect but I've seen they lack a stable/public API. Also, it seems the company behind is not interested in maintaining it beyond their needs. Maybe a good chance for a fork? 🤔

**Comment by nickspacek** [comment]
I threw together a prototype using a Quicktype filter that spits out Java mappings but haven't played around to see how robust the results are. I wondered about exploring the use of hooks or some other plugin-like approach to allow a project like generator-quicktype-models, but I haven't given it a lot of thought!

**Comment by fmvilas** [comment]
Can you share this prototype code? I'm curious.

**Comment by nickspacek** [comment]
Have a gander: nickspacek/generator@08520bc

**Comment by fmvilas** [comment]
Nice! It looks easy! I see we can probably expose the parsed AsyncAPI document in the `generate:after` hook so you don't have to parse it again.

**Comment by derberg** [comment]
@typekpb @nickspacek hi folks, you might be interested in https://github.com/asyncapi/generator/issues/216. It would be awesome to hear your opinion.

**Comment by derberg** [comment]
Folks, have a look at https://www.asyncapi.com/tools/modelina

**Comment by derberg** [comment]
closing as modelina is doing it already https://github.com/asyncapi/modelina
