### ISSUE TITLE
Support marking files as executable

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/generator#16]
### What?
When copying a file from the template to the destination directory, it should respect the file's chmod configuration. At least the executable part. For instance, when generating a Java project, we want `gradlew` to be executable.

### Why?
We should offer a ready-to-use result from the templates.

**Comment by rmelian** [comment]
I started working on this...

**Comment by fmvilas** [comment]
You're on fire mate! :fire:

**Comment by rmelian** [comment]
we can close this as the code is merged in develop branch
