### ISSUE TITLE
Local references to other files does not work when relative directory are not the same

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#166]
Given the following file structure:
```
project
└───files
    │
    └───docs
        │   asyncapi.yml
        └───components
            │   messages.yml
```
Given the `asyncapi.yml` document contains `$ref: './components/messages.yml#/lightMeasured'`
and the generator is then run in the project root, it will get the error:
```
Something went wrong:
Error: Error opening file "/project/components/messages.yml" 
ENOENT: no such file or directory, open '/project/components/messages.yml'
    at parse (/asyncapi-parser/lib/parser.js:75:11)
```

There is missing a path option to the `parse` method:
https://github.com/asyncapi/generator/blob/7479433592e2e7fc2514851740b3f1f254a73fcc/lib/generator.js#L178

**Comment by fmvilas** [comment]
Thanks for creating the issue, Jonas!

**Comment by jonaslagoni** [comment]
I really need this problem fixed :smile: So gonna do a PR soon.
