### ISSUE TITLE
Watcher not working on linux

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#169]
Given this information, https://nodejs.org/api/fs.html#fs_caveats the `recursive` option are only working on Mac and Windows.. So to support Linux, we have to use a module or hack the recursive function together our self (i.e. manually watching all sub directories).

**Comment by fmvilas** [comment]
Yeah, we can probably use a dependency instead of implementing it ourselves. [This one](https://github.com/paulmillr/chokidar) works well with Docker too. I'd put this dependency in `devDependencies` so it's not installed when running `npm install --production`.

**Comment by jonaslagoni** [comment]
Yea lets do that, should be an easy fix as well.
