### ISSUE TITLE
Not all messages, schema, parameters and security schemes are separated

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#170]
When messages are not specified in the AsyncAPI document under components they are unable to be separated into different files. Gonna use messages as example in the following, however this is also a problem for shema, parameters and security schemes.

Given that most use-cases does imply specifying messages as the streetlights example
https://github.com/asyncapi/generator/blob/82f2c809f18d15a32fc888bc2b994c5a18555901/test/docs/streetlights.yml#L87-L112

but into separate files and then referenced, I would expect that creating a template file with the name `$$message$$` would result in all messages regardless of where it is located in the AsyncAPI document, to be created into separate files.

However one could say that the `$$message$$` name should only be used for the messages specified in the components section, so I might need some verification whether this is a bug or :smile:

**Comment by fmvilas** [comment]
I think it's a bug. We can probably leverage `.allMessages` and `.allSchemas` methods from the parser. They take care of scanning all the messages and schemas respectively :)

* https://github.com/asyncapi/parser-js/blob/master/API.md#AsyncAPIDocument+allMessages
* https://github.com/asyncapi/parser-js/blob/master/API.md#AsyncAPIDocument+allSchemas

**Comment by jonaslagoni** [comment]
Yea we could, new question then, should we implement an `allSecuritySchemes` and `allParameters` to the parser or create the function for the generator?

**Comment by fmvilas** [comment]
It shouldn't be a problem because security schemes and parameters are not all over the document. In the case of security schemes, it's even easier because they **have to** be defined in the `components` section. A method to get all the parameters seems to be too specific for our use case so I'd not put it in the parser yet.
