### ISSUE TITLE
Modern C++ code generator.

### ISSUE THREAD

**Issue by giorgiozoppi** [asyncapi/generator#18]
Hello,
i loved your talk. So i decided you to help on this. In embedded enviroment there is a lack of rest framework so this will open new scenarios.

**Comment by fmvilas** [comment]
I just transferred the issue to this repo.

**Comment by giorgiozoppi** [comment]
Ok i have seen something do you have a grammar for your specification, so the parser will be easier.

**Comment by fmvilas** [comment]
Sure! Here you have a JSONSchema definition of the spec: https://github.com/asyncapi/asyncapi/blob/master/schema/asyncapi.json. You can use JSONSchema to validate against this definition.

**Comment by giorgiozoppi** [comment]
Thanks. The api generate is publish/subscribe or you can use as well plain rest, stateless?

**Comment by giorgiozoppi** [comment]
Ok for now i would like to support just kafka.

**Comment by giorgiozoppi** [comment]
The idea is to create a common interface for mimification.

**Comment by derberg** [comment]
@giorgiozoppi Hey man, where are we standing with this one? I'm cleaning up old issues to see what we have and close the ones that are not relevant anymore or dropped.
Should we keep this one open?

**Comment by giorgiozoppi** [comment]
close it.

**Comment by derberg** [comment]
thanks for quick clarification, feel free to reopen once you decide to jump back to the topic

**Comment by derberg** [comment]
@giorgiozoppi fyi, there is a side project for C++ code generator that might be interesting for ya https://github.com/pearmaster/asyncapi-codegen

**Comment by MichaelVoelkel** [comment]
> Sure! Here you have a JSONSchema definition of the spec: https://github.com/asyncapi/asyncapi/blob/master/schema/asyncapi.json. You can use JSONSchema to validate against this definition.

Dead link

**Comment by derberg** [comment]
@MichaelVoelkel 
- for C++ types code gen have a look at https://github.com/asyncapi/modelina
- regarding broken link to JSON schema - all schemas are now located in https://github.com/asyncapi/spec-json-schemas/
