### ISSUE TITLE
Generator with watcher keeps regenerating if AsyncAPI file gets overwritten but contains the same data

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#185]
Given you generate the `nodejs` template in the same directory where the AsyncAPI file is located the watcher will keep regenerate in an endless loop.

We could save the hash of the file/folder to see if any changes occurred before regenerating.

**Comment by derberg** [comment]
@jonaslagoni I think this one can be closed. Templates are no longer part of the generator. Noone will also develop a template by keeping it inside generator directory. What do you think?

**Comment by jonaslagoni** [comment]
Think this issue is still actual, if you use
`ag --watch-template --output ./outputdir ./outputdir/AsyncAPIFile.json https://github.com/jonaslagoni/ts-nats-template.git` and the template itself changes the `./outputdir/AsyncAPIFile.json` for some reason it would keep re-generate.

**Comment by derberg** [comment]
@jonaslagoni this looks like an intentional loop, or is this how you work :)

I tried `ag ../generator/test/docs/ws.yml ./ -o output --force-write -p server=localhost --watch-template` from inside the folder with the template and get constant loop with info like
```
/.../.nvm/versions/node/v12.16.1/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/nodejs-ws-template/output/src/api/index.js was changed
```

**Comment by derberg** [comment]
@jonaslagoni I think I know where is the problem, first of all, we should watch for changes exactly where the template is located, as user of cli specified, 1:1 and we should ignore directory provided with output parameter. Or am I wrong here?

**Comment by jonaslagoni** [comment]
This was a raised issue from @fmvilas with a test setup he had going. But yes your proposed solution sounds reasonable @derberg 😄

**Comment by fmvilas** [comment]
Yup. Agree with the proposed solution.
