### ISSUE TITLE
Automate docker image releases

### ISSUE THREAD

**Issue by rv0** [asyncapi/generator#187]
docker pull asyncapi/generator:latest gives you version 0.22.0 now, this version is over 2 months old ( https://hub.docker.com/r/asyncapi/generator/tags ). 
Ideally new release also create new docker images

**Comment by jonaslagoni** [comment]
Yea agree, should be automated 👍

**Comment by derberg** [comment]
after some cleanup on local, I've just pushed to docker latest 0.28.3 version with tag `0.28.3` and `latest`. Now will work on automating it.

**Comment by derberg** [comment]
Ok, my job is done, ready for review
Once it is merged I will set proper secrets for the GitHub Action flow in Settings/Secrets

**Comment by derberg** [comment]
Docker image will now always be published at the same time NPM package, once we tag the repo.

You cannot see any action here https://github.com/asyncapi/generator/actions because it won't show up until the first run of the Action
