### ISSUE TITLE
Add a way to specify the folder names

### ISSUE THREAD

**Issue by SvenMarquardt2718** [asyncapi/generator#189]
In Openapi there is a way to tell the generator the URL for the organization. E.g. 

If I tell my organization name is example.org all source code for the java project is generated under
 
`src/main/java/org/example`

This also helps with generating classes into an existing project.
But I didn't saw any way to generate folders from an input parameter or from the URL provided in the Asyncapi scheme.

**Comment by fmvilas** [comment]
You can make a template require a specific input param. Check out this example: https://github.com/asyncapi/generator/blob/master/templates/nodejs/.tp-config.json#L3.

You also have hooks. Currently, the only hook is "generate:after" and lets you run code after the project has been generated. This code could create a new folder and move files there. Here's an example on how we're using the hook to rename __.gitignore to .gitignore: https://github.com/asyncapi/generator/blob/master/templates/nodejs/.hooks/rename-gitignore.js

Also, I know @damaru-inc is working on a Java template and had this problem solved: https://github.com/asyncapi/generator/tree/feature/solace-lib?files=1.

Hope it helps! Feel free to reopen the issue if it doesn't solve your needs. Thanks!
