### ISSUE TITLE
[Feature request] Make generator html/markdown support bindings

### ISSUE THREAD

**Issue by karlwbrown** [asyncapi/generator#192]
Currently, any bindings provided seem to be left out of the HTML/Markdown.

Even if we aren't doing any validation on them, it would be valuable IMO to have the HTML/Markdown include these bindings, specified as such and basically copied as-is from the schema.

This way, if you specify some bindings in your schema definition, anyone reading those API documents will be able to see those.

In the future this could be made more sophisticated, but just pushing them out in some reasonable form would add value as a start.

**Comment by damaru-inc** [comment]
I would also like to see this. For the Solace template I'm writing, bindings are essential.

**Comment by jonaslagoni** [comment]
Yea, I agree this would be useful. Maybe we could reuse the implementation from https://github.com/asyncapi/generator/issues/136. Also since the bindings are far from stable I think this could be a suitable solution to this issue, what do you think?

**Comment by fmvilas** [comment]
👍 to @jonaslagoni suggestion. Seems like a suitable solution meanwhile bindings get stable.

**Comment by derberg** [comment]
Looks like a perfect issue for me to start with templating and having a need to understand bindings? Anyone working on it already, or can I pick it up?

**Comment by fmvilas** [comment]
I'd not work on this issue yet. Bindings specs are really unstable yet. Maybe this one is better as your next one: https://github.com/asyncapi/generator/issues/182.

**Comment by derberg** [comment]
sure thing, I thought about this one as an alternative temp solution was suggested, but #182  is also fine

**Comment by derberg** [comment]
Issue moved to [asyncapi/html-template #25](https://github.com/asyncapi/html-template/issues/25) via [**ZenHub**](https://www.zenhub.com/)
