### ISSUE TITLE
upgrade markdown-it dependency to ~10.0.0 to fix vulnerability 

### ISSUE THREAD

**Issue by nabilnaffar-sf** [asyncapi/generator#198]
https://app.snyk.io/vuln/SNYK-JS-MARKDOWNIT-459438

**Comment by fmvilas** [comment]
Agree, we should upgrade it. Do you mind sending a pull request? If you do, please don't include package-lock.json. Thanks!

**Comment by nabilnaffar-sf** [comment]
@fmvilas sure, just from curiosity why do you exclude package-lock.json?

**Comment by fmvilas** [comment]
Good question. I recently learned about [this](https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules/) so now I take care of updating package-lock myself.

**Comment by derberg** [comment]
This one will be fixed with merge of https://github.com/asyncapi/generator/pull/219
