### ISSUE TITLE
Deprecate node-codgen in favor of nodejs template

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/generator#199]
We should deprecate the node-codegen repo and npm package, showing a notice saying that the user should use the nodejs template of the generator package.

Here's the repo: https://github.com/asyncapi/node-codegen

**Comment by derberg** [comment]
@fmvilas hey, I know that you will not cleanup all repos, archive and maybe even delete few. Letting you know about this issue so you can close it once you're done.

**Comment by fmvilas** [comment]
Thanks, mate. It's archived now.
