### ISSUE TITLE
create files depending on schemes

### ISSUE THREAD

**Issue by rmelian** [asyncapi/generator#20]
here is a proposal to add a new property to the `.tp-config.json` file
```json
{
  "schemeFiles" : {
    "amqp": [
      "src/main/java/com/asyncapi/service/AmqpConfig.java",
      "src/main/java/com/asyncapi/service/AmqpMessageHandlerService.java",
      "src/main/java/com/asyncapi/service/AmqpPublisherService.java"
    ],
    "mqtt": [
      "src/main/java/com/asyncapi/service/mqtt/"     
    ]
  }  
}
```

**Comment by netoec84** [comment]
What is expected with this new property?  Please, can you give me more context about it?

**Comment by fmvilas** [comment]
Sorry, just missed your question Jose. The idea is to create certain files and/or directories depending on the protocol. For context, protocols were previously called `schemes`, so `schemeFiles` could now be renamed to `protocolFiles` or maybe find a better name.

**Comment by fmvilas** [comment]
It's now implemented as `conditionalFiles`. It doesn't only support "by protocol" but instead it compares a value with a JSON Schema definition. [Read more here](https://github.com/asyncapi/generator/blob/master/AUTHORING.md#configuration-file).
