### ISSUE TITLE
Retrieving generating html without writing to disk.

### ISSUE THREAD

**Issue by AistisT** [asyncapi/generator#200]
This was available in early versions, but seems to have been removed? Is there a reason why and is there any way without modifying the source code to achieve this?

**Comment by fmvilas** [comment]
It's still there but the way to achieve it has changed. Check out how the playground is doing it: https://github.com/asyncapi/playground/blob/master/src/server/routes/html.js#L12.

Hope it helps!

**Comment by AistisT** [comment]
That's grand, it works great.
I was looking at these options, but it sounded very much like still using a file, albeit dedicated one. Could possibly improve wording on the documentation.

**Comment by fmvilas** [comment]
Agree. Documentation could be improved. PRs welcome :)
