### ISSUE TITLE
[HTML template] Ability to auto-expand message schema

### ISSUE THREAD

**Issue by davydog187** [asyncapi/generator#202]
Hello and thank you for this great project!

# The Problem
I have nested payload structures that are 3-4 levels deep, and it is cumbersome to keep clicking to view the schema. 

# Potential Solution
It would be nice if there was an option in the generator that has nested structures auto-expanded, maybe with a parameter to specify the level of nesting that you want to stop auto-expanding. 

I could be interested in helping contribute, but would need some pointing in the right direction :) Thanks!

**Comment by fmvilas** [comment]
Hey @davydog187. Thanks for the suggestion. It would indeed be great. Any help would be much appreciated 🙏

**Comment by derberg** [comment]
Issue moved to [asyncapi/html-template #19](https://github.com/asyncapi/html-template/issues/19) via [**ZenHub**](https://www.zenhub.com/)
