### ISSUE TITLE
Separation of channels into files are not getting a suitable file name

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#203]
So, when using NATS, and I am guessing other protocols, ones channel name would be something like `smartylighting.streetlights.1.0.action.{streetlightId}.dim` and `smartylighting.streetlights.1.0.dim.*`. However these are not really suitable as file names.

Suggestion 1 is to remove `.`, `*` and parameters so the file names would be `SmartylightingStreetlights10ActionDim` and `SmartylightingStreetlights10Dim`. One problem with this is when defining these two channels `smartylighting.streetlights.1.0.action.{streetlightId}.dim` and `smartylighting.streetlights.1.0.action.dim` they would conflict.

Suggestion 2 is to replace `*` with `All`, replace `{parameter}` with `Parameter` and remove `.`. So for `smartylighting.streetlights.1.0.action.{streetlightId}.dim` and `smartylighting.streetlights.1.0.dim.*` they would become `SmartylightingStreetlights10ActionStreetlightIdDim` and `SmartylightingStreetlights10DimAll`. I cant foresee any problems with this approach :thinking:

**Comment by jonaslagoni** [comment]
Just to add, I know we should not patch the generator for specific protocols, however I think we can generalize the filename which then supports the different kind of inputs of channel names we can expect :smile:

**Comment by fmvilas** [comment]
I agree with you that something should be done. However, what worries me is that I'm not sure if the asterisk (*) is doing what you think it should do. Channel names should not have wildcards and, therefore, having an asterisk would be treated as if the asterisk is part of the channel name and not as a wildcard. Your wildcard is actually a parameter, so you should structure this as `smartylighting/streetlights/1/0/dim/{all}` (remember, use slashes not dots).

**Comment by fmvilas** [comment]
An idea for the solution would be to offer a way to hook up the generator when generating file names. This way it could be customized per template. Right now we have the `generate:after` hook. We could offer a `generate:channelFilename` hook or similar. Same for messages and schemas. What do you think?

**Comment by jonaslagoni** [comment]
🤔 When I am creating an AsyncAPI file for a NATS client, should I not use their channel definitions? Or should I stick to the general concept of channels and use something similar to `smartylighting/streetlights/1/0/dim/{all}`? 

I was thinking of taking the direct approach of specifying the AsyncAPI file as close to the implementation (NATS) as possible, hence using their [subjects](https://docs.nats.io/nats-concepts/subjects) as channels and include the [wildcards](https://docs.nats.io/nats-concepts/subjects#wildcards) directly as channel names.

**Comment by jonaslagoni** [comment]
> An idea for the solution would be to offer a way to hook up the generator when generating file names. This way it could be customized per template. Right now we have the `generate:after` hook. We could offer a `generate:channelFilename` hook or similar. Same for messages and schemas. What do you think?

Would create the most freedom, but what should the standard way generate (when nothing is specified)?

**Comment by fmvilas** [comment]
I think the default [filenamify](https://github.com/asyncapi/generator/blob/master/lib/generator.js#L439) would be ok, right? Why choosing a default if almost every language would be different 🤷‍♂

**Comment by jonaslagoni** [comment]
:thinking: Was thinking about replacing all special chars maybe, so the filename would only be alphabet and numbers. Basically the `pascalCase`, by using the  `camelCase` function from [lodash](https://lodash.com/docs/4.17.15#camelCase) with upper first character `string.charAt(0).toUpperCase() + string.slice(1)`. I mean in the end I guess I wouldn't care if I can specify it my self. However if the majority will need to use the hook then maybe we should consider changing the default :smile: However haven't used it enough to say if this will be a problem or not.

**Comment by fmvilas** [comment]
> Was thinking about replacing all special chars maybe, so the filename would only be alphabet and numbers

Isn't it what filenamify does?

**Comment by jonaslagoni** [comment]
excessive `.` are never removed from the channel name. Neither is the chars `{` and `}` for parameters. At least not when I specify the channel names as `smartylighting.streetlights.1.0.action.{streetlightId}`.

`*` are however removed. 

>When I am creating an AsyncAPI file for a NATS client, should I not use their channel definitions? Or should I stick to the general concept of channels and use something similar to `smartylighting/streetlights/1/0/dim/{all}`?
>I was thinking of taking the direct approach of specifying the AsyncAPI file as close to the implementation (NATS) as possible, hence using their subjects as channels and include the wildcards directly as channel names.

Just to quote last question @fmvilas, think you skipped it :smile: 

**Guess this issues boils down to** me suggestion channel file names should be on the form of `SmartylightingStreetlights10Event` instead of the form `Smartylighting-streetlights-1-0-event` since this is how the schema filenames are defined when the id is in the form of `turnOnOffPayload` - same with messages.

**Comment by fmvilas** [comment]
Yeah, I haven't skipped that question. I'm just assuming a world where this could be specified per template and we're now discussing what should be the default. Should we really care so much about the default way file names are generated **if we already have a way to customize it per template?**

**Comment by jonaslagoni** [comment]
> Yeah, I haven't skipped that question. I'm just assuming a world where this could be specified per template and we're now discussing what should be the default. Should we really care so much about the default way file names are generated **if we already have a way to customize it per template?**

The question was actually a more in regards to AsyncAPI and the channel paths, however taking a look at the spec again `A relative path to an individual channel. The field name MUST be in the form of a RFC 6570 URI template.` I found my answer. And in regards to the default filename, you are right, however I would prefer if it was a unified file name across the template files, i.e. for schemas, channels, messages etc. But yes, lets make it possible to customize the filename parsing and leave it as is, can always bring it up if majority of templates utilizes the same name parsing :smile:

**Comment by fmvilas** [comment]
> however I would prefer if it was a unified file name across the template files

That would be great but some languages enforce certain ways of naming the files. Like Java, for instance, the name of the file has to be the same as the class name.

**Comment by jonaslagoni** [comment]
Yes, which is also why I am suggest we use `pascal case` as the standard way to specify filenames, since this will remove all special chars and provide first letter of each word to be uppercase, i.e. `SmartylightingStreetlights10Event`. So in the end the default (when no custom hooks have been specified) filename for schemas will not vary from the filenames of channels, messages etc.

I just think it is easier to work with (when creating templates) then channels having different filenames (`Smartylighting-streetlights-1-0-event`) from schemas (`SmartylightingStreetlightsPayload` when id is `smartylightingStreetlightsPayload`), messages etc.
