### ISSUE TITLE
Watcher does not reload filters when they are changed

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#204]
When using the watcher and you change the filter it does recognize the change, however they are never applied.

**Comment by fmvilas** [comment]
Not sure why this is happening but, without looking at it, I'm suspecting the watcher is ignoring hidden files and the `.filters` directory is hidden. Actually, any file starting with a dot is treated as a hidden file.

**Comment by jonaslagoni** [comment]
> Not sure why this is happening but, without looking at it, I'm suspecting the watcher is ignoring hidden files and the `.filters` directory is hidden. Actually, any file starting with a dot is treated as a hidden file.

The watcher **is** recognizing the change in the hidden file, however when the generator is run, it will not use the new filter, but use a cached one (the one first loaded when the command was run).

**Comment by derberg** [comment]
I was able to reproduce the issue even with the current generator version where we keep templates separately and filters also separately from template files

**Comment by derberg** [comment]
after few hours of debugging I'm sure problem is here 
https://github.com/asyncapi/generator/blob/master/lib/filtersRegistry.js#L39

If I read file like `fs.readFileSync(filePath, 'utf8')` it shows new content, but `require` brings initial module and not the new one.

**Comment by derberg** [comment]
after finding where the issues is, finding fix was easy
interesting read about modules cache -> https://bambielli.com/til/2017-04-30-node-require-cache/

will provide PR soon
