### ISSUE TITLE
How do we know which params a template supports?

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/generator#207]
Right now, the way we have to know what parameters a template supports is by either looking at the code or at the human-written documentation. None of them are actually good. Looking at source code is a UX anti-pattern and human-written documentation is, well, it's very fragile and easy to forget to maintain it.

### My proposal
Make it mandatory to add a list of params to the `.tp-config.json` file. Something like this:

```js
{
  "parameters": {
    "baseHref": {
      "description": "The base URL to use on links and forms."
    }
  }
}
```

This could also be merged with the existing `requiredParams` field on the same file:

```js
{
  "parameters": {
    "server": {
      "description": "The server to use when generating the code.",
      "required": true
    }
  }
}
```

The generator could then provide a way to verify if a param is defined when accessing it from the template code. E.g.:

```nunjucks
{% if params.myUndefinedParam %}
...
{% endif %}
```

This could trigger an error if the parameter `myUndefinedParam` is not defined on the `.tp-config.json` file. Making it mandatory to define params first and impossible to forget about it.

##### Future
In the future, this information could serve us as a way to generate a template README or improve the CLI to let us know which parameters do we have available with each template.

**Comment by fmvilas** [comment]
@jonaslagoni @derberg

**Comment by basickarl** [comment]
How do we know even which templates exist? No information on that exists either.

**Comment by jonaslagoni** [comment]
> How do we know even which templates exist? No information on that exists either.

It is stated on the [website ](https://www.asyncapi.com/docs/tooling/#codegens) 

>  Please, check out the templates directory to get a list of the supported languages/formats.

However I agree we should maybe specify it directly in the main README file as well :thinking:

**Comment by derberg** [comment]
I'm with the option to simplify as much as possible so better to introduce `parameters` and merge `requiredParams` in it. I would only add that it is mandatory that it is introduced only with a feature that validates if you have your param added to the config, and the other way around, that you have params in config that are not used in template

**Comment by basickarl** [comment]
@jonaslagoni Ah I see. I think the information should either also be in the README or that the README is very explicit that the information is on a seperate website. Just so we know where to look to find what we want. We do automatically always begin with the README though.
