### ISSUE TITLE
[Nodejs template] Error: This template requires the following missing params: server.

### ISSUE THREAD

**Issue by basickarl** [asyncapi/generator#208]
Trying to generate nodejs code. Says it needs the server params. I can't find any examples of this server params, I see here https://www.asyncapi.com/docs/specifications/2.0.0/#serverBindingsObject but it's not very clear at all how the yaml should look.
```
karl@karl-Dell-Precision-M3800:~/dev/sandbox/async-api-gen$ npx ag test.yaml nodejs
Something went wrong:
Error: This template requires the following missing params: server.
    at Generator.validateTemplateConfig (/home/karl/dev/sandbox/async-api-gen/node_modules/asyncapi-generator/lib/generator.js:609:15)
    at Generator.loadTemplateConfig (/home/karl/dev/sandbox/async-api-gen/node_modules/asyncapi-generator/lib/generator.js:592:10)
    at new Generator (/home/karl/dev/sandbox/async-api-gen/node_modules/asyncapi-generator/lib/generator.js:85:10)
    at /home/karl/dev/sandbox/async-api-gen/node_modules/asyncapi-generator/cli.js:121:25
    at new Promise (<anonymous>)
    at generate (/home/karl/dev/sandbox/async-api-gen/node_modules/asyncapi-generator/cli.js:119:10)
    at /home/karl/dev/sandbox/async-api-gen/node_modules/asyncapi-generator/cli.js:71:11
    at /home/karl/dev/sandbox/async-api-gen/node_modules/mkdirp/index.js:38:26
    at FSReqCallback.oncomplete (fs.js:159:5)
```

Tried the following too:
```
karl@karl-Dell-Precision-M3800:~/dev/sandbox/async-api-gen$ npx ag --params server='herro' test.yaml nodejs
Something went wrong:
Error: This template requires the following missing params: server.
```

**Comment by jonaslagoni** [comment]
> Trying to generate nodejs code. Says it needs the server params. I can't find any examples of this server params, I see here https://www.asyncapi.com/docs/specifications/2.0.0/#serverBindingsObject but it's not very clear at all how the yaml should look.
> 
> ```
> karl@karl-Dell-Precision-M3800:~/dev/sandbox/async-api-gen$ npx ag test.yaml nodejs
> Something went wrong:
> Error: This template requires the following missing params: server.
>     at Generator.validateTemplateConfig (/home/karl/dev/sandbox/async-api-gen/node_modules/asyncapi-generator/lib/generator.js:609:15)
>     at Generator.loadTemplateConfig (/home/karl/dev/sandbox/async-api-gen/node_modules/asyncapi-generator/lib/generator.js:592:10)
>     at new Generator (/home/karl/dev/sandbox/async-api-gen/node_modules/asyncapi-generator/lib/generator.js:85:10)
>     at /home/karl/dev/sandbox/async-api-gen/node_modules/asyncapi-generator/cli.js:121:25
>     at new Promise (<anonymous>)
>     at generate (/home/karl/dev/sandbox/async-api-gen/node_modules/asyncapi-generator/cli.js:119:10)
>     at /home/karl/dev/sandbox/async-api-gen/node_modules/asyncapi-generator/cli.js:71:11
>     at /home/karl/dev/sandbox/async-api-gen/node_modules/mkdirp/index.js:38:26
>     at FSReqCallback.oncomplete (fs.js:159:5)
> ```

Hey @basickarl this is a parameter, required by the template itself here: https://github.com/asyncapi/generator/blob/master/templates/nodejs/.tp-config.json
 where it requires you to specify which of your servers from your AsyncAPI file you are generating for :)

**Comment by basickarl** [comment]
@jonaslagoni Thanks for the fast response! Could you write a example of how this is to be done.

**Comment by basickarl** [comment]
I have in my AsyncAPI 2.0.0 documentation: 
```
servers:
  production:
    url: api.streetlights.smartylighting.com:{port}
    protocol: mqtt
    description: Test broker
    variables:
      port:
        description: Secure connection (TLS) is available through port 8883.
        default: '1883'
        enum:
          - '1883'
          - '8883'
    security:
      - apiKey: []
      - supportedOauthFlows:
        - streetlights:on
        - streetlights:off
        - streetlights:dim
      - openIdConnectWellKnown: []
```
So the command:

```
karl@karl-Dell-Precision-M3800:~/dev/sandbox/async-api-gen$ npx ag --params server='production' test.yaml nodejs
Something went wrong:
Error: This template requires the following missing params: server.
    at Generator.validateTemplateConfig (/home/karl/dev/sandbox/async-api-gen/node_modules/asyncapi-generator/lib/generator.js:609:15)
    at Generator.loadTemplateConfig (/home/karl/dev/sandbox/async-api-gen/node_modules/asyncapi-generator/lib/generator.js:592:10)
    at new Generator (/home/karl/dev/sandbox/async-api-gen/node_modules/asyncapi-generator/lib/generator.js:85:10)
    at /home/karl/dev/sandbox/async-api-gen/node_modules/asyncapi-generator/cli.js:121:25
    at new Promise (<anonymous>)
    at generate (/home/karl/dev/sandbox/async-api-gen/node_modules/asyncapi-generator/cli.js:119:10)
    at /home/karl/dev/sandbox/async-api-gen/node_modules/asyncapi-generator/cli.js:71:11
    at /home/karl/dev/sandbox/async-api-gen/node_modules/mkdirp/index.js:38:26
    at FSReqCallback.oncomplete (fs.js:159:5)
```

**Comment by basickarl** [comment]
This is *not obvious* from a new person using this. This should really be documented better.

**Comment by jonaslagoni** [comment]
Agreed, as of now the decision is made to each individual templates are to contain a README file with the general knowledge of the template i.e. its features, params etc. Can you create another issue in regards to the nodejs template README file not containing proper information? on a side note, feel free to create a PR and help out if you want :+1:

**Comment by basickarl** [comment]
@jonaslagoni Ah ok, that sounds peachy pink perfect. I'll see what the flying unicorn can do.
