### ISSUE TITLE
[feature request] Golang generator would be awesome

### ISSUE THREAD

**Issue by 0x4a5e1e4baab** [asyncapi/generator#209]
Currently building a OpenAPI REST app and adding amqp functionality, would really like to use a Spec file to build out the code, rather then free hand it.

Asyncapi looks great just missing go :-)

**Comment by fmvilas** [comment]
Agree. If you can share some initial cut on how the code would look like it would facilitate things a lot :)

**Comment by jonaslagoni** [comment]
Are we talking about a Golang generator or a Golang template for AMQP? 😄

**Comment by fmvilas** [comment]
Correct me if I'm mistaken @andyhowell8, but I think he wants to generate Golang code using AMQP (a Golang template for AMQP).

**Comment by andyhowell8** [comment]
Correct @fmvilas generate Golang code using 

> (a Golang template for AMQP).

My terminology might be incorrect.

I've been using go-swagger for some time and really like the way it can build a server, client and models. 
Its a nice model, but it would be nice to see something that can build  similar stubs using Asyncapi

**Comment by fmvilas** [comment]
@andyhowell8 Can you provide some example code of Go using AMQP? That'd make it much easier for us to create a template.

**Comment by derberg** [comment]
fyi there is another related issue about Go template #31

**Comment by derberg** [comment]
Work in progress => https://github.com/asyncapi/go-template/pull/1

**Comment by derberg** [comment]
Closing this one as any work and feedback should continue here https://github.com/asyncapi/go-template/issues
