### ISSUE TITLE
Get rid of .tp-config.json and use package.json

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/generator#228]
Now that [templates are packages](https://github.com/asyncapi/generator/pull/219), we could use a custom key on the package.json file instead of having our own entire file. For instance:

```js
// package.json
{
  "name": "my-template",
  "version": "0.1.0",
  "asyncapi-generator": {
    "supportedProtocols": ["amqp", "mqtt", "kafka", "ws"],
    "parameters": {
      "server": {
        "description": "The server you want to use in the code.",
        "required": true
      }
    },
    "nonRenderableFiles": [
      "src/api/middlewares/*.*",
      "src/lib/config.js"
    ]
  },
  "dependencies": {
    // ...
  }
}
```

Thoughts?

**Comment by derberg** [comment]
I don't have a strong opinion here really:
On one hand, I like when configurations are separated per file for different packages. Separate config file for this and for that. But I also had experience with `lerna-changelog` that is configured inside `package.json` https://github.com/lerna/lerna-changelog#configuration and it was super handy as you simply maintain 1 and not 2 files. Only remark would be that we need to advise that in `package.json` config key is the last one as it can grow in size, example https://github.com/lerna/lerna-changelog#configuration

**Comment by derberg** [comment]
oh my, I have no idea what would be the name of the parameter in package.json, "tp-config" ?

**Comment by fmvilas** [comment]
`generator`? It's the config for the generator.
