### ISSUE TITLE
Integrate asyncapi-validator in Nodejs templates

### ISSUE THREAD

**Issue by derberg** [asyncapi/generator#234]
Reason:
Current Node templates nicely show what you can get from AsyncAPI file. You can generate an application that can work with Kafka or RabbitMQ, or others. When I play with those, there is one thing missing to make the templates nice, the message validation. Now you can send any message to the channel used by your application. Would be awesome to show that thanks to AsyncAPI with support of asyncapi-validator you can change that.

Description:
- Integrate https://www.npmjs.com/package/asyncapi-validator with the template
- Update docs and scratch note for release notes
- I'm wondering if it should be enabled by default or behind a parameter?

Something interesting for you @WaleedAshraf 😉

**Comment by WaleedAshraf** [comment]
🎉 Niceeee
I'd love to work on this, will try to join the next meeting and we can go from there. 👍

**Comment by derberg** [comment]
See ya tomorrow then!

**Comment by derberg** [comment]
Issue moved to [asyncapi/nodejs-template #8](https://github.com/asyncapi/nodejs-template/issues/8) via [**ZenHub**](https://www.zenhub.com/)
