### ISSUE TITLE
Introduce remote-templates support

### ISSUE THREAD

**Issue by derberg** [asyncapi/generator#235]
**Reason**:

To simplify development of the templates, and also usage of templates we want to make it possible to publish templates separately and then have an option to use them in a generator from a remote location.

**Description:**
- we should not only support calling a template from a local directory, but also from remote location. NPM? Git? URL? check out how similar tools like yeoman are doing it
- have some kind of autodiscovery/registry mechanism so user can easily list available templates. With NPM it could be solved with the support of tags in package.json and NPM API
- it should be clear which templates are officially supported by asyncapi maintainers and which ones are not
- update docs!

**Comment by johndcarmichael** [comment]
Is anyone already working on this?

**Comment by fmvilas** [comment]
Not yet but it's top priority right now so we should start working on it probably next week.

**Comment by johndcarmichael** [comment]
How will you solve the core and template dependency alignment issue?

The initially just pulled them in via git but then when the core brought in new features or a new format the older tpls started to break so we went with a quick and dirty solution of tagging the tpl git branches then comparing again the core npm version: https://github.com/acrontum/openapi-nodegen/blob/master/src/lib/template/TemplateFetch.ts#L183

**Comment by fmvilas** [comment]
I'm happy that you ask. This was partially solved already: https://github.com/asyncapi/generator/pull/219.

There's also this issue: https://github.com/asyncapi/generator/issues/237.

Everything related to making the Generator stable (i.e., v1.0.0) is our top priority so all these features/fixes should be implemented soon.

**Comment by johndcarmichael** [comment]
Nice! Looking forward to it :+1:

**Comment by jonaslagoni** [comment]
Implemented in https://github.com/asyncapi/generator/pull/261

**Comment by fmvilas** [comment]
Thanks, man! 👍
