### ISSUE TITLE
Separate current templates from generator repository

### ISSUE THREAD

**Issue by derberg** [asyncapi/generator#237]
**Reason:**

Generator repo should only consist of the "core" of the generator and once we have 'remote-templates' support, templates should be developed and released separately. This will make onboarding and development aka contributions easier

**Description:**

- move templates to a separate repo. One with monorepo setup with lerna or other tool that will simplify development, or as many as we have templates, but then introduce some naming convention.
- think about pros and cons of monorepo vs separate. For sure with monorepo we won't be able to use GitHub releases, and tagging will be strange because if here https://github.com/asyncapi/generator/issues/235 we go with NPM and sem-ver, then proper versioning will be important for a project

Hints:
- Except for #235 that blocks this issue, it would be also nice to have this #212 done first, before we move templates to separate repositories (if we do not do monorepo)
- Conventional commits support monorepos by allowing to have a scope indication on the commit message, like `feat(markdown): add some new thing to markdown template` so CI can properly identify that the version bump should be done only for markdown template

**Comment by RobertDiebels** [comment]
Might I propose creating an `@asyncapi` scope on npm.
- Will aid users when searching for AsyncAPI related packages.
- Will clarify which packages with `asyncapi` in their name are maintained by AsyncAPI collaborators.
- May be useful in the future if there are going to be more separate templates maintained by AsyncAPI collaborators. 

I'm not sure whether this should be a stand-alone issue or part of this one. Just thought I would mention it.

**Comment by derberg** [comment]
@RobertDiebels we have it already https://www.npmjs.com/search?q=%40asyncapi and templates are already published with the scope. Other packages? should to. I'm now working on release automation for generator #225 , and then parser and I will make sure we publish with @asyncapi scope

**Comment by RobertDiebels** [comment]
@derberg Ah nice! Before I commented I only checked the main packages `generator`, `parser`, etc. I was not aware that we already had separate packages for the templates 👍 . You can disregard my comment in that case.

**Comment by fmvilas** [comment]
This was fixed by #261
