### ISSUE TITLE
Schema file templating should return all schemas of type Object 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#239]
**Reason**
From a templater's point of view it would make sense if the `$$schema$$` file template returned all object type schemas so it is possible to reduce generated code complexity, and making it possible for templates to easily take the object oriented approach.

**Hints**
- Discussion in [slack](https://asyncapi.slack.com/archives/CQVJXFNQL/p1583333853010200) about an issue with the `$$schema$$` file template not generating nested schemas together with a discussion in an [issue in the parser](https://github.com/asyncapi/parser-js/issues/32) triggered this issue.
- This issue is blocked by an [issue in the parser](https://github.com/asyncapi/parser-js/issues/39)

**Comment by Tenischev** [comment]
Hey @jonaslagoni 
Mentioned issues [parser-js/32](https://github.com/asyncapi/parser-js/issues/32) and [parser-js/39](https://github.com/asyncapi/parser-js/issues/39) are closed.
Now we have a description for `$$everySchema$$` in [File templates](https://github.com/asyncapi/generator/blob/master/docs/authoring.md#file-templates)
Is there anything that can be improved?

**Comment by jonaslagoni** [comment]
@Tenischev we have to decide if we want to add another file template like `$$objectSchema$$` or change an existing one and the implement it. Nothing should be blocking this issue 😄
