### ISSUE TITLE
Array-level examples do now show up in Topics section

### ISSUE THREAD

**Issue by fridgerator** [asyncapi/generator#25]
They do show up in the Schemas section however:

```yml
topics:
  example:
    subscribe:
      description: Example topic
      payload:
        $ref: '#/components/schemas/example'

components:
  schemas:
    example:
      type: array
      items:
        type: number
      example: [35.4, 38.6, 46.7, 66.5]
```

Assuming an HTML generated document.

The example within the "Topics" section just shows an empty code block.  However in the schemas section section the example shows correctly.

This works the same using the online editor, as well as with the `ag` cli.

**Comment by fmvilas** [comment]
Thanks for reporting @fridgerator. Will have a look at soon as I can.

**Comment by my0n** [comment]
First PR I guess, tell me what you think. I tried to make the changes as noninvasive as possible. I also noticed that the same issue happens with messages, so I fixed that in the html template, too.
