### ISSUE TITLE
Make generator support installing remote templates

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/generator#251]
Changes this issue must introduce:

1. The syntax must now be something like `ag [options] <asyncapi> <templatePath|templateUrl|templatePackageName|templateGitUrl>`
1. All templates are now treated as "remote".
1. Rename the `-w, --watch` flag to `--watch-template`. Let's leave `-w, --watch` for "watching" the AsyncAPI file. Show a warning when the template directory under `node_modules` is not a symlink (i.e., it's a remote template).
1. Slightly change the meaning of `--force-install`. It will now install the template **and** its dependencies.
1. Remove the `-t, --templates <templateDir>` flag. Keep reading to know why.

Installation is handled by the `npm install` command, which supports the following syntax:
```
npm install [<@scope>/]<name>
npm install [<@scope>/]<name>@<tag>
npm install [<@scope>/]<name>@<version>
npm install [<@scope>/]<name>@<version range>
npm install <git-host>:<git-user>/<repo-name>
npm install <git repo url>
npm install <tarball file>
npm install <tarball url>
npm install <folder>
```

Therefore, the current `-t, --templates <templateDir>` flag can be removed and will always point to the `node_modules` folder of the generator. That will allow us to benefit from the npm cache system too.

### What if I have a local template? Will I have to place it inside `node_modules`?

No, you can keep working as usual. `npm install` will create a symlink to your folder and will place it under `node_modules`.

### Why depending on npm install?

It is much easier for us to rely on npm to do the job. We get a lot for free, including the cache —and a mechanism to skip it. In any case, we already had a dependency on npm when we decided to convert templates to npm packages (#219).

**Comment by fmvilas** [comment]
I'm starting work on this.

**Comment by jonaslagoni** [comment]
Are you going to keep the local way for remote templates i.e. `ag http://github.com/somerepo ./path/to/docs <<template name>>` or is it going to be something else? :smile:

**Comment by fmvilas** [comment]
Happy that you ask. I just updated the description with what I think this issue should modify :)

**Comment by fmvilas** [comment]
While working on this, I realized the `--force-install` flag doesn't make sense anymore. Or, another way to see it is that the `--force-download` is not necessary and we'll have to slightly change the meaning of `--force-install` and it will not take into account the existence of `node_modules` anymore.

I'm updating the description with the following:

```markdown
Changes this issue must introduce:

1. The syntax must now be something like `ag [options] <asyncapi> <templatePath|templateUrl|templatePackageName|templateGitUrl>`
1. All templates are now treated as "remote".
1. Rename the `-w, --watch` flag to `--watch-template`. Let's leave `-w, --watch` for "watching" the AsyncAPI file. Show a warning when the template directory under `node_modules` is not a symlink (i.e., it's a remote template).
-> 1. Slightly change the meaning of `--force-install`. It will now install the template **and** its dependencies.
1. Remove the `-t, --templates <templateDir>` flag. Keep reading to know why.
...
```
