### ISSUE TITLE
Generate markdown for the specs with the events 

### ISSUE THREAD

**Issue by ogpop** [asyncapi/generator#26]
I’ve tried to use  [slack's asyncapi definition](https://github.com/slackapi/slack-api-specs/blob/master/events-api/slack_events_api_async_v1.json) with asyncapi-generator (v0.5.1) to generate markdown and it works fine, but when I try the one with the `events` , rather than `topics` ,  from your repo 
https://github.com/asyncapi/asyncapi/blob/master/test/docs/slack-rtm.yml

It fails with an error: 
```
Something went wrong:
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at module.exports (C:\ … \npm\node_modules\as
yncapi-generator\lib\beautifier.js:163:43)
    at parse.then (C:\ :\ … \npm\node_modules\asynca
pi-generator\lib\generator.js:284:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Online editor  http://editor.asyncapi.org/   fails to parse it as well , with an error 
```
Cannot convert undefined or null to object
```
The concept of `events` seems to be much more appealing in documenting our websockets api, would really like to make it work, not sure what’s am I missing? Is there any other tool I could use to generate the documentation?

Thanks.

**Comment by fmvilas** [comment]
Yeah, this is a missing feature in this markdown template. Let me get this fixed, shouldn't be hard. Thanks for reporting!

**Comment by ogpop** [comment]
That's great, thank you so much!

**Comment by fmvilas** [comment]
@ogpop version 0.6.0 has been published with this issue fixed. Let me know how it works!

**Comment by ogpop** [comment]
Thank you @fmvilas! I was able to generate the markdown.
