### ISSUE TITLE
Kafka client generator for java

### ISSUE THREAD

**Issue by venth** [asyncapi/generator#267]
#Hi guys,

I try to generate Kafka client for java using java-spring. Unfortunately, this template seems to be not working. Although it generates some classes, it doesn't generate any messages nor client classes. I have seen also that it supports MQTT and AMPQ protocols, so Kafka is out of scope.

Does anyone know generator handling java client for Kafka as target?

**Comment by derberg** [comment]
Hi Artur,

Yes, we know that current template is not perfect, you can have a look on other issues https://github.com/asyncapi/generator/issues?q=is%3Aissue+is%3Aopen+java.

I know that @fnobilia planned to look into it and try contributing, but the times are busy now.

There is also another Java template that is almost ready, @damaru-inc works on it, and PR with init version is there already https://github.com/asyncapi/java-spring-cloud-stream-template

**Comment by venth** [comment]
Thanks for the answer 😀

**Comment by Tenischev** [comment]
Hey @venth 
The java-spring template was a little bit updated, please check the current state.
For further suggestions to improve i think better to use https://github.com/asyncapi/java-spring-template/issues

**Comment by venth** [comment]
OK, thanks 👍
