### ISSUE TITLE
Watcher crashes: no such file or directory

### ISSUE THREAD

**Issue by floriandejonckheere** [asyncapi/generator#271]
Even though generating the document works, when using the `--watch-template` switch it seems to crash the generator with the following error:

```js
[WATCHER] Watching for changes in the template directory /Users/florian/.nvm/versions/node/v12.4.0/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/markdown-template and in the AsyncAPI file /Users/florian/Code/nephroflow-provider/documentation/api.yaml
Something went wrong:
Error: ENOENT: no such file or directory, lstat '/Users/florian/.nvm/versions/node/v12.4.0/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/markdown-template'
```

This directory indeed does not exist. Explicitly installing the templates using NPM does not work either. Copying the installed templates from `/Users/florian/.nvm/versions/node/v12.4.0/lib/node_modules/@asyncapi/` to `/Users/florian/.nvm/versions/node/v12.4.0/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/` seems to fix the issue.

**Comment by derberg** [comment]
Hi @floriandejonckheere, thanks for reporting the issue. Can you please share some more details, as I'm nvm user and did not encounter issues described by you:

- do you use generator a library or cli client?
- what npm version you have
- what do you mean by `Explicitly installing the templates using NPM does not work `? can you share commands you use so I can try to reproduce?

**Comment by derberg** [comment]
I just checked with latest generator, installed `npm install -g @asyncapi/generator` and then did `ag asyncapi.yaml @asyncapi/nodejs-template -o output -p server=mosquitto` and it worked well, dependency was installed in the folder where I ran the CLI client and not in nvm directory. 

I basically went through updated https://www.asyncapi.com/docs/tutorials/streetlights/#generating-code and all worked well

**Comment by floriandejonckheere** [comment]
I'm using Node v12.4.0 and NPM 6.9.0. I'm using the generator CLI to build a markdown/HTML document out of a spec.
By explicitly installing I meant installing the templates globally (`npm install -g @asyncapi/html-template`), but as it seems the templates are install locally.

I've reinstalled all packages and it worked without a hitch, same when using Node 13.12. So I guess I'm closing this issue.

Thanks for your fast response!

**Comment by derberg** [comment]
@floriandejonckheere no problem, happy I could help. I will release today a GitHub action for the generator that you can easily integrate with GH pages publishing. Letting you know in case you are looking for some automation
