### ISSUE TITLE
No help topic for './asyncapi.yaml'

### ISSUE THREAD

**Issue by basickarl** [asyncapi/generator#279]
```
karl@karl-Dell-Precision-M3800:~/dev/asy$ npx ag ./asyncapi.yaml @asyncapi/html-template -o ./docs_our
No help topic for './asyncapi.yaml'
```

What does this mean?

I have a specification (asyncapi.yaml) I'm trying to output as html (docs_our directory).

**Comment by derberg** [comment]
@basickarl Hey man, I don't think you can run packages like that with `npx`. Npx needs a real name of the package so it can download it first from npm to its cache. `ag` is the name of the CLI client after it is installed and you install it like `npm install -g @asyncapi/generator` so I believe you shoud try this instead `npx @asyncapi/generator ./asyncapi.yaml @asyncapi/html-template -o ./docs_our`

**Comment by basickarl** [comment]
@derberg I normally install things to my devDependencies then use npx to access it instead of installing things globally, well it's what I am doing now but doesn't seem to work?

I can get the ag help menu up, but after that I'm stuck :/

**Comment by basickarl** [comment]
```
karl@karl-Dell-Precision-M3800:~/dev/asy$ npx ag
NAME:
   ag - A secure, shared workspace for secrets

USAGE:
   ag [global options] command [command options] [arguments...]
   
VERSION:
   0.9.0
   
COMMANDS:
     help, h  Shows a list of commands or help for one command

   ACCESS CONTROL:
     allow     Grant a team permission to access specific resources
     deny      Deny a team permission to access specific resources
     policies  View and manipulate access control list policies

   ACCOUNT:
     login   Log in to your Arigato account
     logout  Log out of your Arigato account
     prefs   View and set preferences
     signup  Create a new Arigato account which, while in alpha, requires an invite code
     verify  Verify the email address for your account

   CONTEXT:
     link    Link your current directory to Arigato
     status  Show the current Arigato status associated with your account and project
     unlink  Remove the link between this project and Arigato

   ORGANIZATIONS:
     envs      View and manipulate environments within an organization
     invites   View and accept organization invites
     keypairs  View and generate organization keypairs
     orgs      View and create organizations
     projects  View and manipulate projects within an organization
     services  View and manipulate services within an organization
     teams     View and manipulate teams within an organization

   SECRETS:
     run    Run a process and inject secrets into its environment
     set    Set a secret for a service and environment
     unset  Remove a secret from a service and environment
     view   View secrets for the current service and environment

   SYSTEM:
     daemon   Manage the session daemon
     version  Display versions of utility components

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
```

As you can see ag works :/

**Comment by basickarl** [comment]
Ok made it work, not the most user friendly way though...

1) clone the generator repo
2) put your shell inside the repo root directory
2) node cli.js asyncapi.yaml html -t templates/ -o test_dir --force-write

**Comment by derberg** [comment]
@basickarl oh man, sorry it took me so much time to look into it again 😞 

What you described above is much complicated than just using generator cli in official way.
I just played a bit with npx and made it work:

`npx -p @asyncapi/generator ag ./asyncapi.yaml @asyncapi/html-template -o ./docs_our`

Please confirm if it works well for you. We could add it to official readme as one way of running generator

**Comment by derberg** [comment]
also, regarding devDependency, if you have generator there already, why using npx? and not adding npm script like "generate-docs": "ag ./asyncapi.yaml @asyncapi/html-template -o ./docs_our" -> this should work without global installation of the generator

**Comment by derberg** [comment]
no further response,
main readme was extended with npx instructions,
closing
