### ISSUE TITLE
Generate stomp/sockjs typescript client

### ISSUE THREAD

**Issue by mpodlodowski** [asyncapi/generator#28]
I would like to provide generator for stomp over sockjs AsyncAPI.
It would be useful for consuming Spring Stomp over SockJS APIs in node/browser env - especially in companion with swagger-generated typescript-fetch client.

Is there something I should be aware of before starting my work on it?

**Comment by derberg** [comment]
@mpodlodowski Hey man, where are we standing with this one? I'm cleaning up old issues to see what we have and close the ones that are not relevant anymore or dropped.
Should we keep this one open?

**Comment by mpodlodowski** [comment]
Hey. No time to work on this ATM. Please close this one. In case I'll have
some time to work on it we can always reopen.

sob., 15 lut 2020, 17:25 użytkownik Lukasz Gornicki <
notifications@github.com> napisał:

**Comment by derberg** [comment]
Thanks a lot for fast response!
