### ISSUE TITLE
Requesting README Updates

### ISSUE THREAD

**Issue by Mrc0113** [asyncapi/generator#285]
The getting started experience could be made a bit easier with some relatively simple updates to the README.md. 

I suggest the following: 
* A link for how to install npm (useful for non-node devs)
* Should have a list of available templates since they are now in other repos
* The example command assume that you know _markdown_ is a template, this should be clarified
* Usage should say `AsyncAPI Document` or `AsyncAPI Specification File` instead of just `asyncapi`. It should also specify if it needs to be yaml, json or either
* While not really a README thing, it would be ideal if the generator would print out the parameters that were passed in so it's clear that the generator read them in properly from the command line.

**Comment by derberg** [comment]
Great ideas @Mrc0113 
- for npm installation, we could also provide in readme alternatives, like `yarn` or event `npx`
- list of templates is always hard to keep up to date, you think this link that we provide there is not enough? https://github.com/search?q=topic%3Aasyncapi+topic%3Agenerator+topic%3Atemplate. Or is it confusing that we provide list from GitHub while best is to use npm releases?
- which `markdown` example are you referring to?
- totally agree with being more specific in Usage section
- that would be separate change, but not hard to do. I like the idea of printing out info about parameters applied to the template

**Comment by Mrc0113** [comment]
Sounds good @derberg!

* Agree on npm alternatives like `yarn` & `npx` being included if you'd like. I'm not a node dev so not the right person to ask ;) 
* That templates list link didn't work for me. The idea could work, but I also don't think there will be a ton of code generators always popping up so it shouldn't be too hard to just add them in manually. Or maybe there is a way to use github actions to automatically make a PR when new repos are added to your search terms? 
![image](https://user-images.githubusercontent.com/1815312/78297413-8418ff00-74fd-11ea-8ca6-f7d38a3f21df.png)
* Nevermind! Looks like `markdown` was replaced with `html-template`. This is more clear

**Comment by derberg** [comment]
@Mrc0113 hey man, would you mind having a look on this PR https://github.com/asyncapi/generator/pull/355/files. Please let me know if the changes make readme better now. Readme preview https://github.com/asyncapi/generator/blob/6942f9f3180219e500869449ab0111fe78ce3994/README.md
