### ISSUE TITLE
Do not create node_modules directory

### ISSUE THREAD

**Issue by Mrc0113** [asyncapi/generator#289]
It would be ideal to not leave behind a `node_modules` directory in the directory that you run the "ag" command from to generate an app. I'm not a node dev so I'm not sure if there is an established pattern for things like this but I would expect that it should be in a hidden directory in the user's home or maybe under /tmp?

**Comment by fmvilas** [comment]
That's really weird. This should not be happening. By default, npm installs global modules on `~/.npm`. I'm assuming you're using Windows. @jonaslagoni is this happening for you too?

**Comment by jonaslagoni** [comment]
Yes, this is also happening for me.

**Comment by Mrc0113** [comment]
@fmvilas, I'm actually on Mac
