### ISSUE TITLE
Java/Scala (maybe Akka?) code generator

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/generator#29]
It would be awesome to have the chance to generate Java/Scala code from the AsyncAPI spec. Not an expert in Java/Scala but by some quick research I found [Akka](http://akka.io) to be the most popular. Please "javers" correct me if I'm wrong.

**Comment by derberg** [comment]
I'll close this issue as it was about AsyncAPI 1 and discussion about current template pain points and support for 2.0 happen here #134
