### ISSUE TITLE
generator.generateDirectoryStructure fails on Windows

### ISSUE THREAD

**Issue by kylemc** [asyncapi/generator#3]
https://github.com/asyncapi/generator/blob/05bd359fad0afc6c6bd3d7f0d9b28f5cffd0fcd1/lib/generator.js#L152

It's the slashes. I would have submitted a PR, but I wasn't sure the right way to do it in node. The following does work, though.

        if (!file_path.startsWith('.partials') && !file_path.startsWith('.helpers')) {

**Comment by fmvilas** [comment]
Thanks for reporting @kylemc. It's fixed and published on npm now.
