### ISSUE TITLE
Python 2.7 code generator

### ISSUE THREAD

**Issue by marcb** [asyncapi/generator#30]
In many enterprise environments there are restrictions on what agents can be written in… sometimes Node.js isn't allowed.

**Comment by derberg** [comment]
@marcb  Hey man, where are we standing with this one? I'm cleaning up old issues to see what we have and close the ones that are not relevant anymore or dropped.
Should we keep this one open?

**Comment by derberg** [comment]
I'm closing this one, Python-related template for the generator is under development here -> https://github.com/asyncapi/python-paho-template
