### ISSUE TITLE
Add hooks generate:before

### ISSUE THREAD

**Issue by Tenischev** [asyncapi/generator#308]
#### Reason/Context
Hooks launched before generation will allow modifying asyncApi before processing the template.
Also they could be used to remove some part of template which is not relevant for protocol in specified asyncapi.

#### Description
In theory, adding of `await this.launchHook('generate:before');` [here](https://github.com/asyncapi/generator/blob/master/lib/generator.js#L147) will solve this.

**Comment by fmvilas** [comment]
I think that makes sense. When I added the "after" hook, I knew at some point we would have to add this one but couldn't come up with a use case. Thanks for raising this issue 🙂
