### ISSUE TITLE
Go code generator

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/generator#31]
It would be awesome to have a code generator for Go. Anyone around who wants to participate?

**Comment by vgarvardt** [comment]
I'm working on one now but I definately need some help. At the moment have simpe strcut generation for messages but need to add some tests.

**Comment by fmvilas** [comment]
Hey @vgarvardt! I'm planning to work on one too. [Join the Slack channel](https://asyncapi.com/slack-invite) and let's work together on this.

**Comment by fmvilas** [comment]
Lovely! Thanks for sharing!

**Comment by derberg** [comment]
@vgarvardt hey man, are you still in the topic? I don't think that @fmvilas is still involved in writing a template but seems more people are interested #209 so would be good to join forces maybe?

**Comment by derberg** [comment]
Closing this one
Discussions should be under one issue https://github.com/asyncapi/generator/issues/209
