### ISSUE TITLE
Documentation for hooks are not updated 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#320]
#### Describe the issue
Hook implemented in #315 are not updated in the [hook documentation](https://github.com/asyncapi/generator/blob/master/docs/authoring.md#hooks)

**Comment by jonaslagoni** [comment]
Think I am a bit sleepy 🛌

**Comment by fmvilas** [comment]
LOL, I just told @Tenischev to convert it to a table for better readability: https://github.com/asyncapi/generator/pull/315#discussion_r417919531.

@Tenischev, It didn't work mate :trollface:
