### ISSUE TITLE
Feature Request - add a "-name" type of parameter that specifies the name of the file produced

### ISSUE THREAD

**Issue by Cingulara** [asyncapi/generator#331]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement? More of a "want" than a "need". We can always rename the file later. I am looking to generate HTML, MD, etc. in a CI/CD pipeline and want to direct the name and location of the file in the pipelines. I will eventually put all these files in one place as HTML (the plan so far) as a catalog. But I want the "asyncapi.yaml" to be a defined name for the source in each repo. I cannot have "asyncapi.md" or "index.html" be generated for every single repo and message from the pub/sub folks.
- How will this change help? It will let you specify the output file specifically so it fits whatever naming convention you choose now or later, and can automate it.
- What is the motivation?  See above.

#### Description
Please try answering few of those questions
- What changes have to be introduced? 
The main generator would need to take in a filename or output file name attribute, validate it is a valid name (regex?) and then use it with the template generator's .xxx filename for a complete filename.
- Will this be a breaking change? I do not think so. It would default to the name of the file for the source. 
- How could it be implemented/designed?
Add a new parameter, defaulted to the filename of the source, but allow using the new name passed in if a valid name. If not a valid name, then error and do not process it. Make people fix the name or remove it and use the default name.

**Comment by derberg** [comment]
@Cingulara Hi, sorry but I have to ask few followup questions/clarifications to fully understand.

I understand that you are referring to https://github.com/asyncapi/markdown-template and https://github.com/asyncapi/html-template. While in a case or markdown case is pretty straight forward, and there is just one file generated, I'm not sure how you see it with HTML template.

HTML template produces not only HTML but also a bit of JS and CSS. You want to change names there too? 🤔 you really have a use case to change `index.html` to something different?

This use case is feasible for md/html, but not really for code templates. 
we have similar PR opened, but for different type of template files -> https://github.com/asyncapi/generator/pull/323

**Comment by Cingulara** [comment]
I see #323 that may work when I see it in action. And yes, my mind right now is mainly on the HTML and Markdown templates. Not sure if this request would go in those specific template repos or here as I am brand new to all of this. 

For Markdown, specifying the name of the file would make the ".md" filename specific. 

For HTML in my head at least, specifying the name of the file would make the "index.html" filename another "xxxxxx.html".  It looks like the JS and CSS are boilerplate so I would only need to use one set of those. Please correct me if I am wrong on that. Those would stay the same. 

Yes I have a use case for this. I plan to put all the HTML files into a single place to show a catalog. We have 2 publishers, 5 subscribers for messages in a pub/sub setup and we also have websockets in use. The websockets have 3 messages that go up to the browser client and 5 that come from the browser and go back out to the message bus. The websockets are all in one webserver. The plan was to document all of these in AsyncAPI and generate the MD files for the repos, as well as generate all HTML files for putting into a web-based catalog similar to Kong API GW's Developer Portal in essence. 

Right now I can do that. I just have to rename the HTML files in my pipeline so I do not have 8 different index.html files and 8 asyncapi.html files. And I want to standardize the "asyncapi.yaml" filename so we know exactly what the file is in the repos we use for the code. 

FYI we have 8 repos that will deal with messages. Each service or message client has its own code repo and its own CI/CD pipeline for generating tests, code, docs, artifacts, etc.

There may be a better way to do this. If you see it please let me know so I can try a few things to see what fits our team and codebase. Documenting our message structure like this is a must for sure.

**Comment by derberg** [comment]
#323 will for sure not work for you as it is strictly related to this feature https://github.com/asyncapi/generator/blob/master/docs/authoring.md#file-templates. But the idea is similar, you basically want to influence the name of the file that will be output by the generator.

If there would be a support for hooks that can be plugged into generator when it generates output, then we could have a hook that could be used in HTML and markdown to rename output 🤔 

One more thing, you mentioned that you rename files with scripts in pipeline, right? so you do not need to have the file name influence before it gets created? 
I'm asking as we already support writing hooks that are called after generation -> https://github.com/asyncapi/generator/blob/master/docs/authoring.md#hooks so such a hook that renames output could be provided in HTML and Markdown templates.

---

different approach: why not placing those html's just in subfolders like?
```
- index.html #here you have your custom index listing all the docs in navigation
- js
- css
- api1
  - index.html
- api2
  - index.html
- api3
  - index.html
```

**Comment by Cingulara** [comment]
I could rename files, or make directories for each name and then move index.html into that as well. And have a main "index.html" to point to them all. I can put that into an NGINX container or something similar and publish for a web-based catalog yes. I was trying to get away from doing all that and generate a single file to put somewhere. However, I can do what you said now same as renaming files. There are workarounds for sure. So definitely not critical. More of a 'nice to have if this can work' kind of thing. 

I will need to study the functionality of this generator more to see what hooks can be called and where. If this is mainly for the HTML and MD templates, that may make more sense so it is localized there.

**Comment by derberg** [comment]
@Cingulara I started working today on this issue https://github.com/asyncapi/generator/issues/318 to get a library of hooks that can be reused across templates. There could be a generic hook for renaming files basing on regex you pass with some parameter. Then it is just a matter of enabling it in a given template, and documenting

**Comment by Cingulara** [comment]
Roger that I will subscribe to that so I see updates and watch it. Thanks.

**Comment by derberg** [comment]
@Cingulara you might be interested with this -> https://github.com/asyncapi//markdown-template/#supported-parameters
Markdown template now supports param that you can use to change the name of output markdown file -> https://github.com/asyncapi/markdown-template/blob/master/hooks/output-filename.js

Same could be done in html-template for the `index.html` file

**Comment by derberg** [comment]
Markdown is supported, for HTML I added an issue here https://github.com/asyncapi/html-template/issues/73
this can be closed

**Comment by derberg** [comment]
@Cingulara in HTML it is also supported now https://github.com/asyncapi/html-template/releases/tag/v0.13.0
