### ISSUE TITLE
Add new flag to disable specific hook function

### ISSUE THREAD

**Issue by derberg** [asyncapi/generator#333]
#### Reason/Context
Once this is merged https://github.com/asyncapi/generator/issues/318 we have hooks types (`generate:after`) and hook names (`createAsyncAPIFile`).

You can now use flag `--disable-hook` to disable hook type, but there is no option to disable only a specific hook.

#### Description

- Introduce new flag/option where user of a particular template can disable only one specific hook
- Come up with suggestion on how info about hooks should be documented in the template, so folks know what hooks can be disabled without reading the code

**Comment by magicmatatjahu** [comment]
@derberg Could I take it? I have an idea to use `--disable-hook` flag for this and extend the flag's argument to something like

```bash
--disable-hook <hookType>#<hookName>
```

Then generator only skip hook with given name :)

I know that hookName is not required, so at the moment it should works only for common hooks like `createAsyncApiFile` from `@asyncapi/generator-hooks`.

I am not a expert in generator and its source code, so probably I don't see problems with this approach. What do you think?

> Come up with suggestion on how info about hooks should be documented in the template, so folks know what hooks can be disabled without reading the code

Simple list of used hooks with names, like:

|Type|Name|Desc|
|-|-|-|
|`generate:after`|`createAsyncApiFile`|`foobar`|

eventually in `desc` points to desc in another repo, if hook is not written in template itself.

Then user should known which hooks can disable.

**Comment by derberg** [comment]
> --disable-hook <hookType>#<hookName>

love it but as log as `--disable-hook <hookType>` will still work as before

> I know that hookName is not required, 

what do you mean?

> I am not a expert in generator and its source code, so probably I don't see problems with this approach. What do you think?

I don't remember implementation details but should be fine

---
table looks good, but `name` should be first imho. Even if hook comes from external lib, it should still be described in the repo where it is used imho

Aynway, take it man

**Comment by magicmatatjahu** [comment]
> love it but as log as --disable-hook <hookType> will still work as before 

Yes, If user put only `--disable-hook <hookType>` then whole hooks of given type will be skipped, but if put `--disable-hook <hookType>#<hookName>`, then only particular hook (with <hookName> name) of <hookType> will be disabled.

> >I know that hookName is not required,
>
> what do you mean?

I mean that <hookName> is not mandatory if you write your own hooks. Please see https://github.com/asyncapi/java-spring-template/blob/master/hooks/01_inverseOperations.js As you can see, the hook is `anonymous`, it doesn't exist :) Maybe I am wrong, and the file name is <hooName> 😄

**Comment by derberg** [comment]
ah, this is what you mean. Yes is it not mandatory. If template dev wants to make hook `disableable` 😄 he then need to add a name 😄 

the only problem I see with your suggestion for the flag is that you will not be able to disable multiple hooks

**Comment by magicmatatjahu** [comment]
So maybe change my idea to `--disable-hook <hookType>[Array<hookName>]`? 🤔

**Comment by derberg** [comment]
@magicmatatjahu maybe look at the library that we use do create CLI to see what options we have, not sure if what you propose is technically possible

**Comment by magicmatatjahu** [comment]
@derberg There can be used variadic options https://github.com/tj/commander.js/blob/master/docs/options-taking-varying-arguments.md like:

```text
ag --disable-hook generate:after createAsyncApiFile anotherHooName secondAnotherHookName -- <rest of options>
```

What do you think?

**Comment by derberg** [comment]
I think it is getting more complicated 🤷 

this `--` is strange, and also what if I want to disable one hook of one type and two hooks on another type, how would it look?

how about do it like with params:

```
--disable-hook generate:after=createAsyncApiFile

--disable-hook generate:after=createAsyncApiFile generate:before=anotherHooName

--disable-hook generate:after=createAsyncApiFile generate:before=anotherHooName,secondAnotherHookName
```

Something custom would be handling the comma separated values I guess

**Comment by magicmatatjahu** [comment]
@derberg When I started implement it, then I realized that variadic ptions will be hard to handle, so I followed in this same way as you proposed :D

**Comment by derberg** [comment]
@magicmatatjahu I will work on this part of the issue `Come up with suggestion on how info about hooks should be documented in the template, so folks know what hooks can be disabled without reading the code` in my task about template for templates, where I have to come up with a template for templates readme files
