### ISSUE TITLE
[Feature Request] Pluggable front-ends (e.g. JSON Schema)

### ISSUE THREAD

**Issue by MikeRalphson** [asyncapi/generator#35]
#### Why

This would allow generation of code (or documentation) based on input **other than** AsyncAPI *document instances*.

#### Example

If we had a JSON Schema front-end, we could (with suitable templates) automatically generate parsing code in multiple languages from the AsyncAPI *schema instance*.

Other code-generation templates could then depend on this lower-level parser, meaning it would be faster and more accurate to generate new parsing code whenever there was a schema change or correction.

This may be useful in order to support both AsyncAPI v1 and v2 anyway.

**Comment by derberg** [comment]
@MikeRalphson Hey man, can you please elaborate a little bit more about this one, I don't fully understand what needs to be done her

**Comment by derberg** [comment]
I'm closing this one as it doesn't look like something that is aligned with core generator functionality that is based on generating basing on info from AsyncAPI Document
