### ISSUE TITLE
conditionalFiles only works if you are lucky

### ISSUE THREAD

**Issue by Tenischev** [asyncapi/generator#358]
#### Describe the bug
1. Description of `conditionalFiles` in [docs](docs/authoring.md) is incomplete and example is actually pitfall.
2. If `subject` is not resolved in AsyncAPI, then file will be rendered because of [this condition](https://github.com/asyncapi/generator/blob/fc4dee9af622dfb198471a2cf0da53f5a3c7c7ae/lib/generator.js#L565)

#### How to Reproduce
Just try to use provided example

#### Expected behavior
1. Add note that path of file should be relative to `tempalte` folder
2. If `subject` is not found in AsyncAPI, then file is not rendered
3. Add note that `validation` is not any `JSON Schema Draft 07 object`, it must be from [`JSON Schema Validation`](https://tools.ietf.org/html/draft-handrews-json-schema-validation-01)
4. Provide a valid example:
Correct `subject` path in term of AsyncAPI spec to server protocols will be `servers.*.protocol`, but result of this (and any other) resolution will be an array, you should take it into account. Since it's not possible to predict how much servers will be in user AsyncAPI, usage of `const` is not possible as is. Perhaps, `contains` should be used always to check against result array. 
Here an example of `validation` that will correctly check for the `mqtt` protocol `{ "contains": { "type": "string", "const": "mqtt" }}`. 
Or another approach where filtering delegated to `subject`  - `"subject": "servers.*.{protocol: protocol} | [?protocol=='mqtt']", "validation": { "const": [ { "protocol": "mqtt" } ] }`

#### Hint
Perhaps we have a bug in [nodejs template](https://github.com/asyncapi/nodejs-template/blob/master/package.json) because it's exact copy of example from cuurent doc

**Comment by derberg** [comment]
One thing sure here is that current conditionalFiles in nodejs-template do not make sense as files listed there do not exist in the tempalate anyway https://github.com/asyncapi/nodejs-template/blob/master/package.json#L88

**Comment by derberg** [comment]
After some investigation:
- current configuration of `conditionalFiles` from nodejs-template can be removed https://github.com/asyncapi/nodejs-template/blob/master/package.json#L88 as files like `amqp.js` or `mqtt.js` do not exist in the template anymore
- I think the feature and the example work pretty well, just tested it in nodejs-template and it worked like a charm (my spec files has 3 servers). I added this:
```
"conditionalFiles": {
      "config/common.yml": {
        "subject": "server.protocol",
        "validation": {
          "const": "amqp"
        }
      }
    }
```
and if I generate service using my mqtt server, the file is not generated -> this is what I expected

I'm more concerned about:
- `nonRenderableFiles` are not supported by `conditionalFiles`, and I think they should
- I don't get what is the point of `nonRenderableFiles` as current use case in nodejs-template doesn't make sense to me https://github.com/asyncapi/nodejs-template/blob/master/package.json#L80 as if I remove those files from `nonRenderableFiles` then are generated just fine

**Comment by derberg** [comment]
@Tenischev `server.protocol` works because this is apparently not a documented feature :)
https://github.com/asyncapi/generator/blob/master/lib/generator.js#L561

**Comment by derberg** [comment]
@Tenischev I tried to replace your hook by configuration in java-template but you do not support `server` parameter there. If users have 2 servers, how do you guess which one they should use for generation?

**Comment by derberg** [comment]
here we could also have a nice warning for template developers https://github.com/asyncapi/generator/blob/master/lib/generator.js#L556 so they know they have wrong conditions, for files that do not exist. That would be a separate feature issue though

**Comment by derberg** [comment]
@Tenischev I created a PR for java, have a look and tell me what you think https://github.com/asyncapi/java-spring-template/pull/55/files

**Comment by derberg** [comment]
@Tenischev I created PR for docs in generator https://github.com/asyncapi/generator/pull/363

@fmvilas have a look on my comment
> nonRenderableFiles are not supported by conditionalFiles, and I think they should
If you agree I will extend this PR with proper fix

**Comment by fmvilas** [comment]
Yeah, I think it totally should 👍

**Comment by derberg** [comment]
@fmvilas PR ready for review

@Tenischev 
there are 2 PR related to this issue you might want to look at:
- https://github.com/asyncapi/generator/pull/363
- https://github.com/asyncapi/java-spring-template/pull/55

**Comment by Tenischev** [comment]
Hey @derberg ,
Now i see on asyncapi/java-spring-template#55 and want to say "Oh, this is what was mean [here](https://github.com/asyncapi/generator/blob/master/docs/authoring.md#special-parameters) in description"
We should expose description of server parameter to describe that you should name one of the servers listed in "servers" of your AsyncAPI
Nevertheless, parameter is very confusing for me, i should think

**Comment by derberg** [comment]
@Tenischev well, the current description of the `server` is accurate, it just doesn't say anything about conditionalFiles. 

I've extended my PR with more explanation, examples and links. What do you think?
