### ISSUE TITLE
[FEATURE REQUEST] Customize the Generated Payload

### ISSUE THREAD

**Issue by jmalcaraz** [asyncapi/generator#38]
**Is your feature request related to a problem?  No

**Can't it be tackled using specification extensions?**
No

**Describe the solution you'd like**
To allow a "example:" tag inside of the definition of the properties. The value associated to the "example" tag is the one that will be rendered in the "automatically generated  payload" for those properties that do not have a "default" value. Notice that you can decide that there is no default value for a schema but however, you want to provide a complete example of such schema to the reader of the documentation. This is where the "example" (or any other better name) could help.

**Describe alternatives you've considered**
Read documentation and no alternatives foreseen. 

**Additional context**
N/A

**Comment by fmvilas** [comment]
Hi @jmalcaraz. I transferred this issue to the generator package since it's a tooling feature request. The spec already allows you to add examples on every field. If I recall correctly, the Markdown template already has this feature. Do you need it in the HTML documentation?

**Comment by jmalcaraz** [comment]
Thanks for the quick anwser. Apologize I have found the functionality right now. I has been a mistake form my side. "example:" is already supported. Thanks a lot! Great work you are doing!

**Comment by fmvilas** [comment]
Thank you! You may want to join the Slack channel for quick questions and answers: https://join.slack.com/t/asyncapi/shared_invite/enQtNDY3MzI0NjU5OTQyLWU4ZGU2MTg1MDIyZDFjMTI2YjkxYTdlMzc1NjgzYTAxZDM1YTg1NDhhMTE2NDliMjlhZjYxNzk0ZTE5ZGU1ZTg.
