### ISSUE TITLE
The API document for the generator does not clarify access to the parsed AsyncAPIDocument

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#387]
#### Reason/Context
With the current [API ](https://github.com/asyncapi/generator/blob/master/docs/api.md#generator)document for the generator it does not state you have access to the parsed AsyncAPIDocument on `asyncapi` and the AsyncAPI file on `originalAsyncAPI`.

#### Description
We need to add jsdoc to the following lines:
https://github.com/asyncapi/generator/blob/4c8dd9de88c701ccf1afaeb28cf6aaba7e8b7e2c/lib/generator.js#L237-L239

**Comment by McZenith** [comment]
Hi! I'm interested with a little mentoring I can pull this.

**Comment by jonaslagoni** [comment]
Hey @McZenith awesome! You can draw inspiration by this:
https://github.com/asyncapi/generator/blob/4c8dd9de88c701ccf1afaeb28cf6aaba7e8b7e2c/lib/generator.js#L114 
To see if it generates the correct API document run the command `npm run docs` 😄

**Comment by McZenith** [comment]
Thanks will do.

**Comment by bszwarc** [comment]
I can help with this one, if it's still available :)
