### ISSUE TITLE
Error while npm install

### ISSUE THREAD

**Issue by aravindajju** [asyncapi/generator#389]
I am trying to npm install asyncapi generator.  But it fails to install.  

#### How to Reproduce
I am on Windows and I am using node v10.16.3 and npm 6.9.0

PS D:\Work Related\eventus> npm i @asyncapi/generator
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/fmvilas/json-schema-ref-parser.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by jonaslagoni** [comment]
With npm version `6.14.5` and node version `v13.9.0` I am not able to reproduce this error. 

Since the generator demands the following engines to run:
```
    "node": ">=12.16",
    "npm": ">=6.13.7"
```

You might have to update both npm and node regardless, and that might solve this install problem as well 🤔

**Comment by aravindajju** [comment]
I overlooked the requirements.  I will update the versions and check.

**Comment by aravindajju** [comment]
Updated node and npm to v12.18.3 and v6.14.7 respectively.  But no luck.  I have looked through the debug log.  It is failing here

83 silly fetchPackageMetaData error for @apidevtools/json-schema-ref-parser@github:fmvilas/json-schema-ref-parser#add-more-info-about-errors Error while executing:

I have attached the npm debug log for reference as well.

PS D:\Work Related\eventus> npm install -g @asyncapi/generator
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/fmvilas/json-schema-ref-parser.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2020-07-23T10_34_56_689Z-debug.log

[2020-07-23T10_34_56_689Z-debug.log](https://github.com/asyncapi/generator/files/4965367/2020-07-23T10_34_56_689Z-debug.log)

**Comment by jonaslagoni** [comment]
Hmm. So after looking at the dependency that can't be fetched it is `"@apidevtools/json-schema-ref-parser": "github:fmvilas/json-schema-ref-parser#add-more-info-about-errors",` and it seems like the `github:` part attempts to install it with `git` as stated in the [npm documentation](https://docs.npmjs.com/cli/install):

> npm install github:githubname/githubrepo[#commit-ish]:
> 
> Install the package at https://github.com/githubname/githubrepo by attempting to clone it using git.

And based on how the documentation for how [package.json github dependency](https://docs.npmjs.com/files/package.json#github-urls) should be defined it doesn't match how it is defined in the parser 🤔 

@aravindajju do you have git installed?

**Comment by jonaslagoni** [comment]
Ahh. I can see that even in our `dockerfile` it states that 

> Since 0.30.0 release Git is supported and required as a dependency

Guess someone forgot to update our readme 😄

**Comment by aravindajju** [comment]
Thank you @jonaslagoni  for this input.  I have git installed, but I've realized it is not in the path for my dev setup.  Once I added, I am able to install it now.

**Comment by derberg** [comment]
I think our priority should be to not use fork here https://github.com/asyncapi/parser-js/blob/master/package.json#L52 but rather switch to the upstream project. 

if above takes to much time, we should just modify `package.json` to point to tarball like https://github.com/fmvilas/json-schema-ref-parser/tarball/add-more-info-about-errors so npm doesn't require `git`. Much better than adding `git` to the list of requirements. So we have no `git` requirement in the parser, and in the generator, we need it as some functionality needs it (the one that validates if given directory is a git repo with unstaged changes)

**Comment by derberg** [comment]
Now, with latest release candidate 8 we are using `@apidevtools/json-schema-ref-parser` from the upstream and not the fork. Issue solved
