### ISSUE TITLE
Improve docker image to contain npm global installation only instead of generator sources

### ISSUE THREAD

**Issue by derberg** [asyncapi/generator#399]
#### Reason/Context
At the moment we provide official docker image that contains generator sources https://github.com/asyncapi/generator/blob/master/Dockerfile#L18-L20
So in the docker image, we do not enable users to use official release but sources of the release. The official release is what goes to npm and this is what Docker should use. This means we should do something like this in the docker image https://github.com/Mermade/oas-kit/blob/master/packages/swagger2openapi/Dockerfile#L8

Another reason to do it is to make sure users never get this issue https://github.com/asyncapi/generator/issues/388#issuecomment-675360044

#### Description
- improve Dockerfile
- make sure docs instructions are still ok

**Comment by derberg** [comment]
Video explanation https://youtu.be/Iqs_2BiNEEo?t=224

**Comment by mowies** [comment]
I would like to work on this issue please :)

**Comment by derberg** [comment]
@mowies please do. I'll jump into review once you undraft it

**Comment by mowies** [comment]
The PR should be ready now
