### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by m-mohr** [asyncapi/generator#40]
I can't install this software on Windows though it doesn't state this in the README. It only says it requires node, nothing about a specific OS.

NPM response:
```
c:\Dev\openeo-api>npm install -g ag
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for ag@0.9.0: wanted {"os":"darwin,linux,!win32","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin,linux,!win32
npm ERR! notsup Valid Arch:  x64
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

Would be great to get Windows support back!

**Comment by m-mohr** [comment]
Sorry, obviously my fault.

**Comment by fmvilas** [comment]
No probs. It took me some time to realize about the mistake too 😄

**Comment by shpelda** [comment]
> Sorry, obviously my fault.

Well, what was the issue there ?

**Comment by jonaslagoni** [comment]
> > Sorry, obviously my fault.
> 
> Well, what was the issue there ?

Wrong installation command, use `npm install -g @asyncapi/generator`.
