### ISSUE TITLE
Support for empty payload

### ISSUE THREAD

**Issue by rv0** [asyncapi/generator#400]
#### Description

"payload" is not mandatory, therefore it can be empty or just left out completely.
However when you do this, the rendering will fail with an unclear error (at least with html-template)

#### How to Reproduce
Remove payload from a message in the streetlights example.

#### Expected behavior
Render empty payload.

**Comment by jonaslagoni** [comment]
@rv0 can you provide the error? This sounds like an issue in the template and not the generator.

**Comment by derberg** [comment]
@jonaslagoni yeap, this is a template related, moving to `html-template` as I know the issue was noticed in the playground

**Comment by derberg** [comment]
Issue moved to [asyncapi/html-template #55](https://github.com/asyncapi/html-template/issues/55) via [**ZenHub**](https://www.zenhub.com/)
