### ISSUE TITLE
Not possible to pass on a local template with latest 1.0.0-rc.9

### ISSUE THREAD

**Issue by rv0** [asyncapi/generator#401]
#### Describe the bug
Using asyncapi version 1.0.0-rc8 I could render the docs with a local template.
With  1.0.0-rc9 it will just default to the html template somehow (probably because it looks inside the package.json of the local template?).
If this is intended behavior, please document how to pass on a custom template with rc9.

#### How to Reproduce

`ag -o html asyncapi.json ../html-template`

Where asyncapi.json is any asyncapi source file and where html template is a modified version of the standard html template.
The result will be a rendered html with the unmodified template

#### Expected behavior

I expect the generator to just use the provided template

**Comment by derberg** [comment]
Are you sure it is caused by the version of the generator? when you install the older one again all works fine?
The generator looks into local template and if you made some changes you need to ask the CLI for another installation with `--install`. Please try again and let me know how that helped

**Comment by rv0** [comment]
Yes, I was running rc.9 and it was rendering "normal" (non-modified version)
Than I installed rc.8 and it was rendering the custom template (modified version)

Just updated back to rc.9 and it works as expected now.. The --install may have been the problem then?

But it's weird, as the html-template folder was something I had never used on this computer before.

**Comment by derberg** [comment]
These things may happen and this is why we have `--install` flag. It happens when you use both, local HTML template and the one from npm as at the end they are both with the same name, `@asyncapi/html-template`

**Comment by derberg** [comment]
for sure not related to release candidates as we did not introduce any direct changes to the generator, but just to the parser and increated the parser version in the generator, thus another generator release

**Comment by rv0** [comment]
Makes sense, thanks for clarifying
