### ISSUE TITLE
readme file referring to non-existing document

### ISSUE THREAD

**Issue by apaezg** [asyncapi/generator#406]
#### Describe the bug
README.md in the section "CLI usage with Docker" still refers to streetlights.yml that seem was deleted on tests/docs.

#### How to Reproduce
- clone repository
- follow guide to execute
`docker run --rm -it \
-v ${PWD}/test/docs/streetlights.yml:/app/asyncapi.yml \
-v ${PWD}/output:/app/output \
asyncapi/generator -o ./output asyncapi.yml @asyncapi/html-template --force-write`

https://github.com/asyncapi/generator/blob/master/README.md#cli-usage-with-docker

#### Expected behavior
Update reference to document dummy.yml for example

**Comment by derberg** [comment]
@apaezg Thanks a lot Antonio. Would you like to open a PR for that? it just needs to be changed to point to the `dummy` file instead of `streetlights`

**Comment by apaezg** [comment]
> @apaezg Thanks a lot Antonio. Would you like to open a PR for that? it just needs to be changed to point to the `dummy` file instead of `streetlights`

Hi @derberg, I think I have just opened the PR properly. It is my very first time contributing to an open source project, so, if there's anything wrong, sorry in advance, and let me know to fix it.

**Comment by derberg** [comment]
@apaezg first and perfect!!! thanks so much mate!
