### ISSUE TITLE
watch-template is watching output folder

### ISSUE THREAD

**Issue by GordeevArt** [asyncapi/generator#409]
#### Describe the bug
Discussed here https://github.com/asyncapi/html-template/issues/61 - I remove unused files by hook and it coping files infinitely.

#### How to Reproduce
In https://github.com/asyncapi/html-template do
`ag test/spec/asyncapi.yml ./ -o test/output --force-write --watch-template -p singleFile=true`
than change some files.

![image](https://user-images.githubusercontent.com/2003488/92919603-72873c00-f439-11ea-9de5-44b281b1fb5d.png)

#### Expected behavior
Not to generate files when output folder changes.

**Comment by jonaslagoni** [comment]
https://github.com/asyncapi/generator/pull/337 should have fixed this issue 🤔 @GordeevArt what generator version are you using? 
@derberg any thoughts on the issue?

**Comment by GordeevArt** [comment]
@jonaslagoni I use latest @asyncapi/generator@1.0.0-rc.10 version

**Comment by derberg** [comment]
@jonaslagoni I forgot I fixed it some time ago 😆 I just checked quickly on local and for me my fix still works 😄 

@GordeevArt are you a windows user? or?

**Comment by GordeevArt** [comment]
@derberg Fedora Linux 5.7.15-100.fc31.x86_64

Try to change something in output folder (index.html).

it matters just for developing with parameter **singleFile=true**.

**Comment by derberg** [comment]
@GordeevArt I tried to do changes manually in output, also added a hook that you added without any parameters so it always runs, and no effect

I recorded this to show how I do it
![](http://g.recordit.co/cu1qQzHFtH.gif)

**Comment by GordeevArt** [comment]
@derberg ok, thanks for research. I do the same but have the bug. It is no critical.

**Comment by derberg** [comment]
@GordeevArt [this](https://github.com/paulmillr/chokidar/tree/master) is what we are using under the hood to watch for changes. Would be great if you could try out [their CLI](https://github.com/kimmobrunfeldt/chokidar-cli) with `--ignore` flag, to see if this issue is caused by the `chokidar` library or we just do something wrong in the Generator

**Comment by GordeevArt** [comment]
@derberg this still don't work for me

**Comment by derberg** [comment]
@GordeevArt you mean you tried https://github.com/kimmobrunfeldt/chokidar-cli indepedently from the generator and it was also detecting changes in ignored paths?

**Comment by derberg** [comment]
@GordeevArt hey man, is it still valid?

**Comment by GordeevArt** [comment]
Yes, but I don't use it now.

**Comment by derberg** [comment]
if somebody experience similar issue, please instead use https://github.com/asyncapi/cli and any CLI issues report there 🙏🏼
