### ISSUE TITLE
NodeJs templates

### ISSUE THREAD

**Issue by RobertDiebels** [asyncapi/generator#41]
On the documentation page for AsyncAPI https://github.com/asyncapi/node-codegen is listed as deprecated in favor of asyncapi-generator.

However, there are no nodejs templates in the generator. Is it possible to port them? 
Since node-codegen is no longer functional ( current version breaks during the tutorial).

**Comment by rmelian** [comment]
Hi @RobertDiebels, I'm working right now fixing the existing node-codegen and soon to start working on porting it too. I'll let you know when is fixed and thank you for taking the time to report this issue.

**Comment by rmelian** [comment]
Hi @RobertDiebels I just published a new version with a fix, can you please try node-codegen generator and let us know if that worked.

NOTE: you need to update your local generator

**Comment by RobertDiebels** [comment]
@rmelian The async-api-codegen hasn't been updated on NPM yet. Do I need to clone and npm link it locally?

**Comment by RobertDiebels** [comment]
@rmelian Looks like it's working 👍

**Comment by RobertDiebels** [comment]
@rmelian Is it also possible to generate a client with node-codegen?

**Comment by rmelian** [comment]
Hi @RobertDiebels for the moment you can use this generator https://github.com/asyncapi/node-codegen

**Comment by fmvilas** [comment]
Fixed on #86
