### ISSUE TITLE
Add type and possibleValues properties to template configuration

### ISSUE THREAD

**Issue by derberg** [asyncapi/generator#414]
#### Reason/Context

I have a template where user can pass `-p png=true` to get additional png of the diagram. I showed example through CLI where everything is a String. Now, in configuration we do not specify type of the value that has to be provided in the parameter. I can do it in readme but yeah, manual and depends on my. Now, I wanted to use my template in Generator as library and I immediately did:
```
const generator = new Generator(path.resolve(__dirname, '../../'), outputDir, { 
    forceWrite: true,
    templateParams: {
      png: true
    }
  });```
```
So I passed Boolean, as this was natural for me.

#### Description
We should introduce new properties to Generator configuration in `parameters` section:
- `type` to clearly specify what data type is of a given parameter so we can also validate if good data is passed, and what to do with it when it comes from CLI
- `enum` or `possibleValues` where we can specify what values are expected on a given parameter.

Thanks to above we not only can nicely validate the input but also have a tool that generates parameters documentaiton in the template readme

**Comment by derberg** [comment]
wouldn't instead of those 2 fields be better to specify just a schema with JSON Schema format 🤔

**Comment by magicmatatjahu** [comment]
Maybe we should switch to JSON Schema for validation? 🤔

**Comment by derberg** [comment]
yup https://github.com/asyncapi/generator/issues/414#issuecomment-693354477 might be the case here

**Comment by magicmatatjahu** [comment]
Ahh sorry 😅 I didn't see it.

**Comment by derberg** [comment]
still good to have
