### ISSUE TITLE
Java-spring templates have undefined members

### ISSUE THREAD

**Issue by RobertDiebels** [asyncapi/generator#42]
Both the MqttConfig and AmqpConfig partial template files will currently result in a compiler error when a spec contains a `topic` object with a  `publish` property.

In the MqttConfig template the [setDefaultTopic function](https://github.com/asyncapi/generator/blob/cbdae35abc594bf8bef7bb92fb3045b465b5592e/templates/java-spring/.partials/MqttConfig.java#L100) will be called with an undefined variable. Since the template only creates the corresponding private members if the topic is of type [subscribe](https://github.com/asyncapi/generator/blob/master/templates/java-spring/.partials/MqttConfig.java#L39).

The same applies to the AmqpConfig template file where the [setExchangeName function](https://github.com/asyncapi/generator/blob/cbdae35abc594bf8bef7bb92fb3045b465b5592e/templates/java-spring/.partials/AmqpConfig.java#L122) will be called with an undefined variable.  Since the template only creates the corresponding private members if the topic is of type [subscribe](https://github.com/asyncapi/generator/blob/cbdae35abc594bf8bef7bb92fb3045b465b5592e/templates/java-spring/.partials/AmqpConfig.java#L37).

**Comment by rmelian** [comment]
Hi @RobertDiebels thank you for reporting this, I'll take a look ASAP

**Comment by RobertDiebels** [comment]
@rmelian Happy to help. I can confirm that the expected output is generated if the handle-bars if-statement for the private members in MqttConfig is removed. As for the AqmpConfig partial, changing the if-statment condition to check for `publish` rather than `subscribe` for the Exchange private members should fix the issue.

**Comment by rmelian** [comment]
do you want to submit a PR?

**Comment by RobertDiebels** [comment]
@rmelian I'll submit a PR in an hour or 2-3 if that's ok.

**Comment by RobertDiebels** [comment]
Done.

**Comment by rmelian** [comment]
hi @RobertDiebels can you share the asyncapi definition you are using

**Comment by rmelian** [comment]
I just approved your PR @RobertDiebels great work
