### ISSUE TITLE
Mixed type array support

### ISSUE THREAD

**Issue by jonathanhuet** [asyncapi/generator#427]
#### Describe the bug
If a mixed type array is declared, this is not correctly rendered in the HTML view it is rendered as _Array < Unknown >_

#### How to Reproduce
To reproduce it: 

1) copy and paste the following spec in the generator

```yaml
asyncapi: 2.0.0
info:
  title: Test MQTT API
  version: '1.0.0'
  description: |
    Test


defaultContentType: application/json

channels:  
  foo/bar:
    description: Test MQTT operation
    publish:

      message:
        $ref: '#/components/messages/testMessage'
components:
  messages:
    testMessage:
      contentType: application/json
      payload:
        $ref: "#/components/schemas/mainSchema"
  schemas:
 
    oneOfSchema:
      type: object
      properties:
        foo:
          type: number
          format: float	
    oneOfSchema2:
      type: object
      properties:
        foo:
          type: number
          format: float	    

             
    mainSchema:
      type: object
      properties:
        mixedTypeArray:
          type: array
          items:
            oneOf:
            - $ref: "#/components/schemas/oneOfSchema"
            - $ref: "#/components/schemas/oneOfSchema2"
```

2) In the generated HTML code, see that the _Array < Unknown >_ is shown for the property `mixedTypeArray` and no types shown in the definition of the array in the drop down of the array
#### Expected behavior
The drop down of the array `mixedTypeArray` should show the list of possible items of the array [ `oneOfSchema` , `oneOfSchema2` ]

**Comment by derberg** [comment]
@jonathanhuet this issue was reported a few days [here](https://github.com/asyncapi/playground/issues/36).

PR with the fix is already opened https://github.com/asyncapi/html-template/pull/97

When I check my fix with your example, this is what I get
<img width="958" alt="Screenshot 2020-10-14 at 10 05 37" src="https://user-images.githubusercontent.com/6995927/95961215-08c9cb80-0e05-11eb-8358-23855d8f9f10.png">

So I guess this is also a fix for you. I'll wait for feedback from @CumminsMikeMattern one day more and if I get no response I'll look for a reviewer and merge/release, so this week it should go out

**Comment by jonathanhuet** [comment]
@derberg thanks for the fast reply!

Totally true about the issue #36. My bad!

About your PR result, it's totally ok for me. Thanks.


Just as a side note that probably is most a feature: As I'm familiar from Swagger/OAS, I'm missing the type name of the (referenced) object in the dropdown, as it is can be seen in OAS generator

**Comment by derberg** [comment]
@jonathanhuet no worries.

you mean that instead of `0` and `1` you would prefer `oneOfSchema` and `oneOfSchema2`?

**Comment by jonathanhuet** [comment]
yes, I think it is might be useful. OAS 3 HTML generator has it for each reference. In terms of coding I think it is useful to identify each parts and then having a specific handler/parser for that specific part of the message

**Comment by CumminsMikeMattern** [comment]
I agree with @jonathanhuet

**Comment by derberg** [comment]
@jonathanhuet @CumminsMikeMattern I'll see what I can do. We already did it a few days ago in our react component https://github.com/asyncapi/asyncapi-react/pull/156 so this is definitely something that should be done here in the HTML template

**Comment by derberg** [comment]
Ok, I pushed fix that I think you are looking for

with such schema:
```
asyncapi: 2.0.0
info:
  title: Test MQTT API
  version: '1.0.0'
  description: |
    Test


defaultContentType: application/json

channels:  
  foo/bar:
    description: Test MQTT operation
    publish:

      message:
        $ref: '#/components/messages/testMessage'
components:
  messages:
    testMessage:
      contentType: application/json
      payload:
        $ref: "#/components/schemas/mainSchema"
  schemas:
 
    oneOfSchema:
      type: object
      properties:
        foo:
          type: number
          format: float	
    oneOfSchema2:
      type: object
      properties:
        foo:
          type: number
          format: float	    

             
    mainSchema:
      type: object
      properties:
        mixedTypeArray:
          type: array
          items:
            oneOf:
            - $ref: "#/components/schemas/oneOfSchema"
            - $ref: "#/components/schemas/oneOfSchema2"
            - type: object
              properties:
                foo:
                  type: number
                  format: float	  
```

you get this 

<img width="942" alt="Screenshot 2020-10-15 at 17 10 43" src="https://user-images.githubusercontent.com/6995927/96149435-9db5ed00-0f09-11eb-8f74-4ca0030d7bb6.png">

**Comment by derberg** [comment]
what do you think?

**Comment by CumminsMikeMattern** [comment]
> what do you think?

Looks great !

**Comment by derberg** [comment]
fixed with https://github.com/asyncapi/html-template/pull/97

**Comment by jonathanhuet** [comment]
Yes, that's great!It will be very helpful! Thanks 👍

**Comment by derberg** [comment]
@jonathanhuet it is already released 😉 https://github.com/asyncapi/html-template/releases/tag/v0.15.0

**Comment by jonathanhuet** [comment]
@derberg Thanks! And also uploaded to https://playground.asyncapi.io/ , perfect!
