### ISSUE TITLE
Java-spring partial template AmqpConfig wrongly adds a comma

### ISSUE THREAD

**Issue by RobertDiebels** [asyncapi/generator#43]
The java-spring template partial AmqpConfig adds a comma when it is not the [last topic](https://github.com/asyncapi/generator/blob/cbdae35abc594bf8bef7bb92fb3045b465b5592e/templates/java-spring/.partials/AmqpConfig.java#L70). 

When a situation occurs when the last topic is a subscribe topic the comma will be added to the generated source. This will cause a compile error.

Afaik handlebars can only solve this with a custom helper. Or by splitting the subscribe and publish topics into two different lists.

**Comment by rmelian** [comment]
Hi @RobertDiebels good catch too, do you want to send another PR :)

**Comment by fmvilas** [comment]
In case it helps: you might need to use `#unless @../last` instead of `#unless @last`.

**Comment by RobertDiebels** [comment]
@rmelian I'll see if I can create a PR within an hour or 8-9.
@fmvilas Thanks! I'll check it out.

**Comment by RobertDiebels** [comment]
@rmelian @fmvilas I created a PR that should fix this. I looked into the `@../last` but I got the impression @../last goes to the parent object and tries to get the last item from the parent. Where the parent would be the asyncapi itself. I prefer this fix however, since it removes the need for a bunch of if-statements in the Config partials. Let me know what you think.

**Comment by rmelian** [comment]
Hi @RobertDiebels I'm sorry it took me so long to review this. This looks fantastic, I have just a few comments.

**Comment by rmelian** [comment]
actually, my only comment was to change x-service-name to operationId as this will be officially supported in version 2.0.0 of the specification but I guess it was my who implemented it this way :)

great work on this, I'm approving this PR
