### ISSUE TITLE
Support TS in hooks and filters

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/generator#455]
#### Reason/Context

At the moment `generator` doesn't support TS in hooks and filters. Problematic is that if someone wants to use TS in template he/she can't, because mentioned hooks and filters won't work due to handle them by generator itself, so generator should handle transpilation to JS before rendering process.

#### Description

I don't think it will be a breaking change. We should do something like that https://github.com/kyma-project/website/blob/master/gatsby/index.js#L3 so before saving filters to nunjucks we should transpile TS code to JS code. This same for hooks.

**Comment by fmvilas** [comment]
> Problematic is that if someone wants to use TS in template he/she can't...

I'm curious how many times this has been a problem 😄
