### ISSUE TITLE
Simplify code related to render engine

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/generator#464]
#### Reason/Context

Working on https://github.com/asyncapi/generator/pull/453 with @jonaslagoni we concluded that code related to render engine - like choose of it and do additional operations like register the filters for Nunjucks - is not a easy to read and maintaince.

There are no breaking changes, the issue is only related to the standardization of the code through (for example) a `switch case` statements and adding tests to the existing, untested logic.

**Comment by magicmatatjahu** [comment]
We should also take care about issue with `nonRenderableFiles` in React case. Whole problem is described in this thread https://github.com/asyncapi/template-for-generator-templates/pull/6#pullrequestreview-554733655 TL;DR; We should copy non-JS files, not skip them.

**Comment by magicmatatjahu** [comment]
@jonaslagoni  I have an idea with `AbstractRenderer` as class and then separate implementations for React and Nunjucks. By this solution we can remove `if-logic` like `if isReactRenderer(...) then ...`.

```js
class AbstractRenderer {
  configure();
  render();
  save();
  ...
}

```

What do you think?

**Comment by jonaslagoni** [comment]
That sounds like a good idea!
