### ISSUE TITLE
'ag' name conflicts with well know search utility 'Silver Searcher'

### ISSUE THREAD

**Issue by strobe** [asyncapi/generator#467]
#### Describe the bug
```
 ~> npm install -g @asyncapi/generator
npm WARN deprecated fsevents@2.1.3: Please update to v 2.2.x
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
/usr/local/bin/asyncapi-generator -> /usr/local/lib/node_modules/@asyncapi/generator/cli.js
npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/@asyncapi/generator/cli.js
npm ERR! dest /usr/local/bin/ag
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/@asyncapi/generator/cli.js' -> '/usr/local/bin/ag'
npm ERR! File exists: /usr/local/bin/ag
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

```

#### How to Reproduce
on macos do
```
brew install ag
npm install -g @asyncapi/generator
```
and as result you get 
```
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/@asyncapi/generator/cli.js' -> '/usr/local/bin/ag```

**Comment by derberg** [comment]
@strobe I don't see any option other than use generator with `npx` instead, at least at the moment. We plan to work this year on generic CLI for asyncapi that does `asyncapi validate` or `asyncapi generate` or `asyncapi add` so this will be the time we will work on a different name of the cli.

do you see any other solution?

**Comment by strobe** [comment]
the main problem with this issue that a lot of tools (like emacs stuff) relayed on 'ag' command and will use a generator instead so a possible solution could be to come up with some more specific name/symlink like 'asgen', 'async-gen', 'asyng'.

> do you see any other solution?
I believe at least for macOS is possible to add a flag to 'brew' installation to don't make a symlink

**Comment by derberg** [comment]
at the moment we already support 2 different names, so instead of `ag` you can use `asyncapi-generator`
https://github.com/asyncapi/generator/blob/master/package.json#L7-L8

I have to shamefully admit I have no idea how this information can help you 😅 but maybe some workaround would work with it for now?

**Comment by strobe** [comment]
> workaround would work with it for now?

my workaround is very simple - I removed 'ag' and switched my configs to use different searcher app the 'ripgrep (rg)'
(but probably that doesn't acceptable for everyone)

More general workounds as you mention usage via 'npx' (but I not tested that it works with preinstalled 'ag' in system) or via 'docker'.

**Comment by derberg** [comment]
`npx` is separate, it is like installing `ag` on-demand only for the moment you need to run `npx`, not global install.

**Comment by derberg** [comment]
I'm gonna close this one, we will not introduce any name changes to the current CLI as we already started working on a new one -> https://github.com/asyncapi/cli/issues/1 and it will not be `ag` but `asyncapi`, which will solve this problem once we release and deprecate `ag`
