### ISSUE TITLE
"Topics" block remains displayed even when not used

### ISSUE THREAD

**Issue by ppseprus** [asyncapi/generator#49]
Based on the AsyncAPI specs, the _topics_ property is optional as long as _stream_ or _events_ is used instead.

**YAML to Reproduce**
```yaml
asyncapi: "1.2.0"
info:
  title: AsyncAPI Sample
  version: 1.0.0

servers:
  - url: domain:1234
    scheme: ws

events:
  send:
    - $ref: '#/components/messages/sendMessage'
  receive:
    - $ref: '#/components/messages/receiveMessage'

components:
  messages:

    sendMessage:
      payload:
        type: object
        properties:
          abcd:
            type: string

    receiveMessage:
      payload:
        type: object
        properties:
          efgh:
            type: string
```

**Current Behaviour:**
The "Topics" is displayed, even though, it is not used.
![image](https://user-images.githubusercontent.com/1323285/54818476-a85ec080-4c99-11e9-89e4-b68a37d54c93.png)

**Expected Behaviour:**
The "Topics" block is not rendered.

**Comment by fmvilas** [comment]
Just transferred the issue. Will review permissions one of these days to make sure you can move with freedom 😄
