### ISSUE TITLE
map schema base url to local folder

### ISSUE THREAD

**Issue by muenchhausen** [asyncapi/generator#512]
#### Reason/Context

1. The resolution of schema references with relative pathes e.g. `../mypath` depend on the implementing library and may not work. Absolue URIs solve the problem.
2. During unit testing, you often need to use local JSON Schema files instead of downloading the schema from a Web-Server.
3. In cases where a schema URI is an [identifier](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.8.2.2) but not necessarily a network locator, it is required to do a mapping to local files. 

For example, I would love to map `https://example.com/` to a local base folder, so the schema file `common/shared.json` can be resolved locally:
```
{
  "$id": "https://example.com/foo/bar.json",
  "items": {
    "$ref": "https://example.com/common/shared.json"
  }
}
```

#### Description

Allow to map from a schema base URI to a local folder with an additional CLI parameter:

```
--map-base-url <url>:<localBaseFolder>
```

**Comment by derberg** [comment]
@muenchhausen hey, interesting use case. In general, I have nothing against the idea. I'm more concerned about the flags you suggested. They depend on each other, therefore I'm not in favor to keep them separate. When you write map, I immediately think about Docker CLI and how the mapping of directories works there.

I also have a question about the PR, you set there an option of the Parser called `idresolver`. Where did you get it from? we resolve refs using an external package in the JS parser and I don't see an option like this there https://apitools.dev/json-schema-ref-parser/docs/options.html#resolve-options

**Comment by muenchhausen** [comment]
I implemented your suggestions - see https://github.com/asyncapi/generator/pull/529
