### ISSUE TITLE
React templates make generation process longer

### ISSUE THREAD

**Issue by derberg** [asyncapi/generator#521]
#### Describe the bug

```
    ✓ generated using Nunjucks template (492ms) #html-template
    ✓ generate using React template (4875ms) #markdown-template
```

Markdown template is the simples one we have, yet it takes 5s to generate `asyncapi.md` with it. Which is really a lot and I bet it will be worse with more complicated templates.

#### How to Reproduce

Just try to generate with HTML template and then markdown one and you'll see that there is a time difference each time.

The problem is in transpilation process with babel. @magicmatatjahu checked and:

```
5 times in a row with transpilation in each render:
3.768s
2.391s
2.236s
2.260s
2.414s
Average: ~2.6s
And here is a time without transpilation in each render:
191.515ms
194.49ms
185.167ms
192.192ms
199.48ms
Average: ~0.193s
```

#### Expected behaviour

IMHO by default, when you run generation, an already transpiled template is used to speed up (yes, it means we publish transpiled files to npm too). The generator is smart and spots transpiled files are missing and it needs to run transpilation. Users (template developers) also have a flag that allows them to explicitly run transpilation during development

**Comment by derberg** [comment]
@magicmatatjahu good point, done

**Comment by magicmatatjahu** [comment]
@derberg To compile the React template and use that "compiled" templated from each run. At the moment we transpile/compile React component by babel on each generation and it is a waste of time.

**Comment by derberg** [comment]
@magicmatatjahu thanks, now I remember. I just think now that it should work like this by default. When you run generation, generator first look for sources of compiled template, if provided, and if not, performs old way. And yeah still in template for templates we need to show how to get it into npm

**Comment by magicmatatjahu** [comment]
> I just think now that it should work like this by default. When you run generation, generator first look for sources of compiled template, if provided, and if not, performs old way

Exactly in this way, look for transpiled files, if don't exist then run transpilation/compilation and generate template.

**Comment by jonaslagoni** [comment]
@magicmatatjahu would you be able to formulate this into a good first issue? 🙂

**Comment by derberg** [comment]
@magicmatatjahu I second what @jonaslagoni wrote because of this thread https://asyncapi.slack.com/archives/CQVJXFNQL/p1648304288930959

we are getting more and more React-based templates, means more unhappy users. 


btw, I was wondering if we could not make it

**Comment by derberg** [comment]
Reopening. Now with budget in bounty program maybe we can find someone who could work on improving things

**Comment by derberg** [comment]
What needs to be done:

1. In Generator we need to:
  -  enable skipping default transpilation. In other words, we should actually make transpilation not be triggered. Related code https://github.com/asyncapi/generator/blob/master/lib/renderer/react.js#L19
  - to enable recompilation, we should enable option `compile` (to be added in https://github.com/asyncapi/generator/blob/master/lib/generator.js) that by default is set to `false`. When set to `true`, transpilation runs again

First bullet point might be considered a breaking change, which is not a problem as we can release it as breaking together with https://github.com/asyncapi/generator/pull/925 and also to use this feature, template developers will anyway have to make changes in their projects to enable release of transpiled files - so they can also change template settings so new version of their template supports latest generator

2. In CLI new flag will need to be enabled

3. In `html-template` we need an example flow on how to enable this new feature to speed up development but also DX in case of generation of output

4. Educate template developers: have a document that describes how stuff work and make sure in all templates under AsyncAPI org there are issues to set things up

1-3 can be pushed through bounty program
2-4 can be pushed as good first issues as after 1 and 3, 2 and 4 will be trivial


@jonaslagoni @magicmatatjahu sounds like a plan? also we could use this as onboarding of potential new maintainer in generator

**Comment by jonaslagoni** [comment]
@derberg makes sense to me 👌

**Comment by smoya** [comment]
A non-asked opinion here (not owner): I like the suggested solution 👍

**Comment by utnim2** [comment]
Hey @derberg as (asyncapi/html-template#558)[https://github.com/asyncapi/html-template/issues/558] is near to completion can i open number 3 issue in the CLI

**Comment by derberg** [comment]
> is near to completion can i open number 3 issue in the CLI

@utnim2  CLI is point `2` and we need point `1` first. Should be an easy PR 🤔 you think you can work on it?

**Comment by utnim2** [comment]
> @utnim2 CLI is point `2` and we need point `1` first. Should be an easy PR 🤔 you think you can work on it?

is point 1 needed you have said [here](https://github.com/asyncapi/generator/issues/521#issuecomment-1997077811) that point 1 is not needed

**Comment by derberg** [comment]
yeah, so we see optimization worked but mainly because of babel that is smart and just tries to regenerate what is not available. But logs still show babel is triggered, so yeah, we should skip it entirely if not needed. So generator should perform transpilation only if explicitly "asked" or if transpiled folder is not present

**Comment by utnim2** [comment]
@derberg will you make the issue or should I proceed with a PR directly

**Comment by utnim2** [comment]
> @utnim2 CLI is point `2` and we need point `1` first. Should be an easy PR 🤔 you think you can work on it?

Done in this #1177

**Comment by derberg** [comment]
still in progress - almost there

**Comment by derberg** [comment]
this issue will be closed with https://github.com/asyncapi/generator/pull/1177

some followup will be done with https://github.com/asyncapi/generator/issues/1259
