### ISSUE TITLE
Expose output directory to the template files

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#527]
#### Reason/Context
I have a use-case where I need the absolute path to the output files, but this is currently not possible through a template.

#### Description
I am not sure if the best approach is to expose the generator object (this is what the hooks have access to) or simply the output directory. 

Example usage with generator object:
```
export default function testFile({ asyncapi, generator }) {
  const outputDir = generator.outputDir;
```

**Comment by derberg** [comment]
I say: if we already pass the generator object to hooks then why not passing it to render engines.

I'm only curious what is the reason it is not done like this already 🤔 there either was no use case or there might be a super good reason to not do it.

**Comment by jonaslagoni** [comment]
I don't recall we ever had the use-case. As I can see without deep diving, there should not be any reason the generator object cannot be exposed in the rendering 🤔

**Comment by derberg** [comment]
@fmvilas do you recall why it is done this way in the generator atm, that entire generator object is passed to hooks but not to render engines, to render engines we expose only some specific things? any specific reason you recall?

**Comment by fmvilas** [comment]
Nope. I think it's just we missed it. I can't recall a specific reason.

**Comment by derberg** [comment]
@jonaslagoni do you still need it, want to work on it? or rather describe well for others to pick as good first issue?

**Comment by jonaslagoni** [comment]
Coming around to this again, on second thought I think it makes sense to close it down, as I cant remember the exact situation that lead to me opening this. 

It might have been in contrast to getting modelina to work with generating models, however I don't see it anymore 😅
