### ISSUE TITLE
Rust code generator

### ISSUE THREAD

**Issue by robot-head** [asyncapi/generator#53]
Wanted to request support for generating serde_json structures from asyncapi definitions.

**Comment by fmvilas** [comment]
That would be awesome. We know nothing about Rust though. If you could help we'd be really happy.

**Comment by robot-head** [comment]
I will see if I can, working at a startup with tight timelines but I would love to help.

**Comment by fmvilas** [comment]
I understand. Let me know if I can help somehow. Sometimes is just a matter of throwing an initial commit with a bootstrap implementation that you are already using. Then people (or a future you) can take it from there. Thanks!

**Comment by derberg** [comment]
@robot-head Hey, I hope you do not mind that I will close this issue in favour of #216. I updated its description so Rust is on the list of the first languages we should support. I checked Quicktype and it supports Rust.
Feel free to reopen this one if I completely misunderstood the topic and you would like to continue the discussion in this issue.
