### ISSUE TITLE
Generator doesn't pull template from private repo

### ISSUE THREAD

**Issue by alextrs** [asyncapi/generator#538]
#### Describe the bug
After upgrade to 1.6.0 version from 1.1.4, ag stopped to recognize npm configuration to use private repository

#### How to Reproduce
```javascript
install @asyncapi/generator@1.6.0

configure NPM to use private repository using:
npm config set registry <path to registry>

try to generate code
ag ./server.yaml @repo/template --force-write --output ./out

see error - Error: 404 Not Found - GET https://registry.npmjs.org/<template in private repo> - Not found

install @asyncapi/generator@1.1.4
ag ./server.yaml @repo/template --force-write --output ./out
Done! ✨

```
#### Expected behavior
Ag should pull template from private repository

**Comment by derberg** [comment]
@alextrs the reason is that with 1.2 we no longer use global npm to install templates, we had to change it to not only support the latest node and npm7 but also to solve some installation-related issues.

tbh, we were not aware people use private registries with generator, so sorry for breaking your functionality.

now we use Arborist for installation (https://github.com/asyncapi/generator/blob/master/lib/generator.js#L371). Luckily what you need is supported -> https://github.com/npm/arborist#usage

we would just need to not only enable Arborist configuration on API level but also figure out how to do it for the CLI, how to name parameters.

Would appriciate some help here

**Comment by derberg** [comment]
would be great if someone could contribute this feature, happy to guide

**Comment by rluvaton** [comment]
I can take it

**Comment by rluvaton** [comment]
A quick workaround would be to install the packages locally (not with the `-g` flag) and run the generate again

**Comment by derberg** [comment]
@rluvaton 🚀 

why do you need workarounds? as I see Arborist supports passing auth token, we just need to enable it on API level and in the code

**Comment by rluvaton** [comment]
I meant workaround until we solve the problem

**Comment by derberg** [comment]
ah, sorry, you are right, this should work

**Comment by derberg** [comment]
This is still valid. I'm happy to help anyone who wants to contribute it

**Comment by toukirkhan** [comment]
I want to contribute in this one.

**Comment by derberg** [comment]
@toukirkhan thanks ❤️ there was already one attempt to fix it but PR was discontinued. You can still have a look at it, and the comments I left there, it will give you some guidance -> https://github.com/asyncapi/generator/pull/673

**Comment by derberg** [comment]
Scope is that someone has to pick up https://github.com/asyncapi/generator/pull/877 and replicate what was done there, and improve stuff from comments

**Comment by mhmohona** [comment]
Would like to work on this issue.

**Comment by aeworxet** [comment]
Bounty Issue's End Of Life (EOL): [2024-02-29 23:59:59 UTC-12:00](https://time.lol/#2024-02-29T23:59:59-12:00)

**Comment by AayushSaini101** [comment]
@derberg I want to start on this issue. Can i take this.?  I have already valid MR merged more than 3 in asynccpai

**Comment by AayushSaini101** [comment]
> @derberg I want to start on this issue. Can i take this.? I have already valid MR merged more than 3 in asynccpai

I have made changes how can I debug? I need some guidelines to debug. Can you please tell

**Comment by chinma-yyy** [comment]
Hey, can I work on this issue?

**Comment by codingmickey** [comment]
Hey! Can I work on this issue? I beleive I can do this

**Comment by princerajpoot20** [comment]
Hey @derber, I would like to work on this

**Comment by derberg** [comment]
Only 2 candidates can be considered for this issue, it is @AayushSaini101  and @princerajpoot20 
Looking at bounty rules:

> Think on the task, make sure that you understand how to do it and CAN do it

Although they did not have to open a PR (did it to quick), they proved he understands the scope and what he is signing up for. Hint for others in future, you can do the same without opening a PR, but just writing transparently in the comment what do you know about the issue

> Regular contributors (GitHub users who have three or more Pull Requests merged throughout the AsyncAPI GitHub Organization, checked with https://github.com/search?q=is%3Apr+org%3Aasyncapi+is%3Amerged+author%3Agh_username)

Both folks also made it super easy for me to quickly click on the link to confirm if they already had 3PR merged

---

Instead of going with some "coin flipping" solution, I decided to give this issue to @AayushSaini101 as he is not involved in any other AsyncAPI program (like mentorship)

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Medium          |2023-11-13                 |[2023-11-20](https://time.lol/#2023-11-20T00:00:00+12:00)              |**[2023-12-29](https://time.lol/#2023-12-29T23:59:59-12:00)**        |[2023-12-01](https://time.lol/#2023-12-01T23:59:59-12:00)         |[2023-12-15](https://time.lol/#2023-12-15T23:59:59-12:00)         |**[2023-12-29](https://time.lol/#2023-12-29T23:59:59-12:00)**|

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.

**Comment by AayushSaini101** [comment]
@derberg I have raised a sample PR Taking PR base of https://github.com/asyncapi/generator/pull/877 . I have also understood the workflow of the generator

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline Extended
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Medium          |2023-11-13                 |[2023-11-20](https://time.lol/#2023-11-20T00:00:00+12:00)              |**[2024-01-26](https://time.lol/#2024-01-26T23:59:59-12:00)**        |[2023-12-29](https://time.lol/#2023-12-29T23:59:59-12:00)         |[2024-01-12](https://time.lol/#2024-01-12T23:59:59-12:00)         |**[2024-01-26](https://time.lol/#2024-01-26T23:59:59-12:00)**|

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.

**Comment by aeworxet** [comment]
@asyncapi/bounty_team

**Comment by aeworxet** [comment]
AsyncAPI Maintainer (@derberg) was absent online in [Slack](https://asyncapi.slack.com) for one period of three working days in a row, so all remaining target dates of the Bounty Issue's Timeline are extended by two calendar weeks.

### Bounty Issue's Timeline Extended
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Medium          |2023-11-13                 |[2023-11-20](https://time.lol/#2023-11-20T00:00:00+12:00)              |**[2024-02-09](https://time.lol/#2024-02-09T23:59:59-12:00)**        |[2024-01-12](https://time.lol/#2024-01-12T23:59:59-12:00)         |[2024-01-26](https://time.lol/#2024-01-26T23:59:59-12:00)         |**[2024-02-09](https://time.lol/#2024-02-09T23:59:59-12:00)**|

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.

**Comment by derberg** [comment]
@aeworxet hey, thanks for reaching out about that topic. So yeah, I'd like to propose that we change this issue from Medium to Advanced. When `medium` level for this issue was assigned, I forgot to take into account advanced testing that will have o be added in a PR to test properly new functionality. I hope we have budget and can pay @AayushSaini101 at the end of the task for `advanced` work.

**Comment by aeworxet** [comment]
Upon request of the AsyncAPI Maintainer (@derberg) Complexity Level of this Bounty Issue has been [reclassified](https://github.com/orgs/asyncapi/discussions/908#discussioncomment-7382700) to `Advanced` and its Timeline changed.

### Bounty Issue has been Reclassified and its Timeline Changed
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Advanced        |2023-11-09                 |[2023-11-13](https://time.lol/#2023-11-13T00:00:00+12:00)              |**[2024-02-23](https://time.lol/#2024-02-23T23:59:59-12:00)**        |[2024-01-19](https://time.lol/#2024-01-19T23:59:59-12:00)         |[2024-02-09](https://time.lol/#2024-02-09T23:59:59-12:00)         |**[2024-02-23](https://time.lol/#2024-02-23T23:59:59-12:00)**|

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.

**Comment by derberg** [comment]
confirming that this is completed, great work 🚀 
@aeworxet please share how @AayushSaini101 should apply for payout

**Comment by aeworxet** [comment]
### Bounty Issue Completed 🎉

Please go to the [AsyncAPI's OpenCollective page](https://opencollective.com/asyncapi) and submit an invoice for `USD 400.00` with the subject `Bounty generator#538`, tag `bounty`.
