### ISSUE TITLE
Mismatch Docker tag <-> generator version

### ISSUE THREAD

**Issue by GodsBoss** [asyncapi/generator#577]
#### Describe the bug

The generator within Docker images seems to be one (patch?) version higher than the Docker image tag says.

#### How to Reproduce

    godsboss@godsboss-HP-EliteBook-x360-1030-G3:~$ docker run --rm -it asyncapi/generator:1.6.5 --version
    1.6.6
    godsboss@godsboss-HP-EliteBook-x360-1030-G3:~$ docker run --rm -it asyncapi/generator:1.6.6 --version
    1.6.7
    godsboss@godsboss-HP-EliteBook-x360-1030-G3:~$ docker run --rm -it asyncapi/generator:1.6.7 --version
    1.6.8
    godsboss@godsboss-HP-EliteBook-x360-1030-G3:~$ docker run --rm -it asyncapi/generator:1.6.10 --version
    1.6.11

I skipped 1.6.8 and 1.6.9, but I guess they show the same phenomen.

#### Expected behavior

Running `docker run --rm -it asyncapi/generator:<x> --version` outputs `<x>` for future images.

**Comment by derberg** [comment]
@GodsBoss sorry for keeping you waiting. I just opened a PR to fix it https://github.com/asyncapi/generator/pull/585

**Comment by derberg** [comment]
I see 1.6.15 also on docker hub and 1.6.14 was skipped, so lgtm
