### ISSUE TITLE
How about changing the name of generator and how we call templates

### ISSUE THREAD

**Issue by derberg** [asyncapi/generator#580]
#### Reason/Context
I was just writing an article where I wanted to briefly explain generator and its templates - I failed again. I'm also failing with it always when tweet about it, some generator or template features.

It is ok for projects like https://github.com/OpenAPITools/openapi-generator to call generator a generator because all is contained in a single repo/project

This is the legacy of our generator, in the past is was also a single project. Now "templates" are standalone projects.

maybe simplest would be
`generator` -> `generator-core` 🤔 
`html-template` -> `html-generator`
`any-template` -> `any-generator`

(as a result, yes, it means renaming packages in npm)

#### Description
I like how [yeoman](https://yeoman.io/) explains what it is, that what we call "templates" are "generators" and what we call "generator" is "yeoman"

I like this because I also many times talk about html-template as "HTML generator" or "Docs generator". 

While it is not a problem to rename html-template to html-generator, obviously it won't be easy to find a name for the generator. There was a good name, but is already taken (**fluffy-robot**) 😞 😆 

What do you think?

**Comment by jonaslagoni** [comment]
Hmm... I think I am too biased to answer this since it makes perfect sense to me 😆However for those that do not know the concept of templates (you would have to dig into how the generator work) I can understand if we want to change it. 

Therefore I am neither for or against it.

**Comment by derberg** [comment]
maybe simplest would be
`generator` -> `generator-core` 🤔 
`html-template` -> `html-generator`
`any-template` -> `any-generator`

**Comment by magicmatatjahu** [comment]
We could name the `templates` as `schematics` and leave the `generator` name :)

**Comment by derberg** [comment]
and how are `schematics` different from `template`? how will this improve the wording and explanation?

@magicmatatjahu

**Comment by magicmatatjahu** [comment]
I thought you needed a synonym :trollface: 

To be honest I have no problem with the name of the generator and with terms such as `html generation` (from template, not generator) etc. For others people, naming may be a problem, but for me, it's not. Let the others emerge.

**Comment by boyney123** [comment]
> `generator` -> `generator-core` 🤔
> `html-template` -> `html-generator`
> `any-template` -> `any-generator`

I quite like the rename to generator I think, I guess the generator > template isn't too much of a hurdle, but I'm just used to generator wording.

![image](https://user-images.githubusercontent.com/3268013/132199744-20826547-da20-4b32-baf9-1d9cd23f2f1e.png)

The descriptions for each template say `Generates` which I guess generator would make more sense? 

But as I said not the end of the world, just another hurdle I have to process to initially understand how generator > templates work, think for me anyway generators would make more sense.

**Comment by derberg** [comment]
@fmvilas only your opinion is missing. If all codeowners are fine, we could query community

**Comment by fmvilas** [comment]
I'd not call them "generators". The tool is also called Generator. Are we going to compose sentences like "Use this generator with Generator"? Or another option is that we change the name of tool as well.

**Comment by derberg** [comment]
they are not called generators, so you would write not `Use this generator with Generator` but use `Node JS Generator` either with `AsyncAPI CLI` or in case of a library, use `generator-core` library.

So you will say `To generate the code in terminal or CI/CD use NodeJS Generator with AsyncAPI CLI. In case you want to do it in a runtime or integrate with your library, use generator-core library`

**Comment by fmvilas** [comment]
Alrighty, sounds good 👍

**Comment by derberg** [comment]
yeah, I do not like the name but I do not think the final idea got much attention, we probably have to give it time
