### ISSUE TITLE
Officially supported image w/ generator + bundle of officially supported templates

### ISSUE THREAD

**Issue by andrew-j-roberts** [asyncapi/generator#587]
#### Reason/Context
If you want to run the generator in an environment with restricted internet access, one of the ways to do that currently is to build the image of the generator & then provide it the local/absolute path to the template it should use. 

It'd be easier to get up and running if there was an officially supported image of the generator that included an exhaustive bundle of all the versions of the officially supported templates, or if that'd be too large size wise maybe just the latest versions of them.

#### Description
- **What changes have to be introduced?**
There would need to be a build step introduced to releases that would build an image w/ the latest version of the generator and all the officially supported templates.

- **How could it be implemented/designed?**
[This issue](https://github.com/asyncapi/generator/issues/538) is similar and would provide a more granular solution to the end goal of this feature request—running the generator in an internet restricted environment, but I think this feature request can stand on its own. An officially supported image would be more convenient and lower the barrier to usage.

**Comment by derberg** [comment]
I'm wondering if we should provide a huge docker image with all template, or maybe rather have setup in all templates, so they not only release npm packages but also a docker image with latest compatible generator and the template?

the problem with having one big bundle on generator repo will cause a situation that it will be quickly outdated and contain only old versions of the template. I mean, generator is not released that frequently, so the official docker image with all the templates can have templates in pretty old versions.

Do you know where I'm getting with my reasoning?

**Comment by andrew-j-roberts** [comment]
Hey @derberg, I do know what you're getting at and from my POV what you suggest is a more elegant solution. Would be interested to hear what others think as well.

I put together a sample repository [here](https://github.com/andrew-j-roberts/asyncapi-generator-binary) that includes a Dockerfile and Github Action for creating a composite image from the generator and a template. Nothing crazy, the generator supports using globally installed templates so it's just one more `npm i` command.

**Comment by derberg** [comment]
keeping it closed, if you still need it, keep in mind we will be deprecating `ag` CLI and all work is now in https://github.com/asyncapi/cli. So if you still need it, please open new issue in new repo
