### ISSUE TITLE
Which versions does this work for?

### ISSUE THREAD

**Issue by basickarl** [asyncapi/generator#60]
As the title states. Which versions of Asyncapi does this work for?

**Comment by fmvilas** [comment]
Latest versions work for 2.0.0-rc1. For support for older versions, use 0.6.x. I'm sorry if it's causing any troubles. We haven't released a stable version of this package yet.

**Comment by basickarl** [comment]
It's ok man! Thanks for the speedy response, looking forward to a stable version!

**Comment by fmvilas** [comment]
Thanks for your understanding!
