### ISSUE TITLE
Support generation of D-Bus XML

### ISSUE THREAD

**Issue by ceich** [asyncapi/generator#643]
#### Reason/Context
I would like to use AsyncAPI to generate D-Bus XML so that:
- I can use AsyncAPI for all interfaces in my system, even inter-process communication (IPC) on a single computer
- I can generate IPC stub/skeleton code from AsyncAPI => D-Bus XML => (many languages)

#### Description
The D-Bus spec includes support for interface [introspection](https://dbus.freedesktop.org/doc/dbus-specification.html#introspection-format) that produces XML. Many languages have packages (e.g. `dbus-codegen`) to create stub/skeleton code from that XML.

**Comment by derberg** [comment]
leaving it closed, we can't really complete it unless there is a volunteer to create a template and actually maintain it
