### ISSUE TITLE
MuleSoft project generator.

### ISSUE THREAD

**Issue by rcarrascosps** [asyncapi/generator#658]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
For the MuleSoft community it would be great to generate a project based on an AsyncAPI spec. The specification can include the different bindings that are currently supported or that are coming in the future. MuleSoft is able to connect to Kafka, Rabbit MQ, JMS, etc.
- How will this change help?
Will help within the MuleSoft community to accelerate the budiling of applications that are Event-Driven
- What is the motivation? 
MuleSoft is a key player in the API Management space and is actually contributing and commited with the ASYNCAPI spec. The community will have a boost if we can incorporate this functionality to the generator. It will be well received, in my opinion, and will be used and implemented in real life cases.

#### Description
Please try answering few of those questions
- What changes have to be introduced?
We will modify the generator to generate a MuleSoft project based on an AsyncAPI spec. Just like we can do it today for a NodeJS based app, or a Pything App; we can to generate a MuleSoft app with the application flows suscribed to what the spec describes
- Will this be a breaking change?
It will be and add-on to the the current generator. It will not touch the current capabilities for the programming languages that are currentlly supported; since this will be for a new platform (MuleSoft) it will be an add-on for the current development, without afeccting other parts of it.
- How could it be implemented/designed?
Myself (Rolando Carrasco) and a colleague (Leonardo Gonzalez) will be in charge of the design and the implementation. We will take care of it.

**Comment by derberg** [comment]
@rcarrascosps there are 2 important questions from my side:

1. Can you come up with some examples of what needs to be really changed in the generator to address MuleSoft needs? Generator is pretty agnostic here, it is just a tool with a bunch of generic features that one should use in a "template", template for HTML generation, or a template for Nodejs app generation. Templates are standalone projects. Not part of this repo.
2. So far we did not yet accept any template that is bound to a specific vendor only. One of the reasons is that it is not focused on the wider community. Also, the spec is pretty agnostic here through bindings feature, so if spec can be agnostic and support multiple bindings, why template can't do the same? We have one example of a template that was donated and is till maintained by Solace -> https://github.com/asyncapi/java-spring-cloud-stream-template but it is not bounds to Solace only. It can work without Solace. My question would be why can't we go this direction with MuleSoft too? We most probably need to go more into details of what are you trying to build in the end.

**Comment by rcarrascosps** [comment]
Hi Lukasz.

Regarding this:
So far we did not yet accept any template that is bound to a specific vendor only. One of the reasons is that it is not focused on the wider community. Also, the spec is pretty agnostic here through bindings feature, so if spec can be agnostic and support multiple bindings, why template can't do the same? We have one example of a template that was donated and is till maintained by Solace -> https://github.com/asyncapi/java-spring-cloud-stream-template but it is not bounds to Solace only. It can work without Solace. My question would be why can't we go this direction with MuleSoft too? We most probably need to go more into details of what are you trying to build in the end.
==
Our approach would be to create a similar to template but instead of JAVA SPRING; will be a MuleSoft pplication. It will not bound to a particular technology (Solace, JMS, RAbbit, etc); it will read the spec and create the MuleSoft application with the required dependencies.

That is exactly what we want to achieve. If that is not part of the generator I understand it, and we can move into the template direction

Thank u again

**Comment by derberg** [comment]
`MuleSoft application` - what does it exactly mean. I'm lacing some knowledge about MuleSoft. I mean how can there be MuleSoft application that is capable of working with any protocol.

Also another question: can MuleSoft app work without MuleSoft. So far I understand it would not be a vendor-neutral template.

Keep in mind that you can create a `template` project wherever you want (doesn't have to be AsyncAPI org) as long as it is compatible with AsyncAPI Generator, it will work.

**Comment by rcarrascosps** [comment]
Hi.
A Mulesoft application can suscribe to different messaging platforms using JMS, RabittMQ , Kafka, MuleSoft Active MQ, Solace, etc.

What I would like to do is:
1) A person designs an API using the AsyncAPI spec
2) A MuleSoft based app that suscribes to the channels described in the specification
3) To use something like this:
ag asyncapi.yaml @asyncapi/nodejs-template -o output -p server=mosquitto

but instead of generating a NodeJS app that consumes the message, to create a MuleSoft app. 
Currently with mulesoft you can create applications based on RAML or OpenAPI spec, in this case we will create an app but based on Asyncapp spec.

That's what I would like to create, and that i think is useful for mulesoft developers. 
The generated mulesoft app, will contains all the necesarry dependencies (RabbitMQ, Kafka, etc) and the flows to suscribe to them.

Sorry if I am not being clear up to this point. 

best regards

**Comment by derberg** [comment]
I think it is much clearer now.

Wouldn't it be better if you keep it here https://github.com/mulesoft-labs instead of AsyncAPI. In AsyncAPI we want to be vendor-agnostic, so Mulesoft-only app would be against it. This is why already mentioned Solace have to work on Java template that can work without Solace. And if you develop your template under `asyncapi` org, we would always push you for the same. Do you know what I mean?

Generator architecture allows you to store the source code wherever you want really, any github org, and publish it on npm wherever you want, so later you can do `ag asyncapi.yaml @mulesoft/some-template` or `ag asyncapi.yaml https://github.com/mulesoft-labs.some-template` if you wish.

Do you know what I mean? technically, to write Mulesoft template compatible with Generator, you do not have to provide code under `asyncapi` GitHub org. Of course we invite all contributors, coming from vendors too, but then you just need to remember that we do not accept vendor-lock-in solutions.

**Comment by rcarrascosps** [comment]
Hi.
Makes sense , Lukasz.

I will proceed on that direction mad it totally makes sense. 



best regards

**Comment by derberg** [comment]
@rcarrascosps you mean you first try to work on it under Mulesoft org, and then, once you are ready to make it more generic you will consider moving under AsyncAPI org? If yes, then please close this ticket, otherwise let us continue discussion

**Comment by rcarrascosps** [comment]
Yes Lucazs , that's what I will do.
I will proceed to close this ticket.

best regards and thank u

**Comment by derberg** [comment]
@rcarrascosps let us know whenever you have questions on how to start writing a template. You know where to find us 😄
