### ISSUE TITLE
Circular "allOf" generates Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by oBJIADo** [asyncapi/generator#666]
### Describe the bug
Circular "allOf" throws Maximum call stack size exceeded.

### How to Reproduce
Used:
- "@asyncapi/generator": "^1.8.14"
- "@asyncapi/html-template": "^0.23.10"

Entity example:

``` yaml
...
Human:
    title: Human
    description: Human.
    allOf:
        - $ref: '#/components/schemas/Entity'
        - type: object
          properties:
            'parent':
                allOf:
                    - $ref: '#/components/schemas/Human'
            name:
              type: string
              minLength: 1
              maxLength: 16
              readOnly: true
          required:
            - name
...
```

When I tried to generate the html template I got an exception:
``` stacktrace
RangeError: Maximum call stack size exceeded
    at PROJECT_PATH\node_modules\@asyncapi\parser\lib\models\schema.js:151:38
    at Array.map (<anonymous>)
    at Schema.allOf (PROJECT_PATH\node_modules\@asyncapi\parser\lib\models\schema.js:151:29)
    at traverseCombinedSchemas (PROJECT_PATH\node_modules\@asyncapi\parser\lib\iterators.js:96:34)
    at traverseSchema (PROJECT_PATH\node_modules\@asyncapi\parser\lib\iterators.js:75:5)
    at PROJECT_PATH\node_modules\@asyncapi\parser\lib\iterators.js:92:7
    at Array.forEach (<anonymous>)
    at checkCombiningSchemas (PROJECT_PATH\node_modules\@asyncapi\parser\lib\iterators.js:91:26)
    at traverseCombinedSchemas (PROJECT_PATH\node_modules\@asyncapi\parser\lib\iterators.js:96:5)
    at traverseSchema (PROJECT_PATH\node_modules\@asyncapi\parser\lib\iterators.js:75:5)
    at recursiveSchemaObject (PROJECT_PATH\node_modules\@asyncapi\parser\lib\iterators.js:195:7)
    at traverseSchema (PROJECT_PATH\node_modules\@asyncapi\parser\lib\iterators.js:68:7)
    at PROJECT_PATH\node_modules\@asyncapi\parser\lib\iterators.js:92:7
    at Array.forEach (<anonymous>)
    at checkCombiningSchemas (PROJECT_PATH\node_modules\@asyncapi\parser\lib\iterators.js:91:26)
    at traverseCombinedSchemas (PROJECT_PATH\node_modules\@asyncapi\parser\lib\iterators.js:96:5)
```

The code that was used to generate:
``` js
const Generator = require('@asyncapi/generator');
Object.keys(asyncApisFiles).forEach(key => {
    let targetDir = `${outputDir}/${asyncApisFiles[key].path}/generated/${key}`;
    const generator = new Generator('@asyncapi/html-template', targetDir, {forceWrite: true});
    generator.generateFromFile(`${outputDir}/${asyncApisFiles[key].path}/${asyncApisFiles[key].hashedFileName}`).then(() => {
        console.log('Html for ' + key + ' schema is generated! Done! ✨');
        let htmlAsString = fs.readFileSync(targetDir + "/index.html", "utf8").toString();
        let chars = {'&lt;img': '<img', '&quot;': '"', '&gt;': '>'};
        htmlAsString = htmlAsString.replace(/(&lt;img)|(&quot;)|(&gt;)/g, m => chars[m]);
        fs.writeFileSync(targetDir + "/index.html", htmlAsString, {encoding: "utf8"});
    }).catch(console.error)
});
```

Unfortunately I cannot provide the whole async-Api file due to NDA. 

### Expected behavior
Successful build.

**Comment by magicmatatjahu** [comment]
@oBJIADo Hi! Currently, we don't support the circular references in some cases, like yours. We only handle circular refs in `items` and `properties` - more info is in this issue -> https://github.com/asyncapi/parser-js/issues/293

Did this problem exist before or did it only appear in `0.23.10` version of `html-template`? I'm asking to make sure if now the `html-template` version didn't mess something up (and it shouldn't). 

Also, why do you make some strange logic for `img` tags?

**Comment by oBJIADo** [comment]
@magicmatatjahu Hi!

About "_some strange logic for img tags?_": this is deprecated logic and should be removed. Never mind this.

The "AllOf" tag was recently added and I don't know if it works before 0.23.

**Comment by magicmatatjahu** [comment]
@oBJIADo 

> The "AllOf" tag was recently added and I don't know if it works before 0.23.

So then it shouldn't work also for previous versions. As I wrote to you, we know about the problem, I even tried to fix it myself, but it's not that easy, because circular references can be everywhere, which complicates things, even when creating a generic solution.

**Comment by magicmatatjahu** [comment]
@oBJIADo The only solution I can see now is to change the schema shape to not have circular references for `allOf`, but I guess in your case this will be very difficult.

**Comment by magicmatatjahu** [comment]
@oBJIADo Hello! I have a good news :) We merged new version of generator and new version of html-template that support circular refs :) You can try it with latest generator `1.8.27` and latest html-template `0.24.0`. Let us know about any bugs/problems! I remember that we test solution with your example and it handles the circular refs in your case :) I will close it, please reopen if you want.

**Comment by oBJIADo** [comment]
I finally have time to try it and it works fine. Thanks a lot!
