### ISSUE TITLE
Move array "sort" operation to a separate statement

### ISSUE THREAD

**Issue by derberg** [asyncapi/generator#667]
More info https://sonarcloud.io/project/issues?id=asyncapi_generator&issues=AXVvKdRcxFJSqWMtO61z&open=AXVvKdRcxFJSqWMtO61z

Code located in `lib/templateConfigValidator.js`

Array-mutating methods should not be used misleadingly. Create a separate variable with clear name

**Comment by kanumalivad** [comment]
Kindly assign to me, Want to work on this

**Comment by derberg** [comment]
Done 😄

**Comment by magicmatatjahu** [comment]
Fixed by #669
