### ISSUE TITLE
use tags for structure

### ISSUE THREAD

**Issue by rv0** [asyncapi/generator#69]
Currently the "tags" system only add tags under each operation.
There's no further functionality as far as I can see.

Swagger also has tags, and uses them for structure. See the pet store example: https://petstore.swagger.io/#/ .. Pet, store, user, etc.. are tags and they provide structure to the document by grouping.

I'm currently documenting a rather big MQTT API and it's very hard to navigate through it at the moment.
The left sidebar is just one big (randomised order) list of summaries of operations. Ideally there would be a hierarchical (collapsible) structure 
```
tag
  - operations
tag2
  - operations
```

The content of the page could also add header titles with tags (see the above pet store example) and even better: have a table of contents / nav with all tags displayed above (anchor links)

**Comment by fmvilas** [comment]
Thanks for opening the issue, @rv0. To clarify:

* We're talking about the HTML template, right?
* If we add a tags menu to the sidebar then the table of contents shouldn't be needed. Am I right?
* When you say hierarchical collapsible structure you mean 2 collapsible items like, for instance, Operations and Tags? Or you mean hierarchical by looking at the common beginning of a channel name?

**Comment by rv0** [comment]
- yes, html template
- yes, tags in sidebar seems like nicest solution
- hierarchical with first level tags and 2nd lavel operations, like the small example above.. hierarchical with channel names would be very cool but seems outside of the scope of this FRQ

**Comment by fmvilas** [comment]
I see. Just as a side note for the future implementer: the hierarchical organization on the sidebar could be driven by a special parameter for the HTML template. See #8.

For instance:

```
ag asyncapi.yaml html --params '{"sidebarOrganization":"hierarchical"}'
```

**Comment by GianniCoene** [comment]
I'm currently working on this issue. So far I have been able to implement the functionality of tags in the sidebar.
The user can click the tag which will reveal all topics associated with that particular tag.

However I ran into some trouble when trying to require the special parameter for the HTML template.
In the code I check if the parameter is present using:
` {{#if params.sidebarOrganization}} ` as mentioned in the referenced issue.
But when I use the CLI to try and generate the docs using the command:
`ag asyncapi.yaml html --params '{"sidebarOrganization":"hierarchical"}'`
I will get a JSON parse error saying: Unexpected token ' in JSON at position 0.

I've tried the parameter in a couple of different notations but none of them seem to work. Any ideas?

**Comment by fmvilas** [comment]
Hey @GianniCoene. I'm trying exactly the same command and it works perfectly. Can you make sure you're running the latest version of the package? If the problem persists, what operating system and terminal are you using?

**Comment by GianniCoene** [comment]
Hello @fmvilas.
I'm using the most recent package. I'm using Windows 10 and CMD (the standard terminal that comes with it).
Just to be clear, the files do generate but I'm getting the --params error message saying they will not be available in the templates because of a parsing error.

**Comment by fmvilas** [comment]
My guess is that it's a Windows CMD issue with double-quotes. Can you try the following:

```
 ag asyncapi.yaml html --params '{\"sidebarOrganization\":\"hierarchical\"}'
```

**Comment by GianniCoene** [comment]
Turns out the problem was an issue with the double-quotes as you said. However I had to leave out the single-quotes as well. The following command works in the Windows CMD:
`ag asyncapi.yaml html --params {\"sidebarOrganization\":\"hierarchical\"}`

Thank you for the help!

**Comment by fmvilas** [comment]
No problem. Windows keeps surprising me 😄

**Comment by marcortw** [comment]
Sorry for writing to a closed thread, but it seems like 'params' is not yet passed on when using the generator as a module with the .generateTemplateFile function. Shall I write a PR?

**Comment by fmvilas** [comment]
You're right. Yeah, feel free to open a PR. Thanks!
