### ISSUE TITLE
Fold long examples

### ISSUE THREAD

**Issue by Tamriel** [asyncapi/generator#72]
When you have long examples, they take up so much space in the right column, that in the middle column there will be very much white space between one operation to the next.

The OpenApi html generator [ReDoc](https://redocly.github.io/redoc/#operation/findPetsByStatus) solves this by folding the examples. The user is able to expand and collapse them.

**Comment by fmvilas** [comment]
Absolutely agree.

**Comment by jonaslagoni** [comment]
I think this was the same as #126 and closed by #153

**Comment by fmvilas** [comment]
🤔 I don't think it's the same. The problem here is that, when the example is so long, it takes a lot of space on the screen. We're talking about limiting the visible height of the example and having an Expand/Collapse link/button below the example.

**Comment by derberg** [comment]
It would be great to get some sample asyncapi spec that is actually generating such a long content, or do you know already some good public example?

Regarding ReDoc. Can you actually point me to a section where this functionality is visible? Is it expand/collapse by default to all, or only for the ones that are longer than the middle section?

In asyncapi-react component, it is solved in the way that all is collapsed by default, and you have one button to expand all, or you can expand one-by-one. So there are different ways to do it, this is why I ask :)

**Comment by derberg** [comment]
Issue moved to [asyncapi/html-template #23](https://github.com/asyncapi/html-template/issues/23) via [**ZenHub**](https://www.zenhub.com/)
