### ISSUE TITLE
Something went wrong using @asyncapi/generator v.1.8.27

### ISSUE THREAD

**Issue by aminrahman** [asyncapi/generator#728]
#### Describe the bug
I have been using @asyncapi/generator v.1.8.11 and it was ok. But using @asyncapi/generator 1.8.27 while generating HTML templates, I constantly get this error:
```
Something went wrong:
Error: command failed
    at ChildProcess.proc.on (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@npmcli/promise-spawn/index.js:64:27)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

```

#### How to Reproduce
I get this error just trying to generate HTML results using the ag command.

**Comment by magicmatatjahu** [comment]
@aminrahman Hi! Could you write which version of npm/node are you using? I think that it's related to that versions, not to generator itself.

**Comment by aminrahman** [comment]
> @aminrahman Hi! Could you write which version of npm/node are you using? I think that it's related to that versions, not to generator itself.

Hi. I am using npm 6.14.4 and node 10.19.0.

**Comment by aminrahman** [comment]
> @aminrahman Hi! Could you write which version of npm/node are you using? I think that it's related to that versions, not to generator itself.

Thank you @magicmatatjahu. It was a matter of version conflict. As in [here](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04) apt repo only contains old and not-supported versions of node. Therefore, I used the [Manual installation](https://github.com/nodesource/distributions/blob/master/README.md#manual-installation) section of nodesource distribution to install newer versions.
