### ISSUE TITLE
Offline installation of @asyncapi/generator

### ISSUE THREAD

**Issue by aminrahman** [asyncapi/generator#729]
#### Reason/Context
We have a project that is running on a local private server. We provide services over ActiveMQ and we use AsyncAPI to generate ApiDocs. The problem is that we don't have internet access on our systems to generate ApiDocs. 

#### Description
Is there any way you could provide the possibility to completely download @asyncapi/generator as a package and move it to another device that doesn't have internet access to install it using npm?

**Comment by jonaslagoni** [comment]
Hey @aminrahman, it is just a node library, so downloading the source files then installing the dependencies `npm i` allow you to execute `node ./cli.js ...` 

That way you can also download the desired templates and reference them locally as `node ./cli.js asyncapi.json ./html-template --output ./apidocs`

**Comment by magicmatatjahu** [comment]
You can always install `@asyncapi/generator` and `@asyncapi/html-template` in local project, then copy everything (with `node_modules`) to desired location (where you haven't internet) and try to generate by cli in `node_modules/@asyncapi/generator/cli.js` like:

```bash
node node_modules/@asyncapi/generator/cli.js {YOUR_ASYNCAPI} node_modules/@asyncapi/html-template -o {OUTPUT} {PARAMETERS}
```

Other solution is using docker but without internet you need to fetch image of generator and somehow transfer it to a machine where you don't have internet

**Comment by derberg** [comment]
answer provided, no followup, closing
