### ISSUE TITLE
AsyncAPI generate crashes when watching a local template during development

### ISSUE THREAD

**Issue by felixjung** [asyncapi/generator#738]
#### Describe the bug

When developing a new template locally and using the `--watch-template` flag, the generator crashes after generating the template.

The error message on a Mac with `nodenv` is

```
[WATCHER] Watching for changes in the template directory /Users/{username}/{path}/asyncapi-go-template and in the AsyncAPI file asyncapi.yaml
Something went wrong:
Error: ENOENT: no such file or directory, lstat '/Users/{username}/.nodenv/versions/17.3.1/lib/node_modules/@asyncapi/generator/node_modules/asyncapi-go-template'
```

#### How to Reproduce

1. Start a new template, for example using the generator template repository.
2. Start the generator in watch mode: `ag --watch-template --output ~/Desktop/asyncapi --force-write asyncapi.yaml "$(pwd)/{your template}"`.

#### Expected behavior

The template should be rendered in the output directory and the generator should continue running, watching for changes.

**Comment by felixjung** [comment]
This bug is caused by a [check for a local template in `cli.js`](https://github.com/asyncapi/generator/blob/master/cli.js#L126). The async function that's being executed returns an error when the folder that's being checked doesn't exist. Since the template is a local one for development, it doesn't exist in the default location `{global node_modules}/@asyncapi/generator/node_modules/{template name}` and `fs.lstat` returns an error.

The error isn't being handled and the CLI crashes in the line linked above.

**Comment by derberg** [comment]
@rcollette Hey, we will pretty soon deprecate Generator CLI. We already enabled generator in [AsyncAPI CLI](https://github.com/asyncapi/cli)

please use CLI with AsyncAPI CLI and if there are any issues with the watcher, these should be fixed there. After CLI installation just run `asyncapi generate fromTemplate --help` to learn more.

Thanks 🙏🏼
