### ISSUE TITLE
Missing Property Descriptions of Referenced Array Objects

### ISSUE THREAD

**Issue by lukas99** [asyncapi/generator#75]
When an object is referenced by an array, the property descriptions of the referenced object are not generated and printed in HTML.

See the following demo specification and use https://playground.asyncapi.io/

---

asyncapi: '2.0.0-rc1'
id: 'urn:demo'
info:
  title: Demo
  version: '1.0'

channels:

  demo/channel:
    publish:
      message:
        $ref: '#/components/messages/demoMessage'

components:

  messages:

    demoMessage:
      name: demoMessage
      payload:
        $ref: '#/components/schemas/demoHeader'

  schemas:

    demoHeader:
      type: object
      properties:
        id:
          type: string
          description: The id
        demoItems:
          type: array
          description: The items of the header
          items:
            $ref: '#/components/schemas/demoItem'

    demoItem:
      type: object
      properties:
        id:
          type: string
          description: The id of the demoItem
        name:
          type: string
          description: The name of the demoItem
        type:
          type: string
          description: The type of the demoItem

![demo](https://user-images.githubusercontent.com/7577436/62698125-a729f800-b9dc-11e9-9427-7019f4c7d5b0.PNG)

**Comment by fmvilas** [comment]
Thanks for the great bug report!

**Comment by fmvilas** [comment]
Fixed at #77.
