### ISSUE TITLE
AVRO schema unions code generation issue

### ISSUE THREAD

**Issue by RobertOttesen** [asyncapi/generator#753]
#### Describe the bug
When an AVRO schema is use that contains unions, for example, ["null", "string"], the generated code is invalid.

#### How to Reproduce
The following snippet from an AVRO schema contains a union of "null" or "string".  See the attached bad events.yml file for the full schema.

`- name: "jobOrderDescription"
          doc: "JobOrderDescription"
          type:
          - "null"
          - "string"
`

Run through code generator.

`ag -o badevents badevents.yml @asyncapi/java-spring-cloud-stream-template`

The generated POJO for the referenced event class contains the following:

`public JobOrder (
		String jobOrderId, 
		&lt;anonymous-schema-2&gt; jobOrderDescription, 
		&lt;anonymous-schema-5&gt; jobOrderLongDescription, 
		String jobOrderNumber, 
		Boolean isActive, 
		String status, 
		Integer statuscode) `

#### Expected behavior
I was expecting at minimal an Object type that would allow the code to be compiled
[badevents.txt](https://github.com/asyncapi/generator/files/8134934/badevents.txt)
.

**Comment by CameronRushton** [comment]
It seems this is a problem with the java-spring-cloud-stream-template and not the generator itself. I'd recommend closing this issue and tracking the copy of it made here https://github.com/asyncapi/java-spring-cloud-stream-template/issues/247
