### ISSUE TITLE
Missing description of channel

### ISSUE THREAD

**Issue by lukas99** [asyncapi/generator#76]
When a channel has a description, it is not generated and printed in HTML.

See the following demo specification and use https://playground.asyncapi.io/

---
```
asyncapi: '2.0.0-rc1'
id: 'urn:demo'
info:
  title: Demo
  version: '1.0'

channels:

  demo/channel:
    description: The description of demo channel.
    publish:
      summary: Channel summary
      message:
        $ref: '#/components/messages/demoMessage'

components:

  messages:

    demoMessage:
      name: demoMessage
      payload:
        $ref: '#/components/schemas/demoHeader'

  schemas:

    demoHeader:
      type: object
      properties:
        id:
          type: string
          description: The id of the header
        name:
          type: string
          description: The name of the header
```

![grafik](https://user-images.githubusercontent.com/7577436/62698510-97f77a00-b9dd-11e9-863d-d67f7f547037.png)

**Comment by fmvilas** [comment]
Thanks again for the great bug report!

**Comment by fmvilas** [comment]
Hey @lukas99! @WaleedAshraf fixed the issue and I just published the package to npm. It's on version 0.9.0. Please note this version comes with a big change: we changed our template system from Handlebars to Nunjucks. If you don't have any custom templates, it should not affect you. Thanks!
