### ISSUE TITLE
simple-git/promise import warning

### ISSUE THREAD

**Issue by fidgi** [asyncapi/generator#770]
#### Describe the bug
While using the generator to generate html doc , a warning from simple-git is raised : 

`
=============================================
simple-git has supported promises / async await since version 2.6.0.
 Importing from 'simple-git/promise' has been deprecated and will be
 removed by July 2022.

To upgrade, change all 'simple-git/promise' imports to just 'simple-git'
=============================================
`

#### How to Reproduce
used generator version : 1.9.1
Just try to generate html doc from an asyncapi.yaml.
`
npx ag specs/asyncapi.yaml ../node_modules/@asyncapi/html-template -o ./html
`

#### Expected behavior
No warning from simple-git

**Comment by pavlikm** [comment]
https://github.com/asyncapi/generator/pull/775
