### ISSUE TITLE
Why does the "generator" need to use "simple-git"?

### ISSUE THREAD

**Issue by man-to-learn** [asyncapi/generator#776]
sorry,I‘m a backend developer.I don't understand the 2 errors below.
> An error will occur when there is no git environment.
> An error will occur when there are uncommitted changes.
Would you get me some help?Thanks.

**Comment by derberg** [comment]
@man-to-learn it is a pretty old feature that is supported by `simple-git`. Have a look at [this PR](https://github.com/asyncapi/generator/pull/223) and linked issue to understand the need and the use case.

**Comment by derberg** [comment]
no follow up, closing. Feel free to leave a comment if you want to reopen and have more questions
