### ISSUE TITLE
[📑 Docs]: determine page outline for Generator Tool docs

### ISSUE THREAD

**Issue by alequetzalli** [asyncapi/generator#789]
### What Dev Docs changes are you proposing?

# Determine outline for Generator Tool docs
Before any TW investment is done toward adding the [Generator Tool](https://github.com/asyncapi/generator) docs in our `/website` repo, we need to agree on the content outline we'll use for this tool documentation. After the outline is agreed upon, the migration and re-writing efforts will make more sense. (cc @pratik2315 @Florence-Njeri) 

## SAMPLE Generator Tool docs outline (to get ideas rolling)
- **Overview** _(what use cases/scenarios this tool solves)_
- **Installation guide** _(download/install instructions)_
- **CLI Command reference** _(list of commands & what they do)_
- **Workflows (functionality)** _(Show us how to use the tool and it’s **functionality**. ex: generate a template, author a template)_

### URLs for new tool docs page and section hyperlinks
If we use the above sample outline, then we'd in turn end up with URLs as follows:

- `docs/tools/generator`
- `docs/tools/generator#overview`
- `docs/tools/generator#installation-guide`
- `docs/tools/generator#cli-command-reference`
- `docs/tools/generator#workflows`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pratik2315** [comment]
> I'm not convinced about `CLI Command reference` and `Workflows` because:
> 
> * Generator is mainly a library. Current CLI will be soon deprecated and people will use generator in the main [`asyncapi` CLI](https://github.com/asyncapi/cli/pull/221). So we should have a main section like `Usage` or `Integration` where we explain both, CLI of course, but also how to use generator on JavaScript API level ( + find a way how to integrate current generator API.md in the whole story)
> * Instead of `Workflows` we need separate section with a set of tutorials on how to create code generator with AsyncAPI Geneerator.

In my 1:1 onboarding call with @alequetzalli , we had a brainstorming practice session about where the generator tutorials should belong. The conclusion was that, since we already have a tutorials section with "Streetlights" and "Streetlights - Interactive (Alpha)" content buckets, we could maybe create similar content buckets for the Generator stuff? So one possible hyperlinks architecture could be for example: `docs/tutorials/generatorTutorial1` 🤔

> * We need a place where we can explain concepts in generator, basically what is AsyncAPI generator and what is Template. What are render engines and what is context

Okay! So if I am not wrong this information could go to: `docs/tools/generator#overview` ?

> * We need a place where we can explain reference info about all possible Configurations that one can do in their code generators
> * Even though we will have tutorials on writing a code generator, we still need a reference docs of all the Generator features, where we discuss all possible options (while in tutorial you always cover just some)
> 
> > is done toward adding the [Generator Tool](https://github.com/asyncapi/generator) docs in our /website repo
> 
> Source of documentation, markdown files will be stored and developed in `generator` repository and just pushed to `website` to render them nicely in the UI, thus moving this issue to `generator` repo so it is visible to all it's users and maintainers, so they can also share their opinion.

**Comment by pratik2315** [comment]
I also had a suggestion I wanted to get reviewed😅
What do you guys think about a separate section for FAQ's related to generator tool where we list common errors faced while using the generator tools and ways to deal with them? or does that conflict with our current information architecture?🤔

what do you think @derberg @alequetzalli @Florence-Njeri !

**Comment by derberg** [comment]
> In my 1:1 onboarding call with @alequetzalli , we had a brainstorming practice session in which we discussed where the generator tutorials should belong. The conclusion was that, since we already have a tutorials section with "Streetlights" and "Streetlights - Interactive (Alpha)" content buckets, we could maybe create similar content buckets for the Generator stuff? So one possible hyperlinks architecture could be for example: docs/tutorials/generatorTutorial-1 

yes, we have current streetlight tutorial but, even though it uses AsyncAPI Generator, its goal is more about showing what you can get out from writing AsyncAPI document. In case of Generator tutorials, we will have more step by step tutorials showing how to create a template, and using a template to generate something will be one of the tutorial set

> Okay! So if I am not wrong this information could go to: docs/tools/generator#overview ?

tbh I think we will end up with `docs/tools/generator/concepts/overview` 🤔 

> What do you guys think about a separate section for FAQ's related to generator tool where we list common errors faced while using the generator tools and ways to deal with them? We can also collect and list some of the most commonly asked questions about the asyncapi community and most used tools and try to answer them there. Does that sound good ! or does that conflict with our current information architecture?🤔

I love FAQs, we just need to be careful to not put there everything. Sometimes asked community question should convert into update in existing doc or additional concept document, not quick new-FAQ-entry

**Comment by alequetzalli** [comment]
> I also had a suggestion I wanted to get reviewed😅 What do you guys think about a separate section for FAQ's related to generator tool where we list common errors faced while using the generator tools and ways to deal with them? We can also collect and list some of the most commonly asked questions about the asyncapi community and most used tools and try to answer them there. Does that sound good ! or does that conflict with our current information architecture?🤔


@pratik2315 So we won't have FAQs in the Tools docs, because it's not a blog post or stand-alone page. Rather.. think about how documenting limitations or common errors fit within out new IA. In this case, we will have the **how-to** section added as a content bucket for writing guides to common user problems/error scenarios. The tool limitations would also require a well-thought-out content outline header for those topics.

To further illustrate the issue I want us to avoid, let me [quote Tom Johnson](https://idratherbewriting.com/2017/06/23/why-tech-writers-hate-faqs/): 

> _"All too often the FAQ format is abused by non-writers who want an easy way to write. The list of random questions grows with each incoming question until it's a ridiculous hodgepodge of information thrown together, with no larger story or narrative."_

**Comment by pratik2315** [comment]
> > I also had a suggestion I wanted to get reviewed😅 What do you guys think about a separate section for FAQ's related to generator tool where we list common errors faced while using the generator tools and ways to deal with them? We can also collect and list some of the most commonly asked questions about the asyncapi community and most used tools and try to answer them there. Does that sound good ! or does that conflict with our current information architecture?🤔
> 
> @pratik2315 So we won't have FAQs in the Tools docs, because it's not a blog post or stand-alone page. Rather.. think about how documenting limitations or common errors fit within our new IA. In our new IA, we'll have a **how-to** section added as a NEW content bucket for writing guides to common user problems/error scenarios. The tool limitations also require a well-thought-out content outline header for those topics.
> 
> To further illustrate the issue I want us to avoid, let me [quote Tom Johnson](https://idratherbewriting.com/2017/06/23/why-tech-writers-hate-faqs/):
> 
> > _"All too often the FAQ format is abused by non-writers who want an easy way to write. The list of random questions grows with each incoming question until it's a ridiculous hodgepodge of information thrown together, with no larger story or narrative."_

That makes sense! Thanks for the input💪😄
