### ISSUE TITLE
Configure nunjucks

### ISSUE THREAD

**Issue by jbadeau** [asyncapi/generator#791]
Ability to configure nunchcucks as described here https://mozilla.github.io/nunjucks/api.html#customizing-syntax.

Maybe this is already possible but I didn't find it in the docs.

#### Description
For example, to customize the syntax

**Comment by magicmatatjahu** [comment]
@jbadeau Hi! Now you can add filters or macros, described in the:

- [Template filters](https://github.com/asyncapi/template-for-generator-templates/tree/nunjucks#template-specific-filters)
- [Using filters](https://github.com/asyncapi/template-for-generator-templates/tree/nunjucks#using-filters)
- [Macros, partials](https://github.com/asyncapi/template-for-generator-templates/tree/nunjucks#partials)

But we don't allow to change syntax.

**Comment by derberg** [comment]
I definitely do not recommend investing in Nunjucks, and use React engine instead 👍🏼

**Comment by derberg** [comment]
I stated before, there are other ways to do things with nunjucks, and we do not do more with this render engine because if investment in react
