### ISSUE TITLE
Add support for Quarkus Generator

### ISSUE THREAD

**Issue by InfoSec812** [asyncapi/generator#794]
I would like to work on adding support for a Quarkus generator/templates. It would likely use SmallRye Reactive Messaging.

**Comment by derberg** [comment]
@InfoSec812 give it a go, especially that we do not know any implementation so far. Templates are separate projects. So you can work on them separately in your repo, and then once ready, submit to join AsyncAPI if you want. Need a hand?

**Comment by derberg** [comment]
@InfoSec812 all good?

**Comment by InfoSec812** [comment]
All good except for not having any time to work on this... :)

**Comment by derberg** [comment]
@InfoSec812 welcome to the club 😆
