### ISSUE TITLE
CLI support template parameters

### ISSUE THREAD

**Issue by rmelian** [asyncapi/generator#8]
Right now the CLI doesn't support passing parameters specific to a template. 

Having a way to pass additional information to a template can open the door to a lot of flexibility. 
For example, for the java generator, we could use the following commands to generate the same code but with different build tools like maven or gradle:  
`ag asyncapi.yaml java-spring maven` 
`ag asyncapi.yaml java-spring gradle` 

I'm not sure if the commander library supports this type of workflow.  I'll try to find that out.

**Comment by netoec84** [comment]
It is fine if it's works like:
`ag asyncapi.yaml java-spring '{ "buildTool": "maven" }'`

And in template it could be used as:
`{{ templateParams.buildTool }}`

You could have json object with more properties, por example:
``ag asyncapi.yaml java-spring '{ "buildTool": "maven", "numericOption": 123, "otherOption": {} }'``

Is that the idea?

**Comment by fmvilas** [comment]
Yeah, that's the idea. Not sure if the format should be this one or something like `ag asyncapi.yaml java-spring --params '{...}'`. What do you think?

**Comment by netoec84** [comment]
I like the idea of passing the value with the option `--params`.

I thought it could also be the route to a file, but with one of the two options it would be fine for now
