### ISSUE TITLE
Wrong execution when trying to generate html template

### ISSUE THREAD

**Issue by mathecruz** [asyncapi/generator#802]
#### Describe the bug
Running generator I got this error:

```
[action:generate-async][layer:use-case][app:ptp-load-test-app][version:0.0.0-test-200]          
Error while trying to execute the use case. 
Error:  Error: command failed     at ChildProcess.<anonymous> (/app/node_modules/@npmcli/promise-spawn/index.js:64:27)     at ChildProcess.emit (events.js:315:20)     
at ChildProcess.EventEmitter.emit (domain.js:467:12)     
at maybeClose (internal/child_process.js:1048:16)     
at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
--
```

#### How to Reproduce
npm version: 6.14.16
node version: 14.15.14
 @asyncapi/generator: ^1.9.5,

code:
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/88394201/176729456-d36760ab-f588-4a5e-ac8b-33f8d44528fa.png">

#### Expected behavior
I want to generate html template.

**Comment by magicmatatjahu** [comment]
@mathecruz Hi! As I see, error is not related to the generator. Please give us more info about error.

**Comment by mathecruz** [comment]
@magicmatatjahu Hi :)
<img width="876" alt="image" src="https://user-images.githubusercontent.com/88394201/179325834-788db0e9-59b8-406d-aec1-b786e576b297.png">
It is related yes... se the log

**Comment by magicmatatjahu** [comment]
@mathecruz Did you install `@asyncapi/html-template` in your project, next to generator? If not, generator tries to install that package for you, but as I see, it has some problems with that (by logs I cannot see reason). You can install template by `npm i @asyncapi/html-template` and then generator will use template from local node_modules :)

Let me know if it helped :)

**Comment by derberg** [comment]
@mathecruz I also recommend to `npm i @asyncapi/html-template` if you use generator as library. It will also "fix" you to specific version, so it is safer. 

I'll close it for now. But please feel free to leave a comment that you are not happy with the solution and I will reopen
