### ISSUE TITLE
Typescript (Angular) generator

### ISSUE THREAD

**Issue by daniel-sc** [asyncapi/generator#803]
#### Reason/Context
- Consuming AsyncAPI from the browser via websocket (stomp) is a common scenario. DEV experience would greatly increase if you'd provide a generator for client-stubs and models similar to the openapi generator: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-angular.md

#### Description
Implementation could follow the openapi generator for typescript-angular.

It would be extra cool if both would be "compatible" in the following sense: For many projects OpenAPI and AsyncAPI exist in parallel and reference the same models. There should be a maningful setup, so that e.g. models from the openapi generator could be used in the AsyncAPI generated client.

**Comment by derberg** [comment]
@daniel-sc 

> For many projects OpenAPI and AsyncAPI exist in parallel and reference the same models

In AsyncAPI you can reference schemas provided using OpenAPI schema

> Implementation could follow the openapi generator for typescript-angular.

So we already have https://github.com/asyncapi/modelina that generates models to TS. Just a matter of contributing missing features there. You can already use modelina in our CLI with `asyncapi generate models`

> if you'd provide a generator for client-stubs

We can definitely help with writing a template for client generation, but writing it from scratch on our own.. will be hard to find time now. 
There is one guy from Oracle that I mentored on starting with client generation for WebSocket (no subprotocols afaik) but I'm not sure how he is doing, will check with him. Also please remember that we still did not figure out STOMP bindings and also how to reuse them in WebSocket when used as a sub protocol -> https://github.com/asyncapi/spec/issues/787
