### ISSUE TITLE
[📑 Docs]: Provide new doc about installation and usage

### ISSUE THREAD

**Issue by derberg** [asyncapi/generator#810]
### What Dev Docs changes are you proposing?

We miss the following docs in current outline: Installation and Usage

What do you think, we need one, two or 3 separate docs?

Nevertheless technical input 👇🏼 

## Installation

I think it makes sense to also add new document called `Installation` where we explain how to install the generator (and also update) and what are technical requirements. Better separate than mixing it with the Intro doc. Even though we know `ag` CLI is going away soon, under `asyncapi` CLI the way it works will not be much different, so simple update to docs will need to be done, not much work

technical input -> https://github.com/asyncapi/generator#using-from-the-command-line-interface-cli

also I think https://github.com/asyncapi/generator#generator-version-vs-template-version should be here. I'm not sure if it should be separate document.

## Using Generator in CLI

We need to explain how to use generator in the CLI

Actually all that we have in the readme must be here in docs. Because ultimate goal is to have all generator docs in one location, and in readme long term we will just link to docs.

Don't worry, we are migrating to new CLI but commands will not change much. Later simple update with search and replace will be possible.

## Using Generator as a library

Readme already has nice simple example on how o use generator npm module. Just the thing is that it is linking to https://github.com/asyncapi/generator/blob/master/docs/api.md

The `api.md` is generated using `npm run docs` and ultimate goal -> we also have it rendered in asyncapi.com. So please, with this issue, also add `api.md` to this readme -> https://github.com/asyncapi/generator/blob/master/docs/README.md

cc @pratik2315 @Florence-Njeri

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Florence-Njeri** [comment]
Hey @derberg I think https://github.com/asyncapi/generator#generator-version-vs-template-version should be a separate document and then I can link it whenever I mention installing a specific version of the generator and also link it when writing about template versions.

**Comment by derberg** [comment]
done by @Florence-Njeri 

- https://github.com/asyncapi/generator/blob/master/docs/installation-guide.md
- https://github.com/asyncapi/generator/blob/master/docs/usage.md
