### ISSUE TITLE
Integrate new ParserAPI

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/generator#825]
We should integrate new ParserAPI in Generator but with fallback compatibility with old one, solution described in the https://github.com/asyncapi/parser-js/issues/585:
- add support for new (optional!) field in template's config, `apiVersion` with possible values, `v2` and `v1` - `v1` should be default value
- integrate new `parser-js` version in generator
- add possible tests
- update docs

**Comment by jonaslagoni** [comment]
This is actually blocking templates from using the new Modelina `next` branch... At least in the general sense. I tried upgrading to the [.NET NATS template](https://github.com/asyncapi/dotnet-nats-template/blob/master/template/AsyncapiNatsClient/models/models.js) to use the new branch, but it's conflicting with the parsed AsyncAPI document not having the new parser API when using the AsyncAPI input processor in Modelina.

I could reparse everything again, but that does not seem right to do either 😄 

Any suggestions how to fix it?
