### ISSUE TITLE
Replace fs.exists with fs.stats

### ISSUE THREAD

**Issue by nodify-at** [asyncapi/generator#836]
#### Reason/Context
fs.exists function is deprecated (see: https://nodejs.org/docs/latest-v14.x/api/fs.html#fs_fs_exists_path_callback) and it causes to unstable behaviour if used with promisify with async hooks. (see: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1185)

#### Description
We can use [fs.stat()](https://nodejs.org/docs/latest-v14.x/api/fs.html#fs_fs_stat_path_options_callback) as it is suggested in node.js official documentation.

This change won't break any functionality, we can release a patch version. I can prepare a PR if it is OK for you :)

**Comment by magicmatatjahu** [comment]
@nodify-at Hi!

> This change won't break any functionality, we can release a patch version. I can prepare a PR if it is OK for you :)

Sure, go ahead :)

**Comment by nodify-at** [comment]
@magicmatatjahu I create a PR :) Thanks. (#838)
