### ISSUE TITLE
The generator discards the version specified

### ISSUE THREAD

**Issue by olvlvl** [asyncapi/generator#84]
Hi,

We expect the tools handling the YAML file to adjust their engine according to the version of the specification defined in the file, not to target the upcoming, unreleased, latest version.

A file with the following version should be handled accordingly. Right now the generator renders empty files, without so much as a warning. This is very confusing.

```
asyncapi: 1.2.0
```

I installed a previous version to be able to work with the current version of the specification.

```bash
npm install -g asyncapi-generator@0.6.4
```

Maybe we could mention this in the README.

**Comment by fmvilas** [comment]
You are absolutely right and I'm very sorry about this. We're not going to support version 1.x further (lack of resources to do so). In the meantime, you may want to convert your AsyncAPI documents to 2.0.0-rc1 using this package: https://github.com/asyncapi/converter.

I'm gonna keep this issue open as a reminder to update the README file. Thanks!

**Comment by olvlvl** [comment]
Hi Fran, do you have an ETA for v2?

**Comment by fmvilas** [comment]
Yes, will be officially launched on September 12th, during the APIdays Barcelona conference.

**Comment by olvlvl** [comment]
Great! Have a great launch!

**Comment by fmvilas** [comment]
Thank you, @olvlvl!

**Comment by fmvilas** [comment]
I just added a warning on the README. Thanks for reporting, @olvlvl!
