### ISSUE TITLE
It doesn't work with typescript v4.8.3

### ISSUE THREAD

**Issue by iamdenny** [asyncapi/generator#841]
#### Describe the bug
It's not working with typescript v4.7.x ~ v4.8.x

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

Please check typescript changes.

- Screenshots
- Link to GitHub repository with project that has issues
- Files that can help reproduce the issue, like your AsyncAPI file, either paste inside the issue in a code block or in a sharable [gist](https://gist.github.com/)

![image](https://user-images.githubusercontent.com/1505166/192144368-d4cac682-1469-4a3f-ba71-1f3d51067441.png)

**Comment by derberg** [comment]
@iamdenny feel free to open up PR with the fix, if it is only about bumping `typescript` dependency
