### ISSUE TITLE
Migrate package-lock.json file to version 2

### ISSUE THREAD

**Issue by smoya** [asyncapi/generator#853]
#### Reason/Context

Parser-JS [requires now](https://github.com/asyncapi/parser-js#develop) Node.js 14 and npm7 or higher.
This means `package-lock.json` version should be always set to `2`. 

#### Description

In order to unify development requirements, I suggest all repositories to stick with that requirements. In order to do that, the following is needed:

- Clarify this requirement under Development section on this repository README file.
- To update `package-lock.json` to version `2`. This is automatically done when running `npm install` if the npm version used is 7 or higher.

Related: 

- https://github.com/asyncapi/.github/issues/177

**Comment by derberg** [comment]
till needed

**Comment by derberg** [comment]
resolved
