### ISSUE TITLE
[Docs Bug 🐞 report]: Links in main readme files are dead

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#873]
### Describe the bug you found in AsyncAPI Docs.

There are multiple links dead in https://github.com/asyncapi/generator#cli-installation

### Attach any resources that can help us understand the issue.

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by derberg** [comment]
true, should point to https://github.com/asyncapi/generator/blob/master/docs/installation-guide.md

other links for usage and versioning are also wrong, they are missing `docs/` prefix

/gfi docs

**Comment by Amishakumari544** [comment]
@jonaslagoni hey👋,how did I find all links? Is there any specific location where all links are available?

**Comment by Florence-Njeri** [comment]
Hello, @Amishakumari544 all the links can be found in the docs folder here 👉🏿https://github.com/asyncapi/generator/tree/master/docs. You'll need to add the /docs prefix to the broken links as mentioned by Lukasz above. For example, currently, clicking the installation guide points to: https://github.com/asyncapi/generator/blob/master/installation-guide.md. After your updates, the new link should look like this: https://github.com/asyncapi/generator/blob/master/docs/installation-guide.md.

**Comment by sambhavgupta0705** [comment]
cc @derberg @Florence-Njeri @jonaslagoni
