### ISSUE TITLE
Docker tag override with latest

### ISSUE THREAD

**Issue by nabilnaffar-sf** [asyncapi/generator#89]
Docker tag should match application version.
Currently all tags are '0.1.0' and 'latest'.

**Use case:**
When version is broken, there is no way to install previous working docker image with stable version.

**Comment by fmvilas** [comment]
[Current tags](https://hub.docker.com/r/asyncapi/generator/tags) are 0.10.0 and latest. They are correct and match the package version.

That said, 0.10.0 is our first version on Docker Hub. We'll keep pushing new tags matching package versions from now on.
