### ISSUE TITLE
cleanup readme and point to new docs location

### ISSUE THREAD

**Issue by derberg** [asyncapi/generator#892]
Now generator docs, on each push to master, will be published to https://www.asyncapi.com/docs/tools/generator

IMHO we should now:
- remove all content from `docs/readme.md` as it do not make sense to maintain TOC there as docs anyway should be read in the website. We can now just put short paragraph that docs for generator are renders and should be read in https://www.asyncapi.com/docs/tools/generator
- remove docs related sections from `readme.md` and just have one section `Documentation` and there short intro and link to https://www.asyncapi.com/docs/tools/generator

Thoughts?

**Comment by Amishakumari544** [comment]
@Florence-Njeri can I help you? 😶‍🌫️

**Comment by Florence-Njeri** [comment]
@Amishakumari544 yes you can. Do you still want to pick this up?

**Comment by janvi01** [comment]
Hey, @derberg I would like to work on this, can I take this up?

**Comment by pratik2315** [comment]
Hey @janvi01 
@Amishakumari544 commented first. If she's not available, you can go ahead and help @Florence-Njeri with this PR

**Comment by BhaswatiRoy** [comment]
Hello
Is this issue still open for work or some progress is already made?

**Comment by pratik2315** [comment]
Hey @BhaswatiRoy I think Florence has made a PR to fix this particular issue
