### ISSUE TITLE
[Docs Bug 🐞 report]: Incorrect url link in the generator introduction page

### ISSUE THREAD

**Issue by janvi01** [asyncapi/generator#906]
### Describe the bug you found in AsyncAPI Docs.

There is an incorrect link to the `AsyncAPI Document` in the generator introduction [page](https://www.asyncapi.com/docs/tools/generator) which points to a 404 page.

The actual link is - https://www.asyncapi.com/docs/tools/generator/asyncapi-document

### Attach any resources that can help us understand the issue.

<img width="1791" alt="Screenshot 2023-01-25 at 7 57 27 PM" src="https://user-images.githubusercontent.com/34344234/214590305-3b0f56a7-f855-4068-a07b-911087e0d37b.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by janvi01** [comment]
I would like to work on this.

**Comment by Florence-Njeri** [comment]
Hey @janvi01, there's a PR up for this https://github.com/asyncapi/generator/pull/895

**Comment by janvi01** [comment]
my bad, apologies @Florence-Njeri I didn't check earlier
