### ISSUE TITLE
version is broken - this.templatesDir doesn't get populated when templatesDir is provided

### ISSUE THREAD

**Issue by nabilnaffar-sf** [asyncapi/generator#91]
generator.js line 66
`if (!templatesDir) this.templatesDir = DEFAULT_TEMPLATES_DIR;`
this.templatesDir doesn't get populated when templatesDir is provided

should be something like:
`this.templatesDir = templatesDir || DEFAULT_TEMPLATES_DIR;`

**Comment by fmvilas** [comment]
You're right. Fixing immediately. Thanks!

**Comment by nabilnaffar-sf** [comment]
Consider moving everything as it to Typescript, it will catch most of those bugs right away ✌️

**Comment by fmvilas** [comment]
Yeah, eventually we'll move to Typescript.

**Comment by fmvilas** [comment]
BTW, it's already published to npm and Docker hub. Version 0.10.1.

**Comment by nabilnaffar-sf** [comment]
tnx, I'll check if it works now

**Comment by nabilnaffar-sf** [comment]
works perfectly! thanks!! 🚀🚀
