### ISSUE TITLE
[Docs Bug 🐞 report]: Grammatical mistakes in Tools: React render engine

### ISSUE THREAD

**Issue by Arya-Gupta** [asyncapi/generator#910]
### Describe the bug you found in AsyncAPI Docs.

There are several grammatical errors in the the docs for [React render engine](https://www.asyncapi.com/docs/tools/generator/react-render-engine).

Here are a few: 
- Incorrect subject verb agreement - 'require' can be changed to 'requires'
- Missing comma after 'Furthermore' 

### Attach any resources that can help us understand the issue.

![image](https://user-images.githubusercontent.com/84087089/215749339-67252822-a77e-46ee-9c95-dd44f7ed82e1.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by derberg** [comment]
@Arya-Gupta I transfered this issue to `generator` repo as sources of the docs are here.

@Florence-Njeri @pratik2315 please have a look

**Comment by Florence-Njeri** [comment]
@derberg Taking a look

**Comment by Florence-Njeri** [comment]
@Arya-Gupta, I've assigned the issue to you. You can start working on it if you like. Remember to read the [contribution guide ](https://github.com/asyncapi/generator/blob/master/CONTRIBUTING.md)

**Comment by Arya-Gupta** [comment]
Thank you @derberg @Florence-Njeri. Can you help me find [this page](https://www.asyncapi.com/docs/tools/generator/react-render-engine) in the generator repo?

**Comment by pratik2315** [comment]
Hey @Arya-Gupta here are the [docs](https://github.com/asyncapi/generator/blob/master/docs/react-render-engine.md) you are looking for. All the docs related stuff is stored under the `generator/docs`

**Comment by Florence-Njeri** [comment]
This issue has been addressed in this [PR](https://github.com/asyncapi/generator/pull/915). Thank you @Arya-Gupta for spotting this and helping us improve the generator docs.
