### ISSUE TITLE
Example generator not complaining about contradictions

### ISSUE THREAD

**Issue by vhe1** [asyncapi/generator#948]
#### Describe the bug
When using allOf for describing a message, and the schemas don't allow for a legal message, I still get an example. Only that example wouldn't validate.

#### How to Reproduce
In a visual studio code instance, with the official asyncApi preview extension installed [(marketplace link)](https://marketplace.visualstudio.com/items?itemName=asyncapi.asyncapi-preview), open this yaml file:
```
asyncapi: '2.6.0'
info:
  title: Contradictory demo
  version: 1.0.0
defaultContentType: application/json
servers:
  ondevice:
    url: localhost
    protocol: mqtt
    bindings:
      mqtt:
        bindingVersion: 0.1.0
        cleanSession: false
channels:
  /message:
    publish:
      operationId: messageOperation
      message:
        payload:
          allOf:
            - type: object
              additionalProperties: false
              required:
                - prop1
              properties:
                prop1:
                  type: string
            - type: object
              additionalProperties: false
              required:
                - prop2
              properties:
                prop2:
                  type: string
```
The preview will contain an example containing both properties:
![image](https://user-images.githubusercontent.com/12475356/234053507-63d42cb4-e41a-454a-a640-8668f629f364.png)

#### Expected behavior
I would have expected

- either an error
- or a message in the example section, detailing that it couldn't create a valid example.

**Comment by vhe1** [comment]
Hello @jonaslagoni !
I'm sorry to mention you directly, but when I created this bug there was apparently a slack error and I fear this bug has been lost in the process.

So I just opened another bug with message traffic and you are the unlucky one. :-(

Maybe you could help me figuring out whether something went wrong during the creation of this bug? My goal is just that someone starts sorting it in or whatever is necessary to get the process going.

**Comment by jonaslagoni** [comment]
@vhe1 this example JSON is generated the [AsyncAPI React component](https://github.com/asyncapi/asyncapi-react) if I am not mistaken.

Regardless, it's impossible (or near it) to detect JSON Schema semantic errors as you have here, the examples are just generated on a "you (as the creator of the schema) know what your doing" approach, i.e. in a best-effort type of approach.

This is something a validator would probably want to give errors on, but as I mentioned, I don't think is possible to do on arbitrary syntactically correct JSON Schema inputs. 

So I don't think this constitutes as a bug. Cause the example is generated as intended IMO. 

You could try raise the issue on the AsyncAPI slack channel or in the other repo, but yea, sorry, cant help you any further then that 🙂

**Comment by derberg** [comment]
no followup, closing
