### ISSUE TITLE
Golang code generation of map attribute doesn't produce the correct payload elements

### ISSUE THREAD

**Issue by dansivret** [asyncapi/generator#957]
#### Describe the bug
Golang code generation of map attribute doesn't produce the correct payload output.

#### How to Reproduce
- Copy the following spec in the http://studio.asyncapi.com 
```
asyncapi: '2.6.0'
info:
  title: map demo
  version: 1.0.0
defaultContentType: application/json
channels:
  demo.topic:
    publish:
      operationId: demoOperation
      message:
        payload:
          $ref: '#/components/schemas/demoMessage'
components:
  schemas:
    someObject:
      type: object
      properties:
        name:
          type: string        
        description:
          type: string  
    demoMessage:
      type: object
      properties:
        name:
          type: string
        MyValue:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/someObject'
      
```
When inspecting the sample payload generated, all looks fine
![Screenshot 2023-04-28 at 2 12 14 PM](https://user-images.githubusercontent.com/44683178/235222972-c04bf609-5e1d-4a67-8784-74dc3fe94f84.png)

- Select `Generate code/docs`
- Select  `GO LANG Watermill Project` 
- Inspect the generated code in the payload.go file

Code generated result is as follows:

```
    
    // DemoMessage represents a DemoMessage model.
type DemoMessage struct {
  Name string `json:"name"`
  MyValue map[string]SomeObject `json:"MyValue"`
  AdditionalProperties map[string]interface{} `json:"additionalProperties"`
}
    
    
    // SomeObject represents a SomeObject model.
type SomeObject struct {
  Name string `json:"name"`
  Description string `json:"description"`
  AdditionalProperties map[string]interface{} `json:"additionalProperties"`
}
    
```
The AdditionalProperties should not be added to the DemoMessage struct and the SomeObject struct.

#### Expected behavior
The expected payload generated code is:
```
    
    // DemoMessage represents a DemoMessage model.
type DemoMessage struct {
  Name string `json:"name"`
  MyValue map[string]SomeObject `json:"MyValue"`
}
    
    
    // SomeObject represents a SomeObject model.
type SomeObject struct {
  Name string `json:"name"`
  Description string `json:"description"`
}
    
```

**Comment by jonaslagoni** [comment]
@dansivret can you clarify why not? Cause the models are generated based on whats defined, i.e. giving you a way to interact with any additional properties.

By setting additionalProperties to false, the models would not have them 🙂

By default its true.

**Comment by jonaslagoni** [comment]
Regarding the serialization of the models, normally that property have to be unwrapped by what ever library you wanna use. Unfortunately there is currently not anything implemented for Go, so yea definitely need that 👍

**Comment by derberg** [comment]
no more reply in 2weeks. closing.

ping if case still needs attention, best with new issue 🙏🏼
