### ISSUE TITLE
Support for application/cloudevents+json 

### ISSUE THREAD

**Issue by murari-goswami** [asyncapi/generator#976]
I am using AsyncAPI in conjunction with cloudevents. For this the default content type as for media I chose as "application/cloudevents+json" as per the official cloudevent spec https://github.com/cloudevents/spec/blob/main/cloudevents/formats/json-format.md. Accordingly, I use  defaultContentType: application/cloudevents+json  in the AsyncAPI specification. All good until here. Later in the process when we generate markdown from the api spec, the AsyncAPI markdown generator puts hyperlink for "application/cloudevents+json" as  https://www.iana.org/assignments/media-types/application/cloudevents+json. Where as iana has no valid "application/cloudevents+json" as media type yet. Can anyone help me here how can "application/cloudevents+json" is registered in iana. Alternatively, can the hyperlink generator from markdown converter be suppressed for this broken link ?

**Comment by AnimeshKumar923** [comment]
is this still valid? @derberg

**Comment by lmgyuan** [comment]
@derberg Do you think this is still valid?

**Comment by derberg** [comment]
we can't really help much in generator. on IANA side and cloudevents mime type - this is not in our scope really.

and regarding markdown template - we need an issue and some idea how we could disable linking to iana -> https://github.com/search?q=repo%3Aasyncapi%2Fmarkdown-template%20iana&type=code - in markdown-template repo

easiest would be to probably add some parameter to disable linking to iana - PR would be appriciated 🙏🏼 

closing it here
