### ISSUE TITLE
AsyncAPI spec v3 support in generator

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator#979]
### Reason/Context
This Issue is used to track changes needed to support AsyncAPI v3. As a code owner, please edit this list of TODO tasks in order to properly track the progress 🙂 Once this issue is closed it means that v3 is now fully supported in this library.  

### Scope

- [ ] https://github.com/asyncapi/parser-js/issues/780
- [ ] Migrate to new JS parser API

**Comment by jonaslagoni** [comment]
We need to add https://github.com/smoya/multi-parser-js as a dependency, and support a new `apiVersion` as `2` along side the rest.

**Comment by derberg** [comment]
I'm all for `apiVersion` flag, main reason is to not harm adoption of future 3.x releases

How removing flag will harm future release:

- forget about v2, lets see we release v3 in September
- imagine `apiVersion` is not there
- generator supports only `Parser API v2`
- imagine there is AsciiDoc template (there actually is one, on GitLab, but imagine different)
- AsciiDoc maintainers took the effort to update the template to support spec v3.0
- Months pass, `Parser API v3` is released for some reason which means:
   - new JS Parser is released (probably major)
   - Generator new major must be released 
- Month after spec 3.1 is released
- AsciiDoc maintainers do not have time to migrate to new Generator and new Parser API
- Community do not adopt 3.1 as they prefer to workaround missing features and just use 3.0

No go for me

Unless we can assure that new Parser API in JS Parser will never mean a breaking change in library API

**Comment by derberg** [comment]
Btw recording of online discussion about the generator -> https://www.youtube.com/watch?v=b4KcouHm958

**Comment by jonaslagoni** [comment]
Agree 👍 

> regarding multi-parser-js - I strongly suggest it is part of the parser, not lib but parser repo, and versioned and released together with JS Parser, to simplify workflows.

It's something we can always figure out how to do at any time, so I am gonna integrate it with the generator to move this issue along.
