### ISSUE TITLE
"required" styling when there are nested objects in payload

### ISSUE THREAD

**Issue by joshg2k** [asyncapi/generator#98]
<img width="1323" alt="Screen Shot 2019-08-21 at 17 19 23" src="https://user-images.githubusercontent.com/4231004/63472461-d5c1bd00-c437-11e9-8b4c-69d8f09726b0.png">

When your payload contains a nested object and you specify that there are required properties in the enveloping object, then the generated "required" text does not render in the correct location(s) or with the correct styling.

**Comment by fmvilas** [comment]
Transferred the issue to this repo. Thanks!
