### ISSUE TITLE
[Docs Bug 🐞 report]: templateParams should be an object instead of string in the JSDoc

### ISSUE THREAD

**Issue by imballinst** [asyncapi/generator#985]
### Describe the bug you found in AsyncAPI Docs.

Hello!

I want to propose line change from this:

https://github.com/asyncapi/generator/blob/76c106b18d53d256df5861a9b2acbb8d0963c2a0/lib/generator.js#L80

to this:

```
   * @param {Object} [options.templateParams]   Optional parameters to pass to the template. Each template define their own params.
```

Reason being is, in the constructor body, `templateParams` is going to be used for `Object.keys`. If string is used with `Object.keys`, it will result in the character indices instead.

```js
> Object.keys("{}")
Array [ "0", "1" ]
```

I can help create a pull request, if this issue is indeed valid. Let me know if I need to provide more information. Thanks!

### Attach any resources that can help us understand the issue.

![image](https://github.com/asyncapi/generator/assets/7077157/5d43be02-3502-4eb7-afaa-dc4f9c402946)

This contradicts with this line:

https://github.com/asyncapi/generator/blob/76c106b18d53d256df5861a9b2acbb8d0963c2a0/lib/generator.js#L125

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by derberg** [comment]
@imballinst you are totally right, can you please open up a PR 🙏🏼
