### ISSUE TITLE
info: contact information does not display in preview pane.

### ISSUE THREAD

**Issue by joshg2k** [asyncapi/generator#99]
<img width="1030" alt="Screen Shot 2019-08-21 at 15 10 57" src="https://user-images.githubusercontent.com/4231004/63465002-f1bc6300-c425-11e9-87c1-d9359f2f5f75.png">

When the specification contains a contact entry in the info section, it is not displayed in the preview panel.

**Comment by fmvilas** [comment]
Transferred the issue to this repo. Thanks.
