### ISSUE TITLE
Date Time format are suppressed to lower case

### ISSUE THREAD

**Issue by murari-goswami** [asyncapi/generator#995]
#### Describe the bug

I got an issue with rendering the Date-Time schema from AsnycAPI to Docuentation. We use the datetime format as YYYY-MM-DDThh:mm:ss.sssZ. However, after rendering through Doc generator it shows the format as yyyy-mm-ddthh:mm:ss.sssz in the documentation of specification.  This can give a misleading information as uppercase 'Z' has been an indication of UTC format where as lowercae 'z' is only signifies the offset. It seems the doc generator converts explicitly this to lower case.

#### How to Reproduce
Run generator to generate document from any specification having date time format as : YYYY-MM-DDThh:mm:ss.sssZ.

#### Expected behavior
The documentation generated from specification should have the same date time format YYYY-MM-DDThh:mm:ss.sssZ.

**Comment by derberg** [comment]
how do you specify this date that renders incorrect? as example?

```
      payload:
        type: string
        format: date-time
        examples:
        - 2023-06-30T00:00:00.000Z
```

please provide more details and also show screen shots

**Comment by AyushNautiyalDeveloper** [comment]
i am recieving correct date-time format. 
![image](https://github.com/asyncapi/generator/assets/138557911/1baab536-6645-4496-961b-5b239b74a41a)

**Comment by derberg** [comment]
closing as no more details provided
